;; Run with: guile --no-auto-compile anchor-confirmation-test.scm ROOT
;; Load the actual continuation-bearing procedures, not copies of their logic.
(use-modules (srfi srfi-1))
(define root (cadr (command-line)))
(define (check value message) (unless value (error message)))
(define (:interactive ignored) #f)
(define == equal?)
(define pending #f)
(define applied '())
(define saved 0)
(define auto? #f)
(define empty? #f)
(define supported? #t)
(define summary (vector 2 1 '() 3 0))
(define (vault-anchor-current-buffer-supported? buf) supported?)
(define (buffer-get-body buf) buf)
(define (vault-anchor-plan body) summary)
(define (vault-anchor-summary-print summary) #f)
(define (vault-anchor-summary-empty? summary) empty?)
(define (vault-anchor-summary-notes-string summary) "plans")
(define (get-preference key) (if auto? "on" "off"))
(define (set-message . args) #f)
(define (native-anchor-enunciations-confirm wraps dead headings notes cont)
  (check (equal? (list wraps dead headings notes) '("2" "1" "3" "plans"))
         "native summary changed")
  (check (procedure? cont) "confirmation needs a continuation")
  (set! pending cont))
(define (vault-anchor-enunciations-confirmed-before-save buf cont)
  (set! applied (cons buf applied))
  (when cont (cont)))
(define vault-anchor-enunciations-confirmed
  vault-anchor-enunciations-confirmed-before-save)

(call-with-input-file
  (string-append root "/ATHENA/progs/athena/athena/tm-vault-anchors.scm")
  (lambda (port)
    (let loop ((form (read port)))
      (unless (eof-object? form)
        (when (and (pair? form) (memq (car form) '(define tm-define))
                   (pair? (cadr form))
                   (memq (caadr form)
                     '(vault-anchor-confirm-native vault-anchor-enunciations
                       vault-anchor-enunciations-before-save)))
          (eval (cons 'define (cdr form)) (current-module)))
        (loop (read port))))))

(for-each
  (lambda (invoke)
    (for-each
      (lambda (accept?)
        (set! pending #f) (set! applied '()) (set! saved 0)
        (invoke "source-buffer" (lambda () (set! saved (+ saved 1))))
        (check pending "confirmation was not requested")
        (check (= saved 0) "save resumed before confirmation")
        (check (null? applied) "anchors changed before confirmation")
        (pending accept?)
        (check (= saved 1) "save continuation must run once, even on rejection")
        (check (equal? applied (if accept? '("source-buffer") '()))
               "confirmation lost its source buffer"))
      '(#t #f)))
  (list vault-anchor-enunciations vault-anchor-enunciations-before-save))

(set! auto? #t) (set! pending #f) (set! saved 0) (set! applied '())
(vault-anchor-enunciations-before-save "automatic" (lambda () (set! saved 1)))
(check (and (not pending) (= saved 1) (equal? applied '("automatic")))
       "automatic approval must bypass the dialog")
(set! auto? #f) (set! empty? #t) (set! saved 0) (set! applied '())
(vault-anchor-enunciations-before-save "empty" (lambda () (set! saved 1)))
(check (and (not pending) (= saved 1) (null? applied))
       "empty plans must save without a dialog")
(set! empty? #f) (set! supported? #f) (set! saved 0)
(vault-anchor-enunciations-before-save "unsupported" (lambda () (set! saved 1)))
(check (and (not pending) (= saved 1)) "unsupported buffers must continue")
(display "PASS: asynchronous anchor approval, cancellation and save continuations\n")
