;; Verify that periodic autosave orchestration returns to the global/UI owner.
(define root (cadr (command-line)))
(define scheduled #f)
(define global-calls 0)
(define autosave-calls 0)
(define in-global? #f)
(define confirmation #f)
(define recovered #f)
(define opened #f)
(define modified #f)
(define permissions-checked #f)
(define :strict ':strict)

(define (check condition message)
  (unless condition (error "Autosave ownership regression" message)))

(define (get-preference key)
  (if (equal? key "autosave") "1" ""))

(define-macro (delayed timing . body)
  `(set! scheduled (lambda () ,@body)))

(define (exec-global thunk)
  (set! global-calls (+ global-calls 1))
  (let ((previous in-global?))
    (dynamic-wind
      (lambda () (set! in-global? #t))
      thunk
      (lambda () (set! in-global? previous)))))

(define (autosave-now)
  (check in-global? "autosave-all must not run on a BufferActor")
  (set! autosave-calls (+ autosave-calls 1)))

(define (nin? item xs) (not (memq item xs)))
(define (autosave-propose name) (string-append name "~"))
(define (autosave-rescue? name) #f)
(define (url->string name) name)
(define (string->url name) name)
(define (url-format name) "texmacs")
(define (tree-import name format) '(document "recovered"))
(define (user-confirm question default cont) (set! confirmation cont))
(define (buffer-set name doc)
  (check in-global? "autosave recovery mutated the buffer registry on a BufferActor")
  (set! recovered (list name doc)))
(define (load-buffer-open name opts)
  (check in-global? "autosave recovery opened a buffer on a BufferActor")
  (set! opened (list name opts)))
(define (buffer-pretend-modified name)
  (check in-global? "autosave recovery marked a buffer on a BufferActor")
  (set! modified name))
(define (load-buffer-check-permissions name opts)
  (check in-global? "autosave fallback checked permissions on a BufferActor")
  (set! permissions-checked (list name opts)))

(define (load-definition wanted)
  (call-with-input-file
    (string-append root "/ATHENA/progs/athena/athena/tm-files.scm")
    (lambda (port)
      (let loop ((form (read port)))
        (cond ((eof-object? form)
               (error "Autosave ownership regression"
                      "definition not found" wanted))
              ((and (pair? form)
                    (or (eq? (car form) 'define) (eq? (car form) 'tm-define))
                    (pair? (cdr form)) (pair? (cadr form))
                    (eq? (caadr form) wanted))
               (eval (if (eq? (car form) 'tm-define)
                         (cons 'define (cdr form)) form)
                     (current-module)))
              (else (loop (read port))))))))

(load-definition 'autosave-delayed)
(load-definition 'load-buffer-check-autosave)

(autosave-delayed)
(check (procedure? scheduled) "autosave timer was not scheduled")
(check (= global-calls 0) "autosave ran before its timer fired")
(check (= autosave-calls 0) "autosave ran before its timer fired")
(scheduled)
(check (= global-calls 1) "autosave timer did not cross through exec-global")
(check (= autosave-calls 1) "autosave-now did not run exactly once")

;; Loading starts globally, but the interactive answer resumes through the
;; active view and can therefore execute on a BufferActor.  The answer must
;; cross back to the global owner before it touches the buffer registry.
(set! in-global? #t)
(load-buffer-check-autosave "/tmp/recovery.tm" '())
(set! in-global? #f)
(check (procedure? confirmation) "autosave recovery did not request confirmation")
(confirmation #t)
(check (= global-calls 2) "autosave recovery did not cross through exec-global")
(check (equal? recovered
               '("/tmp/recovery.tm" (document "recovered")))
       "autosave recovery did not install the recovered document")
(check (equal? opened '("/tmp/recovery.tm" ()))
       "autosave recovery did not open the recovered buffer")
(check (equal? modified "/tmp/recovery.tm")
       "autosave recovery did not preserve modified state")

(set! confirmation #f)
(set! in-global? #t)
(load-buffer-check-autosave "/tmp/recovery.tm" '())
(set! in-global? #f)
(confirmation #f)
(check (= global-calls 3) "autosave rejection did not cross through exec-global")
(check (equal? permissions-checked '("/tmp/recovery.tm" ()))
       "autosave rejection did not resume normal loading globally")

(display "PASS: autosave orchestration and recovery stay on the global owner\n")
