;; Real BufferActor completion: opening/navigating must not mutate the buffer.
;; custom-complete belonged to the retired external-session completion API;
;; exercise the surviving document-word completion path directly instead.
(init-style "generic")
(define initial-mode (get-input-mode))
(define (body) (tree->stree (buffer-tree)))
(define (reset words)
  (buffer-set-body (current-buffer) (stree->tree (cons 'document words)))
  (update-current-buffer)
  (update-forced)
  (tree-go-to (tree-ref (buffer-tree) (- (tree-arity (buffer-tree)) 1)) :end))
(define (start)
  (unless (complete-try?) (error "Document words did not produce candidates")))

(reset '("alpha" "alpine" "al"))
(start)
(unless (equal? (body) '(document "alpha" "alpine" "al"))
  (error "Opening completion inserted text"))
(when (= (get-input-mode) initial-mode) (error "Completion did not open"))
(key-press-complete "down")
(unless (equal? (body) '(document "alpha" "alpine" "al"))
  (error "Navigation inserted text"))
(key-press-complete "tab")
(unless (equal? (body) '(document "alpha" "alpine" "alpine"))
  (error "TAB accepted wrong choice"))
(unless (= (get-input-mode) initial-mode)
  (error "Acceptance left completion active"))

(reset '("alpha" "alpine" "al"))
(start)
(key-press-complete "escape")
(unless (equal? (body) '(document "alpha" "alpine" "al"))
  (error "Cancel changed document"))

(start)
(tree-go-to (tree-ref (buffer-tree) 0) :start)
(key-press-complete "return")
(unless (equal? (body) '(document "alpha" "alpine" "al"))
  (error "Stale cursor accepted completion"))

(reset '("alpha" "al"))
(start)
(unless (equal? (body) '(document "alpha" "al"))
  (error "Single choice inserted eagerly"))
(key-press-complete "return")
(unless (equal? (body) '(document "alpha" "alpha"))
  (error "Enter failed"))

(init-env "page-medium" "paper")
(update-current-buffer)
(update-forced)
(print-to-file (string->url (string-append (getenv "HOME") "/evaluation.pdf")))
