;; Real BufferActor completion: opening/navigating must not mutate the buffer.
;; custom-complete belonged to the retired external-session completion API;
;; exercise the surviving document-word completion path directly instead.
(init-style "generic")
(define initial-mode (get-input-mode))
(define (body) (tree->stree (buffer-tree)))
(define (reset words)
  (buffer-set-body (current-buffer) (stree->tree (cons 'document words)))
  (update-current-buffer)
  (update-forced)
  (tree-go-to (tree-ref (buffer-tree) (- (tree-arity (buffer-tree)) 1)) :end))
(define (start)
  (unless (complete-try?) (error "Document words did not produce candidates")))

(set-boolean-preference "realtime text autocompletion" #t)
(reset '("alpha" "alpine" "a"))
(keyboard-press "l" 0)
(unless (equal? (body) '(document "alpha" "alpine" "al"))
  (error "Realtime completion changed typed text"))
(when (= (get-input-mode) initial-mode)
  (error "Realtime completion did not open while typing"))
(keyboard-press "p" 0)
(unless (equal? (body) '(document "alpha" "alpine" "alp"))
  (error "Realtime completion refresh changed typed text"))
(when (= (get-input-mode) initial-mode)
  (error "Realtime completion did not refresh while typing"))
(key-press-complete "escape")

;; Backslash macro entry uses an inactive HYBRID node.  Its command spelling
;; must not trigger ordinary document-word autocompletion.
(buffer-set-body (current-buffer)
                 (stree->tree
                   '(document "alpha" "alpine" (inactive (hybrid "a")))))
(update-current-buffer)
(update-forced)
(tree-go-to (tree-ref (buffer-tree) 2 0 0) :end)
(keyboard-press "l" 0)
(unless (equal? (body)
                '(document "alpha" "alpine" (inactive (hybrid "al"))))
  (error "Typing in backslash macro input changed the document unexpectedly"))
(unless (= (get-input-mode) initial-mode)
  (error "Realtime completion opened inside backslash macro input"))

(set-boolean-preference "realtime text autocompletion" #f)
(reset '("alpha" "alpine" "a"))
(keyboard-press "l" 0)
(unless (equal? (body) '(document "alpha" "alpine" "al"))
  (error "Disabled realtime completion changed typed text"))
(unless (= (get-input-mode) initial-mode)
  (error "Realtime completion opened while disabled"))

;; Candidate order can stay alphabetical or favor words used more often in
;; the current buffer. Equal-frequency candidates remain alphabetical.
(set-preference "text autocompletion sorting" "alphabetical")
(reset '("alpine" "alpha" "al"))
(start)
(key-press-complete "return")
(unless (equal? (body) '(document "alpine" "alpha" "alpha"))
  (error "Alphabetical completion order selected the wrong candidate"))

(set-preference "text autocompletion sorting" "frequency")
(reset '("alpha" "alpine" "alpine" "alpine" "al"))
(start)
(key-press-complete "return")
(unless (equal? (body)
                '(document "alpha" "alpine" "alpine" "alpine" "alpine"))
  (error "Frequency completion order selected the wrong candidate"))

;; Acceptance can be restricted to Enter or Tab. A disabled acceptance key
;; returns false after closing completion so normal keyboard handling may run.
(set-preference "text autocompletion accept key" "enter")
(reset '("alpha" "al"))
(start)
(when (key-press-complete "tab")
  (error "Tab accepted completion in Enter-only mode"))
(unless (equal? (body) '(document "alpha" "al"))
  (error "Rejected Tab changed the completion text"))
(start)
(unless (key-press-complete "return")
  (error "Enter did not accept completion in Enter-only mode"))
(unless (equal? (body) '(document "alpha" "alpha"))
  (error "Enter-only completion accepted the wrong text"))

(set-preference "text autocompletion accept key" "tab")
(reset '("alpha" "al"))
(start)
(when (key-press-complete "return")
  (error "Enter accepted completion in Tab-only mode"))
(unless (equal? (body) '(document "alpha" "al"))
  (error "Rejected Enter changed the completion text"))
(start)
(unless (key-press-complete "tab")
  (error "Tab did not accept completion in Tab-only mode"))
(unless (equal? (body) '(document "alpha" "alpha"))
  (error "Tab-only completion accepted the wrong text"))

(set-preference "text autocompletion sorting" "alphabetical")
(set-preference "text autocompletion accept key" "both")

(reset '("alpha" "alpine" "al"))
(start)
(unless (equal? (body) '(document "alpha" "alpine" "al"))
  (error "Opening completion inserted text"))
(when (= (get-input-mode) initial-mode) (error "Completion did not open"))
(key-press-complete "down")
(unless (equal? (body) '(document "alpha" "alpine" "al"))
  (error "Navigation inserted text"))
(key-press-complete "tab")
(unless (equal? (body) '(document "alpha" "alpine" "alpine"))
  (error "TAB accepted wrong choice"))
(unless (= (get-input-mode) initial-mode)
  (error "Acceptance left completion active"))

(reset '("alpha" "alpine" "al"))
(start)
(key-press-complete "escape")
(unless (equal? (body) '(document "alpha" "alpine" "al"))
  (error "Cancel changed document"))

(start)
(tree-go-to (tree-ref (buffer-tree) 0) :start)
(key-press-complete "return")
(unless (equal? (body) '(document "alpha" "alpine" "al"))
  (error "Stale cursor accepted completion"))

(reset '("alpha" "al"))
(start)
(unless (equal? (body) '(document "alpha" "al"))
  (error "Single choice inserted eagerly"))
(key-press-complete "return")
(unless (equal? (body) '(document "alpha" "alpha"))
  (error "Enter failed"))

(init-env "page-medium" "paper")
(update-current-buffer)
(update-forced)
(print-to-file (string->url (string-append (getenv "HOME") "/evaluation.pdf")))
