;; Real BufferActor completion: opening/navigating must not mutate the buffer.
(init-style "generic")
(buffer-set-body (current-buffer) (stree->tree '(document "al")))
(go-to-path '(0 0 2))
(define initial-mode (get-input-mode))
(define (body) (tree->stree (buffer-tree)))
(define (start)
  (update-current-buffer)
  (update-forced)
  (custom-complete (stree->tree '(tuple "al" "pha" "pine"))))
(start)
(unless (equal? (body) '(document "al")) (error "First TAB inserted text"))
(when (= (get-input-mode) initial-mode) (error "Completion did not open"))
(key-press-complete "down")
(unless (equal? (body) '(document "al")) (error "Navigation inserted text"))
(key-press-complete "tab")
(unless (equal? (body) '(document "alpine")) (error "TAB accepted wrong choice"))
(unless (= (get-input-mode) initial-mode) (error "Acceptance left completion active"))
(buffer-set-body (current-buffer) (stree->tree '(document "al")))
(go-to-path '(0 0 2))
(start)
(key-press-complete "escape")
(unless (equal? (body) '(document "al")) (error "Cancel changed document"))
(start)
(go-to-path '(0 0 0))
(key-press-complete "return")
(unless (equal? (body) '(document "al")) (error "Stale cursor accepted completion"))
(go-to-path '(0 0 2))
(custom-complete (stree->tree '(tuple "al" "pha")))
(unless (equal? (body) '(document "al")) (error "Single choice inserted eagerly"))
(key-press-complete "return")
(unless (equal? (body) '(document "alpha")) (error "Enter failed"))
(buffer-set-body (current-buffer) (stree->tree '(document "alpha alpine al")))
(go-to-path '(0 0 15))
(update-current-buffer)
(update-forced)
(unless (complete-try?) (error "Document words did not produce candidates"))
(unless (equal? (body) '(document "alpha alpine al")) (error "Document completion inserted eagerly"))
(key-press-complete "escape")
(init-env "page-medium" "paper")
(update-current-buffer)
(update-forced)
(print-to-file (string->url (string-append (getenv "HOME") "/evaluation.pdf")))
