;; Run the real path-search definitions with a deterministic interleaving.
(use-modules (srfi srfi-1) (ice-9 threads))
(define root (cadr (command-line)))
(define (check value message) (unless value (error message)))
(define-syntax-rule (with variable value body ...) (let ((variable value)) body ...))
(define make-ahash-table make-hash-table)
(define ahash-ref hash-ref)
(define (ahash-table->list table)
  (hash-fold (lambda (key value result) (cons (cons key value) result)) '() table))
(define (nnull? value) (not (null? value)))
(define list-sort sort)
(define (lazy-format-force) #f)
(define converter-forward (make-ahash-table))
(define interleave #f)
(define (ahash-set! table key value)
  (hash-set! table key value)
  (when (and interleave (number? value) (= value 0))
    (let ((callback interleave))
      (set! interleave #f)
      (callback))))

(call-with-input-file
  (string-append root "/ATHENA/progs/kernel/athena/tm-convert.scm")
  (lambda (port)
    (let loop ((form (read port)))
      (unless (eof-object? form)
        (when (and (pair? form) (memq (car form) '(define define-public))
                   (memq (if (pair? (cadr form)) (caadr form) (cadr form))
                     '(converter-distance converter-path converter-path-mutex converter-insert
                       converter-walk converter-search)))
          (eval (cons 'define (cdr form)) (current-module)))
        (loop (read port))))))

(define (edge from to cost)
  (unless (hash-ref converter-forward from)
    (hash-set! converter-forward from (make-hash-table)))
  (hash-set! (hash-ref converter-forward from) to cost))
(edge "a" "b" 1.0)
(edge "b" "c" 1.0)
(edge "a" "c" 9.0)
(edge "c" "a" 1.0)
(define nested 'pending)
(set! interleave
  (lambda () (set! nested (converter-search "a" "c"))))
(check (equal? (converter-search "a" "c") '("a" "b" "c"))
       "outer search lost the shortest route")
(check (equal? nested '("a" "b" "c"))
       "concurrent search observed an incomplete route cache")
(check (equal? (converter-search "a" "c") '("a" "b" "c"))
       "completed route cache changed")
(check (equal? (converter-search "a" "a") '("a")) "identity route changed")
(check (not (converter-search "a" "missing")) "unreachable target has a route")
(set! converter-path (make-ahash-table))
(define replacement #f)
(set! interleave
  (lambda ()
    ;; Registration replaces the cache while an older search is in flight.
    (set! replacement (make-ahash-table))
    (set! converter-path replacement)
    (edge "a" "c" 0.5)))
(converter-search "a" "c")
(check (not (hash-ref replacement "a")) "late search repopulated an invalidated cache")
(check (equal? (converter-search "a" "c") '("a" "c"))
       "new generation missed the updated shortest route")
(set! converter-path (make-ahash-table))
(define workers
  (map (lambda (index)
         (call-with-new-thread
           (lambda ()
             (let loop ((remaining 100))
               (or (= remaining 0)
                   (and (equal? (converter-search "a" "c") '("a" "c"))
                        (equal? (converter-search "b" "a") '("b" "c" "a"))
                        (equal? (converter-search "c" "b") '("c" "a" "b"))
                        (loop (- remaining 1))))))))
       (iota 8)))
(check (every identity (map join-thread workers)) "threaded route cache failed")
(display "PASS: interleaved converter searches, shortest paths, cycles and cache\n")
