;; Native generic document environment commands execute on the owning BufferActor.
(import-from (generic document-edit))
(init-style "generic")

(define (check condition message)
  (unless condition
    (error message (get-init-tree "page-medium")
                   (get-init-tree "page-orientation"))))

(define source-mode-next
  (if (string=? (get-env "preamble") "true") "false" "true"))
(check (equal? (in-source-mode?)
               (string=? (get-env "preamble") "true"))
       "source mode predicate matches current environment")
(toggle-source-mode)
(check (equal? (get-init "preamble") source-mode-next)
       "source mode toggle derives next value from current environment")
(when (string=? source-mode-next "true")
  (check (equal? (get-init "src-style") (get-preference "source tree style"))
         "source mode copies source tree style preference")
  (check (equal? (get-init "src-special")
                 (get-preference "source tree special rendering"))
         "source mode copies special rendering preference")
  (check (equal? (get-init "src-compact")
                 (get-preference "source tree compactification"))
         "source mode copies compactification preference")
  (check (equal? (get-init "src-close")
                 (get-preference "source tree closing style"))
         "source mode copies closing style preference"))
(init-default "preamble" "src-style" "src-special" "src-compact" "src-close")

(init-default "page-medium" "page-orientation")
(check (test-default? "page-medium" "page-orientation")
       "multiple defaults initially absent from the init environment")
(check (test-default?) "empty default query is true")

(init-env "page-medium" "paper")
(check (not (test-default? "page-medium"))
       "explicit init value is not default")
(check (test-init? "page-medium" "paper") "native init equality")
(check (equal? (get-init-env "page-medium") "paper")
       "native atomic init lookup")

(init-env-tree "document-test-macro" '(macro "old"))
(check (equal? (get-init-env "document-test-macro") "old")
       "native macro init lookup")
(set-init-env "document-test-macro" "new")
(check (equal? (tree->stree (get-init-tree "document-test-macro"))
               '(macro "new"))
       "set-init-env preserves an existing macro wrapper")
(set-init-env "document-test-macro" '(macro "direct"))
(check (equal? (tree->stree (get-init-tree "document-test-macro"))
               '(macro "direct"))
       "set-init-env does not double-wrap macro input")

(init-env-tree "document-test-complex" '(concat "a" "b"))
(check (not (get-init-env "document-test-complex"))
       "non-atomic non-macro init has no string view")

(init-env "document-test-true" "true")
(check (test-init-true? "document-test-true") "native true init predicate")

(init-default "page-medium" "page-orientation")
(init-multi '("page-medium" "papyrus" "page-orientation" "landscape"))
(check (test-init? "page-medium" "papyrus") "init-multi sets first pair")
(check (test-init? "page-orientation" "landscape") "init-multi sets second pair")
(init-multi (list "page-medium" :default "page-orientation" :default))
(check (test-default? "page-medium" "page-orientation")
       "init-multi handles default keywords")

(init-env "page-medium" "paper")
(init-default "page-medium")
(check (test-default? "page-medium") "native init-default removes explicit value")

(init-page-medium "papyrus")
(check (test-page-medium? "papyrus") "native page-medium setter and predicate")
(init-default-page-medium)
(check (test-default-page-medium?) "native default page-medium")

(init-page-type "a4")
(check (test-page-type? "a4") "native page-type setter and predicate")
(check (and (equal? (get-init "page-width") "auto")
            (equal? (get-init "page-height") "auto"))
       "page type resets explicit dimensions to auto")
(init-page-size "17cm" "23cm")
(check (and (equal? (get-init "page-type") "user")
            (equal? (get-init "page-width") "17cm")
            (equal? (get-init "page-height") "23cm"))
       "native custom page size")
(default-page-type)
(check (test-default-page-type?) "native default page type resets type and size")

(init-page-orientation "landscape")
(check (equal? (get-init "page-orientation") "landscape")
       "native page orientation setter updates initial environment")
(check (equal? (test-page-orientation? "landscape")
               (string=? (get-env "page-orientation") "landscape"))
       "native page orientation predicate matches current environment")
(init-default-page-orientation)
(check (test-default-page-orientation?) "native default page orientation")

(init-env "page-medium" "paper")
(init-env "page-border" "attached")
(init-env "page-packet" "2")
(init-env "page-offset" "1")
(check (equal? (get-init-page-rendering) "book")
       "native page rendering detects book mode")
(check (test-page-rendering? "book")
       "native page rendering predicate")
(document-apply-page-rendering-state "book")
(check (and (equal? (get-init "page-medium") "paper")
            (equal? (get-init "page-border") "attached")
            (equal? (get-init "page-packet") "2")
            (equal? (get-init "page-offset") "1"))
       "native book rendering state")
(init-default-page-rendering)
(check (and (test-default-page-rendering?)
            (not (init-has? "page-border"))
            (not (init-has? "page-packet"))
            (not (init-has? "page-offset")))
       "native default page rendering resets all rendering variables")

(define expected-show-hf
  (if (string=? (get-env "page-show-hf") "true") "false" "true"))
(check (equal? (visible-header-and-footer?)
               (string=? (get-env "page-show-hf") "true"))
       "header/footer predicate matches current environment")
(toggle-visible-header-and-footer)
(check (equal? (get-init "page-show-hf") expected-show-hf)
       "header/footer toggle derives next value from current environment")

(define expected-width-margin
  (if (string=? (get-env "page-width-margin") "true") "false" "true"))
(check (equal? (page-width-margin?)
               (string=? (get-env "page-width-margin") "true"))
       "page width margin predicate matches current environment")
(toggle-page-width-margin)
(check (equal? (get-init "page-width-margin") expected-width-margin)
       "page width margin toggle derives next value from current environment")

(define expected-screen-margin
  (if (string=? (get-env "page-screen-margin") "false") "true" "false"))
(check (equal? (not-page-screen-margin?)
               (string=? (get-env "page-screen-margin") "false"))
       "screen margin predicate matches current environment")
(toggle-page-screen-margin)
(check (equal? (get-init "page-screen-margin") expected-screen-margin)
       "screen margin toggle derives next value from current environment")

(remove-style-package "reduced-margins")
(remove-style-package "normal-margins")
(init-env "page-odd" "1cm")
(check (reduced-margins?) "reduced margin predicate")
(toggle-reduced-margins)
(check (has-style-package? "normal-margins")
       "reduced-margin toggle adds normal override when reduced margins are active")
(toggle-reduced-margins)
(check (not (has-style-package? "normal-margins"))
       "reduced-margin toggle removes normal override first")
(init-env "page-odd" "2cm")
(toggle-reduced-margins)
(check (has-style-package? "reduced-margins")
       "reduced-margin toggle adds reduced package from normal margins")
(remove-style-package "reduced-margins")

(remove-style-package "indent-paragraphs")
(remove-style-package "padded-paragraphs")
(init-env "par-first" "0cm")
(check (not (indent-paragraphs?)) "zero paragraph indent predicate")
(toggle-indent-paragraphs)
(check (has-style-package? "indent-paragraphs")
       "indent toggle adds indent package from zero indent")
(toggle-indent-paragraphs)
(check (not (has-style-package? "indent-paragraphs"))
       "indent toggle removes active indent package")
(init-env "par-first" "1fn")
(check (indent-paragraphs?) "nonzero paragraph indent predicate")
(toggle-indent-paragraphs)
(check (has-style-package? "padded-paragraphs")
       "indent toggle adds padded package from nonzero indent")
(remove-style-package "padded-paragraphs")

(remove-style-package "page-numbers")
(remove-style-package "no-page-numbers")
(init-env "no-page-numbers" "true")
(check (no-page-numbers?) "no-page-numbers predicate")
(toggle-no-page-numbers)
(check (has-style-package? "page-numbers")
       "page-number toggle adds page-numbers override")
(toggle-no-page-numbers)
(check (not (has-style-package? "page-numbers"))
       "page-number toggle removes active override")
(init-env "no-page-numbers" "false")
(toggle-no-page-numbers)
(check (has-style-package? "no-page-numbers")
       "page-number toggle adds no-page-numbers package")
(remove-style-package "no-page-numbers")

(init-env "page-medium" "paper")
(init-env "page-orientation" "landscape")
(update-current-buffer)
(update-forced)
(define (legacy-panorama-packets)
  (let* ((nr (nr-pages))
         (ww (get-window-width))
         (wh (get-window-height))
         (pw (get-page-width #f))
         (ph (get-page-height #f))
         (best-n 0)
         (best-f 0))
    (for (n (.. 1 (+ nr 1)))
      (let* ((r (quotient (+ nr (- n 1)) n))
             (tw (* n pw))
             (th (* r ph))
             (aw (- ww (* n 5120)))
             (ah (- wh (* r 5120)))
             (fw (/ (* 1.0 aw) tw))
             (fh (/ (* 1.0 ah) th))
             (f (min fw fh)))
        (when (or (== n 1) (> f best-f))
          (set! best-n n)
          (set! best-f f))))
    (cond ((> best-n 0) best-n)
          ((> nr 10) 10)
          (else (inexact->exact (ceiling (sqrt (* 1.0 nr))))))))
(check (== (panorama-packets) (legacy-panorama-packets))
       "native panorama packet count matches legacy geometry policy")
(print-to-file (string->url (string-append (getenv "HOME") "/evaluation.pdf")))
#t
