;; Native generic document style commands execute on the owning BufferActor
;; while preserving the public Scheme style extension points.
(import-from (generic document-style))
(init-style "generic")

(define (check condition message . details)
  (unless condition
    (apply error (cons message details))))

(check (equal? (get-style-list) '("generic"))
       "native style-list lookup sees initial generic style")
(check (has-main-style? "generic")
       "native main-style predicate sees initial style")
(check (not (has-no-style?))
       "initial generic style is not empty")
(check (equal? (embedded-style-list "pack-a" "pack-a" "pack-b")
               '("generic" "pack-a" "pack-b"))
       "embedded style list appends unique extra packages")
(check (equal? (style-get-documentation "generic")
               "Default document style")
       "native style documentation reads Scheme synopsis table")
(for-each
  (lambda (key)
    (check (not (style-get-documentation key))
           "unevaluated menu arguments have no style documentation" key))
  '(theme generic (car styles) #f 42))
(let ((action (lambda () (add-style-package theme))))
  (set-procedure-property! action 'source '(lambda () (add-style-package theme)))
  (let* ((source (promise-source action))
         (balloon (property (car source) :balloon)))
    (check (not (apply (car balloon) (cdr source)))
           "menu balloon property accepts an unevaluated style argument")))
(check (equal? (style-get-menu-name "framed-title") "Framed titles")
       "native style menu naming reads Scheme menu table")
(check (equal? (style-get-menu-name "native-unknown-style")
               (upcase-first "native-unknown-style"))
       "native style menu naming preserves fallback policy")
(check (equal? (custom-style-file-name (string->url "/tmp/NativeStyle.ats"))
                "NativeStyle")
       "native custom style filename strips stylesheet suffix")
(check (equal? (custom-style-file-name (string->url "/tmp/LegacyStyle.ts"))
                "LegacyStyle")
       "native custom style filename strips legacy stylesheet suffix")
(check (equal? (custom-style-file-name (string->url "/tmp/NativeStyle"))
               "NativeStyle")
       "native custom style filename preserves extensionless name")
(let* ((style-name "generic.ats")
       (legacy (url-resolve
                 (url-or (url-relative (current-buffer) style-name)
                         (url-append "$ATHENA_STYLE_PATH" style-name))
                 "r")))
  (check (equal? (url-resolve-package "generic") legacy)
         "native style package resolver preserves local-before-global policy"))

(add-style-package "pack-a")
(check (has-style-package? "pack-a")
       "native add-style-package updates actor style state")
(add-style-package "pack-a")
(check (equal? (get-style-list) '("generic" "pack-a"))
       "native normalization removes duplicate packages")
(toggle-style-package "pack-a")
(check (not (has-style-package? "pack-a"))
       "native package toggle removes an active package")
(toggle-style-package "pack-a")
(check (has-style-package? "pack-a")
       "native package toggle adds a missing package")
(remove-style-package* "pack-a")
(check (not (has-style-package? "pack-a"))
       "native starred package removal uses the same mutation path")

(set-no-style)
(check (has-no-style?) "native set-no-style clears the style list")
(check (null? (get-style-list)) "empty style list round-trips natively")
(set-style-list '("generic"))

;; Later category specializations remain authoritative for the native
;; style-overrides? and style-precedes? wrappers.
(tm-define (style-category p)
  (:require (in? p '("native-cat-a" "native-cat-b")))
  :native-test-category)
(check (style-overrides? "native-cat-a" "native-cat-b")
       "native style-overrides dispatches through Scheme style-category")

(tm-define (style-category-precedes? p q)
  (:require (and (== p :native-test-category)
                 (== q :native-later-category)))
  #t)
(tm-define (style-category p)
  (:require (== p "native-later"))
  :native-later-category)
(check (style-precedes? "native-cat-a" "native-later")
       "native style-precedes dispatches through Scheme category policy")

(set-style-list '("generic" "native-cat-a" "native-cat-b"))
(check (equal? (get-style-list) '("generic" "native-cat-b"))
       "native normalization drops package overridden by a later category peer")
(set-style-list '("generic" "native-later" "native-cat-a"))
(check (equal? (get-style-list) '("generic" "native-cat-a" "native-later"))
       "native normalization preserves legacy precedence reordering")

;; Included-package detection remains extensible and is evaluated by the
;; native has-style-package? command against the current normalized list.
(tm-define (style-includes? p q)
  (:require (and (== p "native-bundle") (== q "native-included")))
  #t)
(set-style-list '("generic" "native-bundle" "native-included"))
(check (equal? (get-style-list) '("generic" "native-bundle"))
       "native normalization removes package included by an earlier package")
(set-style-list '("generic" "native-bundle"))
(check (has-style-package? "native-included")
       "native package predicate reaches Scheme style-includes specialization")
(check (not (not-has-style-package? "native-included"))
       "native negated package predicate matches included package")

(set-style-list '("generic"))
(init-env "page-medium" "paper")
(update-current-buffer)
(update-forced)
(print-to-file (string->url (string-append (getenv "HOME") "/evaluation.pdf")))
#t
