;; Native generic document environment commands execute on the owning BufferActor.
(import-from (generic document-edit))
(init-style "generic")

(define (check condition message)
  (unless condition
    (error message (get-init-tree "page-medium")
                   (get-init-tree "page-orientation"))))

(init-default "page-medium" "page-orientation")
(check (test-default? "page-medium" "page-orientation")
       "multiple defaults initially absent from the init environment")
(check (test-default?) "empty default query is true")

(init-env "page-medium" "paper")
(check (not (test-default? "page-medium"))
       "explicit init value is not default")
(check (test-init? "page-medium" "paper") "native init equality")
(check (equal? (get-init-env "page-medium") "paper")
       "native atomic init lookup")

(init-env-tree "document-test-macro" '(macro "old"))
(check (equal? (get-init-env "document-test-macro") "old")
       "native macro init lookup")
(set-init-env "document-test-macro" "new")
(check (equal? (tree->stree (get-init-tree "document-test-macro"))
               '(macro "new"))
       "set-init-env preserves an existing macro wrapper")
(set-init-env "document-test-macro" '(macro "direct"))
(check (equal? (tree->stree (get-init-tree "document-test-macro"))
               '(macro "direct"))
       "set-init-env does not double-wrap macro input")

(init-env-tree "document-test-complex" '(concat "a" "b"))
(check (not (get-init-env "document-test-complex"))
       "non-atomic non-macro init has no string view")

(init-env "document-test-true" "true")
(check (test-init-true? "document-test-true") "native true init predicate")

(init-default "page-medium" "page-orientation")
(init-multi '("page-medium" "papyrus" "page-orientation" "landscape"))
(check (test-init? "page-medium" "papyrus") "init-multi sets first pair")
(check (test-init? "page-orientation" "landscape") "init-multi sets second pair")
(init-multi (list "page-medium" :default "page-orientation" :default))
(check (test-default? "page-medium" "page-orientation")
       "init-multi handles default keywords")

(init-env "page-medium" "paper")
(init-default "page-medium")
(check (test-default? "page-medium") "native init-default removes explicit value")

(init-page-medium "papyrus")
(check (test-page-medium? "papyrus") "native page-medium setter and predicate")
(init-default-page-medium)
(check (test-default-page-medium?) "native default page-medium")

(init-page-type "a4")
(check (test-page-type? "a4") "native page-type setter and predicate")
(check (and (equal? (get-init "page-width") "auto")
            (equal? (get-init "page-height") "auto"))
       "page type resets explicit dimensions to auto")
(init-page-size "17cm" "23cm")
(check (and (equal? (get-init "page-type") "user")
            (equal? (get-init "page-width") "17cm")
            (equal? (get-init "page-height") "23cm"))
       "native custom page size")
(default-page-type)
(check (test-default-page-type?) "native default page type resets type and size")

(init-page-orientation "landscape")
(check (equal? (get-init "page-orientation") "landscape")
       "native page orientation setter updates initial environment")
(check (equal? (test-page-orientation? "landscape")
               (string=? (get-env "page-orientation") "landscape"))
       "native page orientation predicate matches current environment")
(init-default-page-orientation)
(check (test-default-page-orientation?) "native default page orientation")

(define expected-show-hf
  (if (string=? (get-env "page-show-hf") "true") "false" "true"))
(check (equal? (visible-header-and-footer?)
               (string=? (get-env "page-show-hf") "true"))
       "header/footer predicate matches current environment")
(toggle-visible-header-and-footer)
(check (equal? (get-init "page-show-hf") expected-show-hf)
       "header/footer toggle derives next value from current environment")

(define expected-width-margin
  (if (string=? (get-env "page-width-margin") "true") "false" "true"))
(check (equal? (page-width-margin?)
               (string=? (get-env "page-width-margin") "true"))
       "page width margin predicate matches current environment")
(toggle-page-width-margin)
(check (equal? (get-init "page-width-margin") expected-width-margin)
       "page width margin toggle derives next value from current environment")

(define expected-screen-margin
  (if (string=? (get-env "page-screen-margin") "false") "true" "false"))
(check (equal? (not-page-screen-margin?)
               (string=? (get-env "page-screen-margin") "false"))
       "screen margin predicate matches current environment")
(toggle-page-screen-margin)
(check (equal? (get-init "page-screen-margin") expected-screen-margin)
       "screen margin toggle derives next value from current environment")

(init-env "page-medium" "paper")
(init-env "page-orientation" "landscape")
(update-current-buffer)
(update-forced)
(print-to-file (string->url (string-append (getenv "HOME") "/evaluation.pdf")))
#t
