;; Native formatting commands execute on an actual BufferActor-owned document.
(import-from (generic format-drd) (generic generic-edit) (table table-edit) (source macro-search))
(init-style "generic")
(define (body) (tree->stree (buffer-tree)))
(define (node) (tree-ref (buffer-tree) 0))
(define (check condition message)
  (unless condition (error message (body) (cursor-path))))
(define (reset content)
  (selection-cancel)
  (buffer-set-body (current-buffer) (stree->tree `(document ,content)))
  (update-current-buffer)
  (tree-go-to (node) :end)
  (commit-changes)
  (clear-undo-history))

;; JSON metadata is native, while non-generic domain extensions still compose.
(check (and (procedure? make-interactive-with)
            (procedure? make-interactive-line-with)
            (procedure? make-interactive-with-opacity)
            (procedure? make-alternate))
       "native interactive formatting bindings available without format-edit")
(check (equal? (logic-ref env-var-description% "par-left") "Left margin")
       "interactive formatting prompt descriptions available at startup")
(check (equal? (standard-parameters "float") '("page-float-sep")) "float parameters")
(check (equal? (standard-parameters "reference") '()) "known parameterless primitive")
(check (not (standard-parameters "format-test-unknown")) "unknown primitive stays false")
(check (equal? (standard-parameters "locus") '("locus-color" "visited-color")) "locus parameters")
(check (focus-has-preferences? (stree->tree '(float ""))) "float preferences")
(check (not (focus-has-preferences? (stree->tree "text"))) "atomic tree has no preferences")
(check (equal? (parameter-choice-list "ornament-shape") '("classic" "rounded" "angular" "cartoon"))
       "ornament choices have no other sentinel")
(check (equal? (parameter-choice-list "hmagnified-factor")
               '("0.2" "0.5" "0.8" "0.9" "1.1" "1.2" "1.5" "2" "5" :other))
       "suffix choice rule and symbol sentinel")
(check (equal? (parameter-choice-list "blur-pen-angle")
               '("-60" "-45" "-30" "0" "30" "45" "60" "90" :other)) "pen angles")
(check (not (parameter-choice-list "format-test-unknown")) "unknown parameter choices")
(check (equal? (customizable-parameters (stree->tree '(extended "")))
               '(("extended-factor" "Factor"))) "extended has its own factor")
(check (equal? (customizable-parameters (stree->tree '(monospaced "")))
               '(("monospaced-factor" "Factor"))) "monospaced factor targets monospaced")
(check (equal? (customizable-parameters (stree->tree '(motion-blur "")))
               '(("blur-pen-dx" "Pen dx") ("blur-pen-dy" "Pen dy"))) "motion pen parameters")
(check (null? (customizable-parameters-memo (stree->tree '(format-test-custom ""))))
       "unknown customization is empty")
(tm-define (customizable-parameters t)
  (:require (tree-is? t 'format-test-custom))
  '(("format-test-value" "Value")))
(check (equal? (customizable-parameters-memo (stree->tree '(format-test-custom "")))
               '(("format-test-value" "Value"))) "newly loaded rules are not hidden by stale cache")
(check (customizable-context? (stree->tree '(format-test-custom ""))) "customization extension context")
(tm-define (parameter-choice-list variable)
  (:require (== variable "format-test-value"))
  '("one" "two"))
(check (equal? (parameter-choice-list "format-test-value") '("one" "two")) "choice extension")
(check (equal? (parameter-choice-list "degraded-threshold") '("0.5" "0.6" "0.667" "0.75" :other))
       "native choice fallback remains reachable")
(tm-define (standard-parameters tag)
  (:require (== tag "format-test-standard"))
  '("format-test-parameter"))
(check (equal? (standard-parameters "format-test-standard")
               '("format-test-parameter"))
       "standard parameter extension")
(check (equal? (standard-parameters "float") '("page-float-sep"))
       "native standard fallback remains reachable")
(tm-define (focus-has-preferences? t)
  (:require (tree-is? t 'format-test-no-preferences))
  #f)
(check (not (focus-has-preferences?
             (stree->tree '(format-test-no-preferences ""))))
       "focus preference extension overrides native extension fallback")
(check (focus-has-preferences? (stree->tree '(format-test-native "")))
       "native extension focus fallback remains reachable")

(reset '(with "color" "red" "color" "blue" "text"))
(check (tm-equal? (with-ref (node) "color") "red") "with-ref first match")
(check (tm-equal? (tree-with-get (node) "color") "blue") "tree-with-get last match")
(check (not (with-ref (node) "missing")) "missing property")
(check (not (tree-with-get #f "color")) "absent tree")
(let ((detached (stree->tree '(with "color" "red" "text"))))
  (check (equal? (tree->stree (with-set detached "color" "blue"))
                 '(with "color" "blue" "text")) "detached with-set returns wrapper"))
(with-set (node) "color" "green")
(check (equal? (body) '(document (with "color" "green" "color" "blue" "text")))
       "with-set changes first matching value")
(with-set (node) "font-series" "bold")
(check (equal? (body)
               '(document (with "color" "green" "color" "blue" "font-series" "bold" "text")))
       "with-set appends property before body")

(reset "text")
(let* ((text (node)) (pointer (tree->tree-pointer text)))
  (tree-go-to text 2)
  (with-set text "color" "red")
  (check (equal? (body) '(document (with "color" "red" "text"))) "wrap text")
  (check (equal? (tree->path (tree-pointer->tree pointer)) (tree->path (node) 2))
         "wrapping preserves the original text observer")
  (check (equal? (cursor-path) (tree->path (node) 2 2)) "wrapping preserves cursor")
  (tree-pointer-detach pointer))
(commit-changes)
(undo 0)
(check (equal? (body) '(document "text")) "wrapping is undoable")

(reset '(with "color" "red" (with "font-series" "bold" "text")))
(with-merge (tree-ref (node) 2))
(check (equal? (body) '(document (with "color" "red" "font-series" "bold" "text")))
       "merge adjacent wrappers")
(reset '(with "color" "red" (with "color" "blue" "text")))
(with-merge (tree-ref (node) 2))
(check (tm-equal? (tree-with-get (node) "color") "blue") "inner properties take precedence")

(reset '(with "color" "red" "font-series" "bold" (with "color" "blue" "text")))
(with-simplify (tree-ref (node) 4))
(check (equal? (body) '(document (with "font-series" "bold" (with "color" "blue" "text"))))
       "simplify removes only shadowed outer properties")
(reset '(with "color" "red" (document (with "color" "blue" "text"))))
(with-simplify (tree-ref (node) 2 0))
(check (equal? (body) '(document (with "color" "blue" "text")))
       "simplify crosses a single-paragraph document")
(reset '(with "color" "red" (document (with "color" "blue" "text") "other")))
(with-simplify (tree-ref (node) 2 0))
(check (equal? (body)
               '(document (with "color" "red" (document (with "color" "blue" "text") "other"))))
       "simplify must not change another paragraph's environment")

(reset "text")
(tree-with-set (node) "color" "red" "font-series" "bold")
(check (equal? (body) '(document (with "color" "red" "font-series" "bold" "text")))
       "variadic binding passes all property pairs")
(tree-with-set (tree-ref (node) 4) "color" "blue")
(check (equal? (body) '(document (with "font-series" "bold" "color" "blue" "text")))
       "tree-with-set simplifies and merges")
(tree-with-reset (tree-ref (node) 4) "color")
(check (equal? (body) '(document (with "font-series" "bold" "text"))) "reset inherited property")
(tree-with-reset (tree-ref (node) 2) "font-series")
(check (equal? (body) '(document "text")) "reset unwraps empty formatting")
(tree-with-reset #f "color")
(tree-with-set (node))
(check (equal? (body) '(document (with "text"))) "variadic binding accepts no pairs")

(reset '(with "color" "red" "color" "blue" "text"))
(tree-with-reset (tree-ref (node) 4) "color")
(check (equal? (body) '(document (with "color" "red" "text"))) "reset removes last duplicate only")

(reset "picked")
(selection-set (tree->path (node) 0) (tree->path (node) 6))
(toggle-bold)
(check (equal? (body) '(document (with "font-series" "bold" "picked"))) "bold selected text")
(selection-cancel)
(tree-go-to (node) 2 :end)
(toggle-bold)
(check (equal? (body) '(document (with "font-series" "bold" "picked"))) "toggle at end does not edit text")
(check (equal? (cursor-path) (tree->path (node) 1)) "toggle leaves wrapper at end")
(tree-go-to (node) 2 :start)
(toggle-bold)
(check (equal? (cursor-path) (tree->path (node) 0)) "toggle leaves wrapper at start")
(tree-go-to (node) 2 3)
(check (with-like-check-insert '(with "font-series" "bold" "")) "detect existing wrapper")

(reset "picked")
(selection-set (tree->path (node) 0) (tree->path (node) 6))
(toggle-underlined)
(check (equal? (body) '(document (underline "picked"))) "underline selected text")
(selection-cancel)
(tree-go-to (node) 0 3)
(toggle-underlined)
(check (equal? (body) '(document "picked")) "underline toggles off without fallback")

(reset "picked")
(selection-set (tree->path (node) 0) (tree->path (node) 6))
(make-with-like '(with-opacity "50%" ""))
(check (equal? (body) '(document (with-opacity "50%" "picked"))) "non-unary with-like selection")

(reset "")
(make-multi-with '("color" "red" "font-series" "bold"))
(check (equal? (body) '(document (with "color" "red" "font-series" "bold" "")))
       "insert multiple formatting properties")
(check (equal? (cursor-path) (tree->path (node) 4 0)) "multi-with cursor starts inside body")
(reset '(with "color" "red" "picked"))
(selection-set (tree->path (node) 2 0) (tree->path (node) 2 6))
(make-multi-with '("color" "blue" "font-series" "bold"))
(check (equal? (body) '(document (with "color" "blue" "font-series" "bold" "picked")))
       "multi-with simplifies shadowed outer formatting")
(check (selection-active-any?) "multi-with reselects formatted text")
(reset "paragraph")
(make-line-with "par-mode" "center")
(check (equal? (body) '(document (with "par-mode" "center" (document "paragraph"))))
        "paragraph formatting without explicit selection")
(reset "paragraph")
(make-multi-line-with '("par-mode" "center" "par-left" "1cm"))
(check (equal? (body)
               '(document (with "par-mode" "center" "par-left" "1cm"
                                (document "paragraph"))))
        "multiple paragraph properties")

(reset '(blur "text"))
(check (equal? (get-effect-pen (node)) "gaussian") "default blur pen")
(tree-go-to (node) 0 2)
(set-effect-pen #f "motion")
(check (equal? (body) '(document (motion-blur "text"))) "change innermost effect pen")
(check (equal? (get-effect-pen #f) "motion") "lookup pen at cursor")
(check (test-effect-pen? (node) "motion") "effect menu checkmark")
(set-effect-pen (node) "invalid")
(check (equal? (body) '(document (motion-blur "text"))) "unknown pen leaves document alone")
(reset '(outline "text"))
(check (equal? (get-effect-pen (node)) "oval") "default outline pen")
(reset '(erode "text"))
(check (equal? (get-effect-pen (node)) "rectangular") "default erode pen")

(reset '(tabular (tformat (table (row (cell "A") (cell "B"))))))
(tree-go-to (node) 0 0 0 0 0 0)
(table-select-cells 1 1 1 2)
(check (selection-active-table?) "fixture has a two-cell selection")
(make-multi-with '("color" "red" "font-series" "bold"))
(selection-cancel)
(table-go-to 1 1)
(check (equal? (cell-get-format "color") "red") "first cell formatting")
(check (equal? (cell-get-format "font-series") "bold") "first cell second property")
(table-go-to 1 2)
(check (equal? (cell-get-format "color") "red") "second cell formatting")
(check (equal? (cell-get-format "font-series") "bold") "second cell second property")

(init-env "page-medium" "paper")
(update-current-buffer)
(update-forced)
(print-to-file (string->url (string-append (getenv "HOME") "/evaluation.pdf")))
