;; Remaining generic editing commands preserve their Scheme behavior.
(import-from (generic generic-edit))
(import-from (graphics graphics-utils))
(module-provide '(generic live-spell))
(init-style "generic")

(define (body) (tree->stree (buffer-tree)))
(define (check value message)
  (unless value (error "Generic native regression" message (body) (cursor-path))))
(define (reset content cursor)
  (selection-cancel)
  (cancel-alt-selection "spell-live")
  (buffer-set-body (current-buffer) (stree->tree content))
  (update-current-buffer)
  ;; Clipboard copying inspects layout boxes even in a headless editor.
  (update-forced)
  (go-to cursor)
  (commit-changes)
  (clear-undo-history))

(reset '(document "abcdef" "next") '(0 0 2))
(check (not (path->tree #f)) "false path is harmless")
(check (== (graphics-path-property #f "magnify") "default")
       "missing graphics path uses property default")
(check (== (graphics-eval-magnify) "default")
       "missing graphics context uses magnify default")
(check (== (graphics-eval-magnify-at #f) "default")
       "missing graphics object uses magnify default")
(yank-paragraph)
(check (equal? (body) '(document "abcdef" "next")) "yank keeps paragraph")
(check (equal? (tree->stree (selection-tree)) "cdef") "yank selects paragraph suffix")
(reset '(document "abcdef" "next") '(0 0 2))
(kill-paragraph)
(check (equal? (body) '(document "ab" "next")) "kill removes paragraph suffix only")
(check (equal? (cursor-path) '(0 0 2)) "kill cursor")
(commit-changes)
(undo 0)
(check (equal? (body) '(document "abcdef" "next")) "kill is undoable")

(define (legacy-graphics-selection)
  (when (selection-active-any?)
    (let ((selected (selection-tree)))
      (clipboard-cut "graphics background")
      (insert-go-to `(draw-over ,selected (graphics) "0cm") '(1 1)))))
(define (legacy-graphics)
  (let ((graphics '(with "gr-mode" (tuple "hand-edit" "penscript") (graphics)))
        (selected (if (selection-active-any?) (selection-tree) "")))
    (when (selection-active-any?) (clipboard-cut "graphics background"))
    (insert-go-to `(draw-over ,selected ,graphics "2cm") '(1 2 1))))
(define (legacy-balloon)
  (wrap-selection-small
    (insert-go-to '(inactive (hover-balloon "" "" "left" "Bottom")) '(0 0 0))))

(define (compare-edit legacy native selected?)
  (define (prepare)
    (reset '(document "abcd") '(0 0 2))
    (when selected? (selection-set '(0 0 1) '(0 0 3))))
  (prepare)
  (legacy)
  (let ((expected-body (body)) (expected-cursor (cursor-path)))
    (prepare)
    (native)
    (check (equal? (body) expected-body) "native edit produces the same tree")
    (check (equal? (cursor-path) expected-cursor) "native edit leaves the same cursor")))
(for-each
  (lambda (selected?)
    (compare-edit legacy-graphics-selection make-graphics-over-selection selected?)
    (compare-edit legacy-graphics make-graphics-over selected?)
    (compare-edit legacy-balloon make-balloon selected?))
  '(#f #t))

(reset '(document "helo world") '(0 0 2))
(set-alt-selection "spell-live" '((0 0 0) (0 0 4)))
(spell-live-replace-current-word "hello")
(check (equal? (body) '(document "hello world")) "spelling replacement")
(check (equal? (cursor-path) '(0 0 5)) "spelling replacement cursor")
(undo 0)
(check (equal? (body) '(document "helo world")) "spelling replacement undo group")
(cancel-alt-selection "spell-live")
(spell-live-replace-current-word "ignored")
(spell-live-insert-current-word)
(check (equal? (body) '(document "helo world")) "missing spelling selection is harmless")

(check (equal? (background-selector-initial "pattern" #f "25pt")
               '("$ATHENA_PATH/misc/patterns/neutral-pattern.png" "25pt" "100@" "" ""))
       "pattern defaults")
(check (equal? (background-selector-initial "picture" #f "25pt")
               '("$ATHENA_PATH/misc/patterns/neutral-pattern.png" "100%" "100%" "" ""))
       "picture defaults")
(check (equal? (background-selector-initial "gradient" #f "25pt")
               '("athena-gradient-vertical" "100%" "100%" "0" "black" "white"))
       "gradient defaults")
(define image-pattern
  '(pattern "image.png" "3cm" "4cm" (eff-skin (eff-recolor "0" "red") "blue")))
(for-each
  (lambda (old)
    (check (equal? (background-selector-initial "picture" old "100%")
                   '("image.png" "3cm" "4cm" "red" "blue"))
           "nested image effects accept trees and strees"))
  (list image-pattern (stree->tree image-pattern)))
(check (equal? (background-selector-result
                "picture" (background-selector-initial "picture" image-pattern "100%"))
               image-pattern)
       "image effect roundtrip")
(check (equal? (background-selector-result "picture" '("x.png" "1cm" "2cm"))
               '(pattern "x.png" "1cm" "2cm"))
       "image without effects omits extra child")
(check (equal? (background-selector-result "picture" '("x.png" "1cm" "2cm" "" "green"))
               '(pattern "x.png" "1cm" "2cm" (eff-skin "0" "green")))
       "skin without recoloring")
(define gradient
  '(pattern "athena-gradient-vertical" "9cm" "8cm" (eff-gradient "45" "red" "blue")))
(check (equal? (background-selector-result
                "gradient" (background-selector-initial "gradient" gradient "100%"))
               gradient)
       "gradient roundtrip")
(check (equal? (background-selector-initial "gradient" '(not-a-pattern "x") "100%")
               (background-selector-initial "gradient" #f "100%"))
       "invalid old pattern falls back")
(check (not (background-selector-result "pattern" '())) "cancelled selector")
(check (not (background-selector-result "gradient" '("x" "w" "h")))
       "incomplete gradient result")
;; Headless cancellation exercises public bindings without opening real dialogs.
(define (unexpected-callback value) (error "Headless selector invoked callback" value))
(open-pattern-selector unexpected-callback "25pt")
(open-gradient-selector unexpected-callback)
(open-gradient-selector unexpected-callback (stree->tree gradient))
(open-background-picture-selector unexpected-callback image-pattern)

(reset '(document "Generic native commands passed") '(0 0 0))
(init-env "page-medium" "paper")
(update-current-buffer)
(update-forced)
(print-to-file (string->url (string-append (getenv "HOME") "/evaluation.pdf")))
