;; Generic editor commands execute on the owning BufferActor.
(import-from (generic generic-edit))
(import-from (generic generic-menu))
(import-from (generic generic-doc))
(init-style "generic")

(define (body) (tree->stree (buffer-tree)))
(define (check condition message)
  (unless condition
    (error message (body) (cursor-path)
           (if (selection-active-any?)
               (list (selection-get-start) (selection-get-end)) '()))))
(define (reset content cursor)
  (selection-cancel)
  (buffer-set-body (current-buffer) (stree->tree content))
  (update-current-buffer)
  (go-to cursor)
  (commit-changes)
  (clear-undo-history))
(reset '(document "abc" "def") '(0 0 1))
(select-all)
(check (selection-active-any?) "select-all activates selection")
(check (equal? (selection-get-start) '(0 0)) "select-all start")
(check (equal? (selection-get-end) '(0 1)) "select-all end")

(reset '(document "aa" "bb" "cc") '(0 0 1))
(go-to-line 2)
(check (equal? (cursor-path) '(0 2 0)) "go-to-line")

(reset '(document "abcdef") '(0 0 1))
(go-to-column 4)
(check (equal? (cursor-path) '(0 0 4)) "go-to-column")

(reset '(document "zero alpha beta alpha") '(0 0 12))
(let ((result (select-word "alpha" (tree-ref (buffer-tree) 0) 18)))
  (check (= result 16) "select-word result"))
(check (equal? (selection-get-start) '(0 0 16)) "select-word start")
(check (equal? (selection-get-end) '(0 0 21)) "select-word end")

(reset '(document "no match") '(0 0 2))
(check (not (select-word "alpha" (tree-ref (buffer-tree) 0) 2))
       "select-word missing result")
(check (not (selection-active-any?)) "missing word leaves selection inactive")

(check (equal? (search-parameters "reference")
               '("locus-color" "visited-color"))
       "reference search parameters")
(check (null? (search-parameters "not-a-reference"))
       "unknown search parameters remain empty after macro discovery")

(reset '(document "abc") '(0 0 1))
(label-insert (buffer-tree))
(check (equal? (body) '(document (concat "a" (inactive (label "")) "bc")))
       "generic label insertion")
(check (equal? (cursor-path) '(0 0 1 0 0 0)) "label insertion cursor")

;; Later Scheme specializations still intercept the native baseline.
(tm-define (label-insert t)
  (:require (tree-is? t 'label-test-extension))
  (tree-set! t 0 "handled"))
(buffer-set-body (current-buffer)
                 (stree->tree '(document (label-test-extension "x"))))
(update-current-buffer)
(tree-go-to (tree-ref (buffer-tree) 0 0) :end)
(label-insert (tree-ref (buffer-tree) 0 0))
(check (equal? (body) '(document (label-test-extension "handled")))
       "label outward dispatch reaches Scheme extension")
(tree-set! (tree-ref (buffer-tree) 0) 0 "x")
(tree-go-to (tree-ref (buffer-tree) 0 0) :end)
(make-label)
(check (equal? (body) '(document (label-test-extension "handled")))
       "no-argument make-label reaches Scheme label specialization")

(reset '(document "abc") '(0 0 1))
(recenter-window)

(reset '(document "ab") '(0 0 1))
(make-link-image '("linked.png" "2cm" "3cm" "4cm" "5cm"))
(check (equal? (body)
               '(document (concat "a"
                                  (image "linked.png" "2cm" "3cm" "4cm" "5cm")
                                  "b")))
       "linked image wrapper preserves path and dimensions")

(reset '(document "ab") '(0 0 1))
(make-inline-image
  '("$ATHENA_PATH/misc/images/windows/SmallTile.png" "1cm" "" "" ""))
(check (tree-is? (tree-ref (buffer-tree) 0 1) 'image)
       "inline image wrapper inserts an image node")
(check (= (tree-arity (tree-ref (buffer-tree) 0 1)) 5)
       "inline image wrapper preserves image arity")
(check (equal? (tree->stree (tree-ref (buffer-tree) 0 1 1)) "1cm")
       "inline image wrapper preserves requested width")

(reset '(document "") '(0 0 0))
(make-thumbnails-sub
  (list (string->url "one.png")
        (string->url "two.png")
        (string->url "three.png"))
  2)
(check (equal? (body)
               '(document
                  (tabular*
                    (tformat
                      (twith "table-width" "1par")
                      (twith "table-hyphen" "yes")
                      (table
                        (row
                          (cell (image "one.png" "0.48par" "" "" ""))
                          (cell (image "two.png" "0.48par" "" "" "")))
                        (row
                          (cell (image "three.png" "0.48par" "" "" ""))
                          (cell "")))))))
       "native thumbnail builder preserves rows, width, and padding")

(check (not (focus-label (stree->tree '(focus-unknown "x"))))
       "generic focus-label baseline is false")

;; Generic focus-menu field policy is native but must continue to agree with
;; the DRD and rich-length primitives that define its semantics.
(define menu-with (stree->tree '(with "foo-bar" "value" "body")))
(check (equal? (string-variable-name? menu-with 0)
               (and (equal? (tree-child-type menu-with 0) "variable")
                    (tree-in? menu-with '(with attr style-with style-with*))
                    (tree-atomic? (tree-ref menu-with 0))
                    (not (equal? (tree->stree (tree-ref menu-with 0)) ""))))
       "native string-variable predicate matches DRD primitives")
(check (equal? (hidden-child? menu-with 1)
               (and (not (tree-accessible-child? menu-with 1))
                    (not (string-variable-name? menu-with 1))
                    (not (equal? (type->format (tree-child-type menu-with 1))
                                 "n.a."))))
       "native hidden-child policy matches accessibility and format rules")
(check (equal? (tree-child-name* menu-with 1)
               (let ((name (tree-child-name menu-with 1)))
                 (if (not (equal? name "")) name
                     (if (string-variable-name? menu-with 0)
                         (string-replace (tree->string (tree-ref menu-with 0))
                                         "-" " ")
                         (let ((type (tree-child-type menu-with 1)))
                           (if (equal? type "regular") "" type))))))
       "native child name fallback matches variable-name policy")
(check (equal? (type->format "raw") "n.a.")
       "native type format rejects raw fields")
(check (equal? (type->format "url") (if (qt-gui?) "string" "smart-file"))
       "native URL input format preserves GUI policy")
(check (equal? (type->width "length") "5em")
       "native type width preserves compact length field")
(check (equal? (type->width "identifier") "8em")
       "native type width preserves identifier field width")
(define rich-length (stree->tree '(plus "1cm" "2pt")))
(check (equal? (inputter-active? rich-length "length")
               (tm-rich-length? rich-length))
       "native inputter activity matches rich-length predicate")
(check (equal? (inputter-decode rich-length "length")
               (tm->rich-length rich-length))
       "native inputter decode matches rich-length formatter")
(check (equal? (tm->stree (inputter-encode "1cm+2pt" "length"))
               (tm->stree (rich-length->tm "1cm+2pt")))
       "native inputter encode matches rich-length parser")
(check (equal? (inputter-encode "plain" "string") "plain")
       "native inputter encode preserves ordinary strings")

(parameter-set "page-screen-margin" "true" :global)
(check (parameter-test? "page-screen-margin" "true" :global)
       "native global parameter test sees explicit value")
(check (equal? (parameter-get "page-screen-margin" :global) "true")
       "native global parameter getter preserves string value")
(check (equal? (parameter-get-string "page-screen-margin" :global) "true")
       "native global parameter string getter preserves string value")
(check (not (parameter-default? "page-screen-margin" :global))
       "native global parameter default predicate sees explicit override")
(check (parameter-enabled? "page-screen-margin" :global)
       "native parameter-enabled delegates to true-value policy")
(parameter-reset "page-screen-margin" :global)
(check (parameter-default? "page-screen-margin" :global)
       "native global parameter reset clears explicit override")

(define (legacy-focus-doc-arg-name t i previous)
  (let* ((raw (tree-child-name t i))
         (base (cond ((not (equal? raw "")) raw)
                     ((equal? (tree-child-type t i) "regular") "body")
                     (else (tree-child-type t i)))))
    (let loop ((n 1))
      (let ((candidate (if (= n 1) base
                           (string-append base (number->string n)))))
        (if (member candidate previous) (loop (+ n 1)) candidate)))))
(define (legacy-focus-doc-arg-names t i previous)
  (if (>= i (tree-arity t)) '()
      (let ((name (legacy-focus-doc-arg-name t i previous)))
        (cons name
              (legacy-focus-doc-arg-names t (+ i 1) (cons name previous))))))
(define doc-name-tree
  (stree->tree '(with "foo" "one" "foo" "two" "body")))
(check (equal? (focus-doc-arg-names doc-name-tree 0 '())
               (legacy-focus-doc-arg-names doc-name-tree 0 '()))
       "native documentation argument naming preserves DRD conflict policy")
(check (equal? (focus-doc-arg-names doc-name-tree 1 '("body" "value"))
               (legacy-focus-doc-arg-names doc-name-tree 1 '("body" "value")))
       "native documentation argument naming honors existing names")

(check (parameter-value? "plain")
       "native parameter value predicate accepts strings")
(check (parameter-value? '("Label" "value"))
       "native parameter value predicate accepts labelled pairs")
(check (not (parameter-value? '(1 "value")))
       "native parameter value predicate rejects nonstring labels")
(check (equal? (parameter-name "page-screen-margin")
               (focus-tag-name
                 (string->symbol
                   (tree-name (list (string->symbol "page-screen-margin"))))))
       "native parameter naming preserves focus tag naming policy")
(check (equal? (parameter-show-in-menu? "page-screen-margin")
               (not (member->theme "page-screen-margin")))
       "native parameter visibility baseline preserves theme membership policy")
(check (not (parameter-show-in-menu? "language"))
       "Scheme parameter visibility specialization remains authoritative")

(define variant-tree (stree->tree '(section "Title")))
(check (equal? (focus-variants-of variant-tree)
               (variants-of (tree-label variant-tree)))
       "native focus variant baseline preserves variants-of policy")
(check (equal? (focus-tag-name 'section)
               (string-replace
                 (upcase-first (tree-name (tree 'section))) "-" " "))
       "native focus tag naming preserves generic display policy")

(tm-define (focus-variants-of t)
  (:require (tree-is? t 'native-variant-extension))
  '(native-one native-two))
(check (equal? (focus-variants-of
                 (stree->tree '(native-variant-extension "x")))
               '(native-one native-two))
       "native focus variant baseline remains a Scheme extension point")

(tm-define (member->theme name)
  (:require (== name "native-theme-special"))
  "native-theme")
(tm-define (focus-tag-name label)
  (:require (== label 'special))
  "Specialized tag")
(check (equal? (focus-tag-name 'native-theme-special) "Specialized tag")
       "native focus tag recursion redispatches through Scheme specialization")

(define proposal-tree (stree->tree '(native-proposal-extension "x")))
(check (not (child-proposals proposal-tree 0))
       "native child proposal baseline returns false")
(tm-define (child-proposals t i)
  (:require (tree-is? t 'native-proposal-extension))
  '("fast" "slow" :other))
(check (equal? (child-proposals proposal-tree 0) '("fast" "slow" :other))
       "native child proposal baseline remains a Scheme extension point")

(define (legacy-focus-parameters-list t mode)
  (let* ((ls (list-filter (search-parameters (tree-label t))
                          parameter-show-in-menu?))
         (xs (if (== mode :global) (list)
                 (map car (customizable-parameters-memo t))))
         (no (if (== mode :global) inhibit-global-table
                 inhibit-local-table)))
    (list-filter (list-difference ls xs)
                 (lambda (x) (not (ahash-ref no x))))))
(define parameter-tree (stree->tree '(section "Title")))
(check (equal? (focus-parameters-list parameter-tree :global)
               (legacy-focus-parameters-list parameter-tree :global))
       "native global focus parameter list matches legacy filtering")
(define local-mode (list :local (tree-label parameter-tree)))
(check (equal? (focus-parameters-list parameter-tree local-mode)
               (legacy-focus-parameters-list parameter-tree local-mode))
       "native local focus parameter list matches legacy filtering")
(check (equal? (focus-parameters-list-memo parameter-tree :global)
               (focus-parameters-list parameter-tree :global))
       "native focus parameter memoization returns computed value")
(focus-parameters-cache-clear)
(check (equal? (focus-parameters-list-memo parameter-tree :global)
               (focus-parameters-list parameter-tree :global))
       "native cache clearing invalidates focus parameter memoization")

(check (equal? (tree->stree
                  (focus-search-label
                   (stree->tree
                     '(document "x" (concat "a" (label "target"))))))
               '(label "target"))
       "native focus label search walks structural children")
(check (equal? (tree->stree
                 (focus-search-label
                   (stree->tree
                     '(with "mode" "ignored"
                            (document (label "last"))))))
               '(label "last"))
       "native focus label search follows the final with child")
(check (equal? (tree->stree
                 (focus-list-search-label
                   (list (stree->tree '(foo "x"))
                         (stree->tree '(label "listed")))))
               '(label "listed"))
       "native focus label list search returns the first matching label")

;; Later focus-label specializations remain authoritative.  The specialization
;; deliberately uses the native structural search, while get/set dispatch back
;; through the public focus-label command.
(tm-define (focus-label t)
  (:require (tree-is? t 'focus-label-extension))
  (focus-search-label (tree-ref t 0)))
(buffer-set-body
  (current-buffer)
  (stree->tree '(document (focus-label-extension (document (label "old"))))))
(update-current-buffer)
(define focus-extension (tree-ref (buffer-tree) 0))
(check (equal? (focus-get-label focus-extension) "old")
       "native focus-get-label reaches Scheme focus-label specialization")
(focus-set-label focus-extension "new")
(check (equal? (body)
               '(document (focus-label-extension (document (label "new")))))
       "native focus-set-label mutates the specialized active label")

(buffer-set-body
  (current-buffer)
  (stree->tree '(document (hover-balloon "body" "tip" "left" "Bottom"))))
(update-current-buffer)
(tree-go-to (tree-ref (buffer-tree) 0 0) :end)
(check (test-balloon-halign? "left")
       "native balloon horizontal alignment predicate")
(check (test-balloon-valign? "Bottom")
       "native balloon vertical alignment predicate")
(set-balloon-halign "Right")
(set-balloon-valign "top")
(check (equal? (body)
               '(document (hover-balloon "body" "tip" "Right" "top")))
       "native balloon alignment setters mutate the active balloon")
(reset '(document "plain") '(0 0 1))
(check (not (test-balloon-halign? "left"))
       "balloon alignment predicate is false outside balloon context")

(check (mini-flow-context? (stree->tree '(table "x")))
       "native mini-flow predicate recognizes base table tag")
(check (not (mini-flow-context? (stree->tree '(document "x"))))
       "native mini-flow predicate rejects main document tag")
(check (balloon-context? (stree->tree '(hover-balloon "x" "y" "left" "Bottom")))
       "native balloon context recognizes live balloon group")
(check (not (balloon-context? (stree->tree '(document "x"))))
       "native balloon context rejects non-balloon tags")

(check (equal? (cardlink-default-link-body (stree->tree "report.PDF"))
               "PDF document")
       "native cardlink classification is case-insensitive for PDF")
(check (equal? (cardlink-default-link-body
                 (stree->tree "tmfs://wikilink/example/"))
               "TMFS link")
       "native cardlink classification preserves TMFS link naming")
(check (equal? (cardlink-default-link-body (stree->tree "picture.PNG"))
               "Image document")
       "native cardlink classification recognizes image suffixes")

(define detached-link (stree->tree '(hlink "Body" "notes.txt")))
(define detached-card (display-link-as-card detached-link))
(check (equal? (tree->stree detached-link) '(hlink "Body" "notes.txt"))
       "native detached link conversion leaves caller handle unchanged")
(check (equal? (tree->stree detached-card) '(cardlink "Body" "notes.txt"))
       "native detached link conversion returns converted card")
(define detached-link-again (display-card-as-link detached-card))
(check (equal? (tree->stree detached-link-again) '(hlink "Body" "notes.txt"))
       "native detached card conversion returns link with nonempty body")

(buffer-set-body (current-buffer)
                 (stree->tree '(document (hlink "" "report.pdf"))))
(update-current-buffer)
(display-link-as-card (tree-ref (buffer-tree) 0))
(check (equal? (body) '(document (cardlink "" "report.pdf")))
       "native link-to-card conversion preserves active tree mutation")
(display-card-as-link (tree-ref (buffer-tree) 0))
(check (equal? (body) '(document (hlink "PDF document" "report.pdf")))
       "native card-to-link conversion fills default body for empty card")

(define rendered-card
  (cardlink-native-render (stree->tree "") "" "PDF"))
(check (tree-is? rendered-card 'with)
       "native cardlink render-tree builder returns ornament wrapper")
(check (equal? (tree->stree (tree-ref rendered-card 10 0 0 2))
               "PDF Document")
       "native cardlink render-tree builder supplies default display body")

(reset '(document "plain") '(0 0 1))
(check (in-main-flow?) "cursor in ordinary document text is in main flow")
(buffer-set-body
  (current-buffer)
  (stree->tree '(document (table (row (cell "x"))))))
(update-current-buffer)
(tree-go-to (tree-ref (buffer-tree) 0 0 0 0) :end)
(check (not (in-main-flow?))
       "cursor inside table cell is outside main flow")

(define activated-hit? #f)
(define disactivated-hit? #f)
(tm-define (notify-activated t)
  (:require (tree-is? t 'notify-test-extension))
  (set! activated-hit? #t))
(tm-define (notify-disactivated t)
  (:require (tree-is? t 'notify-test-extension))
  (set! disactivated-hit? #t))
(define notify-target (stree->tree '(notify-test-extension "x")))
(notify-activated notify-target)
(notify-disactivated notify-target)
(check activated-hit? "native notify-activated baseline remains overloadable")
(check disactivated-hit? "native notify-disactivated baseline remains overloadable")

(reset '(document "abc") '(0 0 1))
(search-next)
(search-previous)
(focus-open-search-tool (focus-tree))

(reset '(document "ab") '(0 0 1))
(make-specific "html")
(check (equal? (body)
               '(document (concat "a" (inactive (specific "html" "")) "b")))
       "inactive specific insertion")
(check (equal? (cursor-path) '(0 0 1 0 1 0)) "inactive specific cursor")

(reset '(document "ab") '(0 0 1))
(make-specific "texmacs")
(check (equal? (body) '(document (concat "a" (specific "texmacs" "") "b")))
       "TeXmacs specific insertion")
(check (equal? (cursor-path) '(0 0 1 1 0)) "TeXmacs specific cursor")

(reset '(document "ab") '(0 0 1))
(make-include (string->url "other.ath"))
(check (equal? (body) '(document (concat "a" (include "other.ath") "b")))
       "relative include insertion")
(check (equal? (cursor-path) '(0 0 1 1)) "include cursor")

(reset '(document "ab") '(0 0 1))
(make-experimental-build-warning)
(check (equal? (body)
               '(document (concat "a" (experimental-build-warning) "b")))
       "experimental warning insertion")

(reset '(document (note-inline "body" "note-x") "tail") '(0 1 0))
(make-note-ref)
(check (equal? (body)
               '(document (note-inline "body" "note-x")
                          (concat (note-ref "note-x") "tail")))
       "note reference reuses unmatched text id")
(check (equal? (cursor-path) '(0 1 0 1)) "note reference cursor")

(reset '(document (note-ref "note-y") "tail") '(0 1 0))
(make-note-inline)
(check (equal? (body)
               '(document (note-ref "note-y")
                          (concat (note-inline "" "note-y") "tail")))
       "inline note reuses unmatched reference id")
(check (equal? (cursor-path) '(0 1 0 0 0)) "inline note cursor")

(reset '(document (note-ref "note-z") "tail") '(0 1 0))
(make-note-wide)
(check (equal? (body)
               '(document (note-ref "note-z")
                          (note-wide (document "") "note-z") "tail"))
       "wide note reuses unmatched reference id")
(check (equal? (cursor-path) '(0 1 0 0 0)) "wide note cursor")

(reset '(document (note-ref "note-f") "tail") '(0 1 0))
(make-note-footnote)
(check (equal? (body)
               '(document (note-ref "note-f")
                          (concat (note-footnote (document "") "note-f") "tail")))
       "footnote reuses unmatched reference id")
(check (equal? (cursor-path) '(0 1 0 0 0 0)) "footnote cursor")

(tm-define (create-unique-id) "generated-note-id")
(reset '(document "tail") '(0 0 0))
(make-note-ref)
(check (equal? (body) '(document (concat (note-ref "generated-note-id") "tail")))
       "note id fallback uses the public unique-id extension point")

(reset '(document "abc") '(0 0 1))
(make-marginal-note)
(check (equal? (body)
               '(document (concat "a"
                                  (inactive (marginal-note "normal" "c" ""))
                                  "bc")))
       "marginal note insertion")
(check (equal? (cursor-path) '(0 0 1 0 2 0)) "marginal note cursor")
(set-marginal-note-hpos "left")
(set-marginal-note-valign "top")
(check (test-marginal-note-hpos? "left") "marginal horizontal position")
(check (test-marginal-note-valign? "top") "marginal vertical alignment")

(reset '(document "abcd") '(0 0 2))
(selection-set '(0 0 1) '(0 0 3))
(make-marginal-note)
(check (equal? (body)
               '(document (concat "a"
                                  (inactive (marginal-note "normal" "c" "bc"))
                                  "d")))
       "marginal note wraps small selection")
(check (equal? (cursor-path) '(0 0 1 0 2 2)) "wrapped marginal cursor")

(reset '(document "abc") '(0 0 1))
(make-insertion "float")
(check (equal? (body)
               '(document (concat "a" (float "float" "tbh" (document "")) "bc")))
       "float insertion")
(check (equal? (cursor-path) '(0 0 1 2 0 0)) "float insertion cursor")
(check (test-insertion-positioning? "h") "float h positioning initially enabled")
(toggle-insertion-positioning "h")
(check (not (test-insertion-positioning? "h")) "float h positioning disabled")
(check (equal? (tree->stree (tree-ref (buffer-tree) 0 1 1)) "tb")
       "float position string removes h")
(toggle-insertion-positioning "h")
(check (test-insertion-positioning? "h") "float h positioning restored")
(check (equal? (tree->stree (tree-ref (buffer-tree) 0 1 1)) "tbh")
       "float position string restores h")

(init-env "page-medium" "paper")
(update-current-buffer)
(update-forced)
(print-to-file (string->url (string-append (getenv "HOME") "/evaluation.pdf")))
#t
