;; Generic keyboard fallbacks execute on the owning BufferActor.
(import-from (generic generic-edit))
(import-from (generic insert-menu))
(import-from (graphics graphics-kbd))
(init-style "generic")

(define (body) (tree->stree (buffer-tree)))
(define (check condition message)
  (unless condition (error message (body) (cursor-path))))
(define (reset content position)
  (selection-cancel)
  (buffer-set-body (current-buffer) (stree->tree `(document ,content)))
  (update-current-buffer)
  (tree-go-to (tree-ref (buffer-tree) 0) position)
  (commit-changes)
  (clear-undo-history))

(reset "ab" 1)
(kbd-space-bar (buffer-tree) #f)
(check (equal? (body) '(document "a b")) "space insertion")
(check (equal? (cursor-path) '(0 0 2)) "space cursor")

(reset "ab" 1)
(kbd-enter (buffer-tree) #f)
(check (equal? (body) '(document "a" "b")) "return splits paragraph")
(check (equal? (cursor-path) '(0 1 0)) "return cursor")

(reset "ab" 1)
(kbd-remove (buffer-tree) #f)
(check (equal? (body) '(document "b")) "backspace")
(check (equal? (cursor-path) '(0 0 0)) "backspace cursor")

(reset "ab" 1)
(kbd-remove (buffer-tree) #t)
(check (equal? (body) '(document "a")) "delete")
(check (equal? (cursor-path) '(0 0 1)) "delete cursor")

(reset "abcd" 2)
(selection-set (tree->path (tree-ref (buffer-tree) 0) 1)
               (tree->path (tree-ref (buffer-tree) 0) 3))
(kbd-remove (buffer-tree) #f)
(check (equal? (body) '(document "ad")) "selection delete")
(check (equal? (cursor-path) '(0 0 1)) "selection delete cursor")

(define (reset-graphics-selection)
  (selection-cancel)
  (buffer-set-body
    (current-buffer)
    (stree->tree
      '(document
         (with "gr-mode" (tuple "hand-edit" "penscript")
               (graphics ""))
         "tail")))
  (update-current-buffer)
  (with g (tree-ref (tree-ref (buffer-tree) 0) 1)
    (tree-go-to g :start)
    (selection-set (tree->path g :start) (tree->path g :end)))
  (commit-changes)
  (clear-undo-history))

(reset-graphics-selection)
(key-press "delete")
(check (null? (select (buffer-tree) '(graphics)))
       "delete removes selected whole graphics")

(reset-graphics-selection)
(key-press "backspace")
(check (null? (select (buffer-tree) '(graphics)))
       "backspace removes selected whole graphics")

(reset "ab" 1)
(kbd-alternate-variant (buffer-tree) #t)
(check (equal? (body) '(document (concat "a" (htab "5mm") "b")))
       "alternate tab insertion")
(check (equal? (cursor-path) '(0 0 1 1)) "alternate tab cursor")

(reset "abcd" 1)
(kbd-select (lambda () (tree-go-to (tree-ref (buffer-tree) 0) 2)))
(check (selection-active-any?) "native kbd-select activates selection")
(check (equal? (selection-get-start) '(0 0 1)) "native kbd-select start")
(check (equal? (selection-get-end) '(0 0 2)) "native kbd-select end")
(check (equal? (cursor-path) '(0 0 2)) "native kbd-select cursor")

(reset "abcd" 1)
(kbd-plain-move (lambda () (tree-go-to (tree-ref (buffer-tree) 0) 3)))
(check (equal? (cursor-path) '(0 0 3)) "native kbd-plain-move procedure bridge")

(define (legacy-kbd-horizontal t forwards?)
  (if (tree-is-buffer? t)
      (let ((move (lambda () (if forwards? (go-right) (go-left)))))
        (go-to-next-such-that move generic-context?))
      (and-with p (tree-outer t)
        (legacy-kbd-horizontal p forwards?))))
(define (legacy-kbd-extremal t forwards?)
  (if (tree-is-buffer? t)
      (let ((move (lambda () (if forwards? (go-end-line) (go-start-line)))))
        (go-to-next-such-that move generic-context?))
      (and-with p (tree-outer t)
        (legacy-kbd-extremal p forwards?))))

(reset "abcd" 2)
(legacy-kbd-horizontal (focus-tree) #f)
(define legacy-left-path (cursor-path))
(reset "abcd" 2)
(kbd-left)
(check (equal? (cursor-path) legacy-left-path)
       "native generic left matches legacy movement")

(reset "abcd" 2)
(legacy-kbd-extremal (focus-tree) #f)
(define legacy-start-path (cursor-path))
(reset "abcd" 2)
(kbd-start-line)
(check (equal? (cursor-path) legacy-start-path)
       "native generic start-line matches legacy movement")

(reset "ab" 1)
(kbd-space)
(check (equal? (body) '(document "a b")) "native no-argument space dispatch")
(check (equal? (cursor-path) '(0 0 2)) "native no-argument space cursor")

;; Public no-argument commands must remain tm-define extension points after
;; their generic baseline moves into native glue.
(tm-define (kbd-return)
  (:require (tree-is? (focus-tree) 'keyboard-return-extension))
  (tree-set! (focus-tree) 0 "extended"))
(buffer-set-body (current-buffer)
                 (stree->tree '(document (keyboard-return-extension "x"))))
(update-current-buffer)
(tree-go-to (tree-ref (buffer-tree) 0 0) :end)
(kbd-return)
(check (equal? (body) '(document (keyboard-return-extension "extended")))
       "native no-argument command remains a Scheme extension point")

;; Raw native movement must continue to dispatch through later Scheme
;; specializations instead of bypassing mode-specific behavior.
(tm-define (kbd-horizontal t forwards?)
  (:require (tree-is? t 'keyboard-move-extension))
  (tree-set! t 0 (if forwards? "right" "left")))
(buffer-set-body (current-buffer)
                 (stree->tree '(document (keyboard-move-extension "x"))))
(update-current-buffer)
(tree-go-to (tree-ref (buffer-tree) 0 0) :end)
(kbd-right)
(check (equal? (body) '(document (keyboard-move-extension "right")))
       "native no-argument movement reaches Scheme extension")
(kbd-left)
(check (equal? (body) '(document (keyboard-move-extension "left")))
       "native left movement reaches Scheme extension")

;; Native outward fallback must continue to compose with later mode handlers.
(tm-define (kbd-enter t shift?)
  (:require (tree-is? t 'keyboard-test-extension))
  (tree-set! t 0 (if shift? "shift" "enter")))
(buffer-set-body (current-buffer)
                 (stree->tree '(document (keyboard-test-extension "x"))))
(update-current-buffer)
(tree-go-to (tree-ref (buffer-tree) 0 0) :end)
(kbd-enter (tree-ref (buffer-tree) 0 0) #f)
(check (equal? (body) '(document (keyboard-test-extension "enter")))
       "keyboard outward dispatch reaches Scheme extension")

(define (reset-hybrid command)
  (selection-cancel)
  (buffer-set-body (current-buffer)
                   (stree->tree `(document (inactive (hybrid ,command)))))
  (update-current-buffer)
  (tree-go-to (tree-ref (buffer-tree) 0 0 0) :end)
  (commit-changes)
  (clear-undo-history))

(reset-hybrid "")
(hybrid-kbd-curly-left)
(check (equal? (body) '(document (eqnarray ""))) "empty hybrid curly-left")
(check (equal? (cursor-path) '(0 0 0 0)) "eqnarray activation cursor")

(reset-hybrid "begin{strong")
(hybrid-kbd-curly-right)
(check (equal? (body) '(document (strong ""))) "begin command curly-right")
(check (equal? (cursor-path) '(0 0 0 0)) "begin activation cursor")

(reset-hybrid "left")
(hybrid-kbd-backslash)
(check (equal? (body) '(document (inactive (hybrid "left\\"))))
       "left command accepts backslash continuation")
(check (equal? (cursor-path) '(0 0 0 0 5)) "backslash continuation cursor")

(reset-hybrid "strong")
(hybrid-kbd-space)
(check (equal? (body) '(document (strong " "))) "space activates hybrid first")
(check (equal? (cursor-path) '(0 0 0 1)) "hybrid space cursor")

(reset-hybrid "strong")
(hybrid-kbd-sub)
(check (equal? (body) '(document (strong (rsub "")))) "hybrid subscript")
(check (equal? (cursor-path) '(0 0 0 0 0)) "hybrid subscript cursor")

(reset-hybrid "strong")
(hybrid-kbd-sup)
(check (equal? (body) '(document (strong (rsup "")))) "hybrid superscript")
(check (equal? (cursor-path) '(0 0 0 0 0)) "hybrid superscript cursor")

(reset-hybrid "")
(hybrid-kbd-formula-open "frac")
(check (equal? (body) '(document (frac "" ""))) "empty hybrid formula command")
(check (equal? (cursor-path) '(0 0 0 0)) "formula activation cursor")

(reset "" 0)
(escape-symbol-insert "tree:dx")
(check (equal? (body)
               '(document (frac "<mathd>" "<mathd>x")))
       "native escape symbol inserts derivative tree")

(reset "" 0)
(escape-symbol-insert "tree:math-up:sin")
(check (equal? (body) '(document (math-up "sin")))
       "native escape symbol inserts dynamic math-up tree")

(reset "" 0)
(escape-symbol-insert "tree:operator:lim")
(check (equal? (body) '(document "lim"))
       "native escape symbol inserts dynamic operator text")

(reset "" 0)
(make 'math-ss)
(define legacy-math-ss (body))
(reset "" 0)
(escape-symbol-insert "tree:math-ss")
(check (equal? (body) legacy-math-ss)
       "JSON call descriptor matches public make command")

(let ((binding (kbd-find-key-binding "C-S-p")))
  (check (equal? (key-press-command "C-S-p") (and binding (car binding)))
         "native key-press-command mirrors public keyboard binding lookup"))
(check (not (key-press-command "definitely-not-a-real-athena-key-binding"))
       "native key-press-command returns false for missing binding")

(check (equal? (handwriting-symbol-input-description "\\---") "--")
       "native handwriting description preserves direct-text mapping")
(reset "" 0)
(handwriting-symbol-insert "\\---")
(check (equal? (body) '(document "--"))
       "native handwriting insertion handles direct text")

(check (equal? (handwriting-symbol-input-description "\\lhd") "\\lhd  Enter")
       "native handwriting description reaches keyboard command table")
(reset "" 0)
(handwriting-symbol-insert "\\lhd")
(check (equal? (body) '(document "<vartriangleleft>"))
       "native handwriting insertion executes keyboard command procedure")

(init-env "page-medium" "paper")
(update-current-buffer)
(update-forced)
(print-to-file (string->url (string-append (getenv "HOME") "/evaluation.pdf")))
#t
