;; Generic editor commands execute on the owning BufferActor.
(import-from (generic generic-edit))
(init-style "generic")

(define (body) (tree->stree (buffer-tree)))
(define (check condition message)
  (unless condition
    (error message (body) (cursor-path)
           (if (selection-active-any?)
               (list (selection-get-start) (selection-get-end)) '()))))
(define (reset content cursor)
  (selection-cancel)
  (buffer-set-body (current-buffer) (stree->tree content))
  (update-current-buffer)
  (go-to cursor)
  (commit-changes)
  (clear-undo-history))
(reset '(document "abc" "def") '(0 0 1))
(select-all)
(check (selection-active-any?) "select-all activates selection")
(check (equal? (selection-get-start) '(0 0)) "select-all start")
(check (equal? (selection-get-end) '(0 1)) "select-all end")

(reset '(document "aa" "bb" "cc") '(0 0 1))
(go-to-line 2)
(check (equal? (cursor-path) '(0 2 0)) "go-to-line")

(reset '(document "abcdef") '(0 0 1))
(go-to-column 4)
(check (equal? (cursor-path) '(0 0 4)) "go-to-column")

(reset '(document "zero alpha beta alpha") '(0 0 12))
(let ((result (select-word "alpha" (tree-ref (buffer-tree) 0) 18)))
  (check (= result 16) "select-word result"))
(check (equal? (selection-get-start) '(0 0 16)) "select-word start")
(check (equal? (selection-get-end) '(0 0 21)) "select-word end")

(reset '(document "no match") '(0 0 2))
(check (not (select-word "alpha" (tree-ref (buffer-tree) 0) 2))
       "select-word missing result")
(check (not (selection-active-any?)) "missing word leaves selection inactive")

(check (equal? (search-parameters "reference")
               '("locus-color" "visited-color"))
       "reference search parameters")
(check (null? (search-parameters "not-a-reference"))
       "unknown search parameters remain empty after macro discovery")

(reset '(document "abc") '(0 0 1))
(label-insert (buffer-tree))
(check (equal? (body) '(document (concat "a" (inactive (label "")) "bc")))
       "generic label insertion")
(check (equal? (cursor-path) '(0 0 1 0 0 0)) "label insertion cursor")

;; Later Scheme specializations still intercept the native baseline.
(tm-define (label-insert t)
  (:require (tree-is? t 'label-test-extension))
  (tree-set! t 0 "handled"))
(buffer-set-body (current-buffer)
                 (stree->tree '(document (label-test-extension "x"))))
(update-current-buffer)
(tree-go-to (tree-ref (buffer-tree) 0 0) :end)
(label-insert (tree-ref (buffer-tree) 0 0))
(check (equal? (body) '(document (label-test-extension "handled")))
       "label outward dispatch reaches Scheme extension")
(tree-set! (tree-ref (buffer-tree) 0) 0 "x")
(tree-go-to (tree-ref (buffer-tree) 0 0) :end)
(make-label)
(check (equal? (body) '(document (label-test-extension "handled")))
       "no-argument make-label reaches Scheme label specialization")

(reset '(document "abc") '(0 0 1))
(recenter-window)

(reset '(document "ab") '(0 0 1))
(make-specific "html")
(check (equal? (body)
               '(document (concat "a" (inactive (specific "html" "")) "b")))
       "inactive specific insertion")
(check (equal? (cursor-path) '(0 0 1 0 1 0)) "inactive specific cursor")

(reset '(document "ab") '(0 0 1))
(make-specific "texmacs")
(check (equal? (body) '(document (concat "a" (specific "texmacs" "") "b")))
       "TeXmacs specific insertion")
(check (equal? (cursor-path) '(0 0 1 1 0)) "TeXmacs specific cursor")

(reset '(document "ab") '(0 0 1))
(make-include (string->url "other.ath"))
(check (equal? (body) '(document (concat "a" (include "other.ath") "b")))
       "relative include insertion")
(check (equal? (cursor-path) '(0 0 1 1)) "include cursor")

(reset '(document "ab") '(0 0 1))
(make-experimental-build-warning)
(check (equal? (body)
               '(document (concat "a" (experimental-build-warning) "b")))
       "experimental warning insertion")

(reset '(document (note-inline "body" "note-x") "tail") '(0 1 0))
(make-note-ref)
(check (equal? (body)
               '(document (note-inline "body" "note-x")
                          (concat (note-ref "note-x") "tail")))
       "note reference reuses unmatched text id")
(check (equal? (cursor-path) '(0 1 0 1)) "note reference cursor")

(reset '(document (note-ref "note-y") "tail") '(0 1 0))
(make-note-inline)
(check (equal? (body)
               '(document (note-ref "note-y")
                          (concat (note-inline "" "note-y") "tail")))
       "inline note reuses unmatched reference id")
(check (equal? (cursor-path) '(0 1 0 0 0)) "inline note cursor")

(reset '(document (note-ref "note-z") "tail") '(0 1 0))
(make-note-wide)
(check (equal? (body)
               '(document (note-ref "note-z")
                          (note-wide (document "") "note-z") "tail"))
       "wide note reuses unmatched reference id")
(check (equal? (cursor-path) '(0 1 0 0 0)) "wide note cursor")

(reset '(document (note-ref "note-f") "tail") '(0 1 0))
(make-note-footnote)
(check (equal? (body)
               '(document (note-ref "note-f")
                          (concat (note-footnote (document "") "note-f") "tail")))
       "footnote reuses unmatched reference id")
(check (equal? (cursor-path) '(0 1 0 0 0 0)) "footnote cursor")

(tm-define (create-unique-id) "generated-note-id")
(reset '(document "tail") '(0 0 0))
(make-note-ref)
(check (equal? (body) '(document (concat (note-ref "generated-note-id") "tail")))
       "note id fallback uses the public unique-id extension point")

(reset '(document "abc") '(0 0 1))
(make-marginal-note)
(check (equal? (body)
               '(document (concat "a"
                                  (inactive (marginal-note "normal" "c" ""))
                                  "bc")))
       "marginal note insertion")
(check (equal? (cursor-path) '(0 0 1 0 2 0)) "marginal note cursor")
(set-marginal-note-hpos "left")
(set-marginal-note-valign "top")
(check (test-marginal-note-hpos? "left") "marginal horizontal position")
(check (test-marginal-note-valign? "top") "marginal vertical alignment")

(reset '(document "abcd") '(0 0 2))
(selection-set '(0 0 1) '(0 0 3))
(make-marginal-note)
(check (equal? (body)
               '(document (concat "a"
                                  (inactive (marginal-note "normal" "c" "bc"))
                                  "d")))
       "marginal note wraps small selection")
(check (equal? (cursor-path) '(0 0 1 0 2 2)) "wrapped marginal cursor")

(reset '(document "abc") '(0 0 1))
(make-insertion "float")
(check (equal? (body)
               '(document (concat "a" (float "float" "tbh" (document "")) "bc")))
       "float insertion")
(check (equal? (cursor-path) '(0 0 1 2 0 0)) "float insertion cursor")
(check (test-insertion-positioning? "h") "float h positioning initially enabled")
(toggle-insertion-positioning "h")
(check (not (test-insertion-positioning? "h")) "float h positioning disabled")
(check (equal? (tree->stree (tree-ref (buffer-tree) 0 1 1)) "tb")
       "float position string removes h")
(toggle-insertion-positioning "h")
(check (test-insertion-positioning? "h") "float h positioning restored")
(check (equal? (tree->stree (tree-ref (buffer-tree) 0 1 1)) "tbh")
       "float position string restores h")

(init-env "page-medium" "paper")
(update-current-buffer)
(update-forced)
(print-to-file (string->url (string-append (getenv "HOME") "/evaluation.pdf")))
#t
