;; Exercise native geometry commands on an actual editor owned by its actor.
(init-style "generic")
(define (check condition message)
  (unless condition (error message (body))))
(define (body) (tree->stree (buffer-tree)))
(define (node) (tree-ref (buffer-tree) 0))
(define (reset content)
  (buffer-set-body (current-buffer) (stree->tree `(document ,content)))
  (update-current-buffer)
  (tree-go-to (node) :end)
  (commit-changes)
  (clear-undo-history))

(reset '(space "1cm"))
(geometry-horizontal (node) #t)
(check (equal? (body) '(document (space "1.1cm"))) "rigid space width")
(geometry-vertical (node) #f)
(check (equal? (body) '(document (space "1.1cm" "0ex" "1.1ex")))
       "space ternary expansion")
(geometry-incremental (node) #t)
(check (equal? (body) '(document (space "1.1cm" "-0.1ex" "1ex")))
       "space vertical translation")
(check (equal? (get-manual-focus-path) (tree->path (node))) "focus retained")

(reset '(hspace "1cm" "2cm" "3cm"))
(geometry-horizontal (node) #f)
(check (equal? (body) '(document (hspace "0.9cm" "1.9cm" "2.9cm")))
       "rubber space lengths move together")
(reset '(hspace "1cm" "2pt" "3cm"))
(geometry-horizontal (node) #t)
(check (equal? (body) '(document (hspace "1cm" "2pt" "3cm")))
       "inconsistent rubber space unchanged")
(reset '(vspace "1cm"))
(geometry-vertical (node) #t)
(check (equal? (body) '(document (vspace "1.1cm"))) "vertical space direction")

(set-preference "default unit" "cm")
(reset '(move "text" "" ""))
(geometry-horizontal (tree-ref (node) 0) #t)
(geometry-vertical (node) #t)
(check (equal? (body) '(document (move "text" "0.1cm" "-0.1cm")))
       "move defaults and ancestor dispatch")
(tree-focus (node))
(geometry-left)
(check (equal? (tree->stree (tree-ref (node) 1)) "0cm") "focused command")

(reset '(resize "text" "" "" "" ""))
(geometry-extremal (node) #t)
(geometry-incremental (node) #f)
(check (equal? (body)
               '(document (resize "text" (plus "1l" "0.1cm")
                                   (plus "1b" "0.1cm") (plus "1r" "0.1cm")
                                   (plus "1t" "0.1cm"))))
       "resize initializes and translates both bounds")

(reset '(reduce-by "text" "1cm"))
(geometry-vertical (node) #f)
(check (equal? (body) '(document (reduce-by "text" "0.9cm"))) "vertical adjustment")

(reset '(hspace "1cm"))
(pinch-start)
(geometry-scale (node) 4.0)
(check (equal? (body) '(document (hspace "2cm"))) "gesture scaling")
;; Each real mouse event commits its frame before the next scale callback.
(commit-changes)
(geometry-scale (node) 9.0)
(check (equal? (body) '(document (hspace "3cm"))) "gesture replaces previous frame")
(commit-changes)
(pinch-clear)
(geometry-scale (node) 4.0)
(check (equal? (body) '(document (hspace "6cm"))) "new gesture starts from current size")
(pinch-clear)

;; A Scheme domain extension must still receive dispatch from a native parent walk.
(tm-define (geometry-horizontal t forward?)
  (:require (tree-is? t 'geometry-test-extension))
  (tree-set! t 0 (if forward? "right" "left")))
(reset '(geometry-test-extension "text"))
(geometry-horizontal (tree-ref (node) 0) #t)
(check (equal? (body) '(document (geometry-test-extension "right")))
       "domain extension retained")

(reset "picked")
(let ((text (node)))
  (selection-set (tree->path text 0) (tree->path text 6)))
(check (selection-active-small?) "test selection is inline")
(make-move "1cm" "2cm")
(check (equal? (body) '(document (move "picked" "1cm" "2cm")))
       "native wrapper preserves selection")

(reset "")
(make-clipped "1l" "1b" "1r" "1t")
(check (equal? (body) '(document (clipped "" "1l" "1b" "1r" "1t")))
       "native clipped insertion")

(init-env "page-medium" "paper")
(update-current-buffer)
(update-forced)
(print-to-file (string->url (string-append (getenv "HOME") "/evaluation.pdf")))
