;; Exercise production navigation definitions with asynchronous owner queues.
(use-modules (srfi srfi-1))
(define root (cadr (command-line)))
(define owner 'source)
(define pending '())
(define opened '())
(define history '())
(define labels '())
(define positions '())
(define failed-message #f)
(define resolve-ok? #t)
(define (check ok message) (unless ok (error message)))
(define (!= a b) (not (equal? a b)))
(define == equal?)
(define (nnull? x) (pair? x))
(define-syntax with
  (syntax-rules ()
    ((_ (a b) value body ...) (apply (lambda (a b) body ...) value))))
(define (load-definition file name)
  (call-with-input-file (string-append root "/ATHENA/progs/" file)
    (lambda (port)
      (let loop ((form (read port)))
        (check (not (eof-object? form)) (string-append "Missing " (symbol->string name)))
        (if (and (pair? form) (memq (car form) '(define tm-define))
                 (pair? (cadr form)) (eq? (caadr form) name))
            (eval (cons 'define
                        (cons (cadr form)
                              (filter (lambda (x)
                                        (not (and (pair? x)
                                                  (memq (car x) '(:synopsis :argument :require)))))
                                      (cddr form))))
                  (current-module))
            (loop (read port)))))))
(define files "athena/athena/tm-files.scm")
(define vault "athena/athena/tm-vault.scm")
(for-each (lambda (name) (load-definition files name))
          '(load-browse-buffer load-browse-buffer-main linked-file-opened
            linked-file-load-native))
(for-each (lambda (name) (load-definition vault name))
          '(vault-jump-to-source artifact-jump-to-position))

(define (enqueue destination thunk)
  (set! pending (append pending (list (cons destination thunk)))))
(define (exec-global thunk)
  (if (eq? owner 'global) (thunk) (enqueue 'global thunk)))
(define (exec-buffer name thunk)
  (check (eq? owner 'global) "exec-buffer used outside global owner")
  (enqueue (url->system name) thunk))
(define (drain)
  (unless (null? pending)
    (let ((job (car pending)))
      (set! pending (cdr pending))
      (set! owner (car job))
      ((cdr job))
      (drain))))
;; URLs deliberately reject use by another owner. Navigation must carry text.
(define (system->url text) (vector owner text))
(define (url->system u)
  (check (eqv? (vector-ref u 0) owner) "native URL crossed owner boundary")
  (vector-ref u 1))
(define (current-buffer) (system->url "/source.ath"))
(define (url-rooted? u)
  (or (string-prefix? "/" (url->system u))
      (string-prefix? "tmfs://" (url->system u))))
(define (url-relative base u) (system->url (string-append "/" (url->system u))))
(define (url-rooted-protocol? u protocol) #f)
(define (url-rooted-web? u) #f)
(define (url-rooted-tmfs? u) #t)
(define (buffer-exists? name)
  (check (eq? owner 'global) "buffer registry read by source actor")
  (member (url->system name) opened))
(define (switch-to-buffer name)
  (check (eq? owner 'global) "buffer switch outside global owner")
  (check (member (url->system name) opened) "switched to missing buffer"))
(define (load-buffer name)
  (check (eq? owner 'global) "load outside global owner")
  (set! opened (cons (url->system name) opened)))
(define (cursor-history-add p)
  (check (not (eq? owner 'global)) "cursor history outside buffer actor")
  (set! history (append history (list (cons owner p)))))
(define (cursor-path) '(0 2))
(define (go-to-label label)
  (check (equal? owner "/target.ath") "label jump used the source actor")
  (set! labels (cons label labels)))
(define (artifact-position-in-buffer p)
  (check (equal? owner "/target.ath") "artifact jump used the source actor")
  (set! positions (cons p positions)))
(define (artifact-url-uuid u) (url->system u))
(define (artifact-resolve-uuid uuid)
  (check (eq? owner 'global) "artifact resolver used the source actor")
  (and resolve-ok? (list (system->url "/target.ath") '(0 3))))
(define (set-message text title) (set! failed-message text))

;; Radioactive artifact: resolve globally, then jump and record on target actor.
(load-definition vault 'go-to-url)
(go-to-url (system->url "uuid") '(0 1))
(check (null? opened) "global command executed synchronously on source")
(drain)
(check (equal? positions '((0 3))) "artifact position lost")
(check (equal? (map car history) '(source "/target.ath")) "history owners wrong")
(set! owner 'source)
(set! resolve-ok? #f)
(go-to-url (system->url "missing"))
(drain)
(check (string? failed-message) "failed resolution was not reported")
(check (= (length positions) 1) "failed resolution moved cursor")

;; Transclusion: reuse open target and never schedule label work on source.
(set! owner 'source)
(vault-jump-to-source (system->url "/target.ath") "end-label")
(drain)
(check (equal? labels '("end-label")) "transclusion did not locate label")
(set! owner 'source)
(vault-jump-to-source (system->url "/target.ath") "")
(drain)
(check (= (length labels) 1) "empty anchor unexpectedly moved cursor")

;; Generic URL path used by wikilinks: source history, global load, target post.
(load-definition "link/link-navigate.scm" 'go-to-url)
(define wiki? #t)
(define (wikilink-url? u) wiki?)
(define (url-handlers u)
  (list load-browse-buffer
        (lambda (target)
          (check (equal? (url->system target) "target.ath") "post URL changed")
          (go-to-label "wiki-label"))))
(set! owner 'source)
(set! opened '())
(set! history '())
(go-to-url "target.ath" '(0 1))
(drain)
(check (equal? labels '("wiki-label" "end-label")) "wikilink post lost")
(check (equal? (map car history) '(source)) "wikilink recorded redirect history")
;; Other links still record the destination, and post does not share native URL.
(set! owner 'source)
(set! wiki? #f)
(set! history '())
(go-to-url "target.ath" '(0 1))
(drain)
(check (equal? (map car history) '(source "/target.ath")) "target history missing")

;; The TMFS wikilink loader must defer its redirect until import has returned,
;; then leave whichever actor the delayed-command queue selected.
(load-definition vault 'wikilink-handler-sub)
(define (display* . args) #t)
(define (string-tokenize-by-char text separator) (string-split text separator))
(define (vault-url-component-decode text) text)
(define (vault-get-node uuid) '(tuple "target.ath" "begin" "end"))
(define tree? pair?)
(define tree-label car)
(define (tree-ref t i) (list-ref (cdr t) i))
(define (tree->string t) t)
(define unix->url system->url)
(define (vault-get-root) (system->url "/"))
(define (url-append base leaf)
  (system->url (string-append (url->system base) (url->system leaf))))
(define (url-exists? u) #t)
(define (texmacs-compat-version) "2.1.4")
(define (exec-delayed thunk) (enqueue 'source thunk))
(set! owner 'global)
(set! labels '())
(let ((document (wikilink-handler-sub "uuid")))
  (check (eq? (car document) 'document) "TMFS loader did not return document")
  (check (null? labels) "redirect ran inside TMFS import"))
(drain)
(check (equal? labels '("end")) "deferred wikilink redirect lost destination")

;; Selection is read and serialized on its actor; only the URL crosses to GUI.
(load-definition vault 'resolve-selection-as-artifact-name)
(define selection? #t)
(define (selection-active-any?) selection?)
(define (selection-tree)
  (check (eq? owner 'source) "selection read outside its actor")
  (vector owner "groups"))
(define (artifact-name-query-url selected)
  (check (eq? owner (vector-ref selected 0)) "selection tree crossed owner boundary")
  "tmfs://artifact-name-query/67726f757073")
(set! owner 'source)
(set! opened '())
(set! history '())
(resolve-selection-as-artifact-name)
(check (null? opened) "selection action opened a buffer on its actor")
(drain)
(check (equal? opened '("tmfs://artifact-name-query/67726f757073"))
       "selection query was not opened")
(check (equal? (map car history) '(source)) "selection source history lost")
(set! owner 'source)
(set! selection? #f)
(resolve-selection-as-artifact-name)
(check (null? pending) "empty selection scheduled navigation")
(display "PASS: artifact, transclusion and wikilink navigation owner boundaries\n")
