;; Validate the shipped declarative keymap, using Scheme's reader rather than
;; text matching so mode scopes and key sequence boundaries remain significant.
(use-modules (srfi srfi-1))
(define root (cadr (command-line)))
(define (forms name)
  (call-with-input-file (string-append root "/ATHENA/progs/" name)
    (lambda (port)
      (let loop ((result '()))
        (let ((form (read port)))
          (if (eof-object? form) (reverse result)
              (loop (cons form result))))))))
(define (check expected actual label)
  (unless (equal? expected actual) (error label expected actual)))
(define math-maps
  (filter (lambda (form)
            (and (pair? form) (eq? (car form) 'kbd-map)
                 (member '(:mode in-math?) (cdr form))))
          (forms "math/math-kbd.scm")))
(define (binding key)
  (append-map (lambda (form)
                (filter (lambda (entry)
                          (and (pair? entry) (equal? (car entry) key)))
                        (cdr form)))
              math-maps))
(check '(("- var" "<setminus>")) (binding "- var") "minus variant")
(check '(("- >" "<rightarrow>")) (binding "- >") "right arrow unchanged")
(check '(("- -" "<longminus>")) (binding "- -") "long minus unchanged")
(check '(("math:right | var" (math-evaluation-bar)))
       (binding "math:right | var") "evaluation bar variant")
(check '(("|" (math-bracket-open "|" "|" (quote default))))
       (binding "|") "absolute value unchanged")
(check '(("math:right |" (math-bracket-close "|" "|" #t)))
       (binding "math:right |") "closing bar unchanged")
(check #t
  (and (member '(set-variant-keys "tab" "S-tab")
               (forms "athena/keyboard/prefix-kbd.scm")) #t)
  "Tab is the variant key")
(check #f
  (any (lambda (form)
         (and (pair? form) (eq? (car form) 'kbd-map)
              (member '("- var" "<setminus>") (cdr form))))
       (forms "generic/generic-kbd.scm"))
  "no text-mode override")
(display "PASS: math minus variant and existing arrow bindings\n")
