;; Validate the shipped declarative keymap, using Scheme's reader rather than
;; text matching so mode scopes and key sequence boundaries remain significant.
(use-modules (srfi srfi-1))
(define root (cadr (command-line)))
(define (forms name)
  (call-with-input-file (string-append root "/ATHENA/progs/" name)
    (lambda (port)
      (let loop ((result '()))
        (let ((form (read port)))
          (if (eof-object? form) (reverse result)
              (loop (cons form result))))))))
(define (check expected actual label)
  (unless (equal? expected actual) (error label expected actual)))
(define math-maps
  (filter (lambda (form)
            (and (pair? form) (eq? (car form) 'kbd-map)
                 (member '(:mode in-math?) (cdr form))))
          (forms "math/math-kbd.scm")))
(define (binding key)
  (append-map (lambda (form)
                (filter (lambda (entry)
                          (and (pair? entry) (equal? (car entry) key)))
                        (cdr form)))
              math-maps))
(check '(("- var" "<setminus>")) (binding "- var") "minus variant")
(check '(("- >" "<rightarrow>")) (binding "- >") "right arrow unchanged")
(check '(("- -" "<longminus>")) (binding "- -") "long minus unchanged")
(check '(("math:right | var" (math-evaluation-bar)))
       (binding "math:right | var") "evaluation bar variant")
(check '(("|" (math-bracket-open "|" "|" (quote default))))
       (binding "|") "absolute value unchanged")
(check '(("| var" "|")) (binding "| var") "literal bar remains available")
(check '(("| var var" (math-evaluation-bar)))
       (binding "| var var") "evaluation bar in ordinary Tab cycle")
(check '(("| var var var" (math-separator "|" (quote default))))
       (binding "| var var var") "middle separator remains available")
(check '(("math:right |" (math-bracket-close "|" "|" #t)))
       (binding "math:right |") "closing bar unchanged")
(check #t
  (and (member '(set-variant-keys "tab" "S-tab")
               (forms "athena/keyboard/prefix-kbd.scm")) #t)
  "Tab is the variant key")
(check #f
  (any (lambda (form)
         (and (pair? form) (eq? (car form) 'kbd-map)
              (member '("- var" "<setminus>") (cdr form))))
       (forms "generic/generic-kbd.scm"))
  "no text-mode override")
(for-each
  (lambda (entry)
    (check (list entry) (binding (car entry)) "normal subgroup Tab variant"))
  '(("< | var" "<vartriangleleft>")
    ("| > var" "<vartriangleright>")
    ("< | var var" "<blacktriangleleft>")
    ("| > var var" "<blacktriangleright>")
    ("< | var var var" "<trianglelefteq>")
    ("| > var var var" "<trianglerighteq>")
    ("| var > var var" "<trianglerighteq>")))
(define latex-commands
  (append-map cdr
    (filter (lambda (form) (and (pair? form) (eq? (car form) 'kbd-commands)))
            (forms "athena/keyboard/latex-kbd.scm"))))
(for-each
  (lambda (entry)
    (check `(insert ,(cadr entry))
           (caddr (assoc (car entry) latex-commands))
           "normal subgroup command uses canonical symbol"))
  '(("lhd" "<vartriangleleft>") ("rhd" "<vartriangleright>")
    ("unlhd" "<trianglelefteq>") ("unrhd" "<trianglerighteq>")))
(display "PASS: math variants, normal subgroup commands and arrow bindings\n")
