;; Focused source-metadata checks on a BufferActor-owned editor. Use an
;; isolated profile; this test does not save documents or open a vault.
(import-from (generic document-part) (generic generic-edit))
(init-style "generic")

(define (check condition label)
  (unless condition (error "Source metadata edit regression" label)))
(define (annotate node)
  (check (eq? (car (tree-ensure-node-id! node)) 'ok) "assign test identity")
  (check (eq? (car (tree-update-node-properties! node
                    '(("test:marker" (string "preserve"))) '())) 'ok)
         "assign extension property"))
(define (same-header a b)
  (and (equal? (tree-node-id a) (tree-node-id b))
       (equal? (tree-node-properties a) (tree-node-properties b))))
(define (install body)
  (selection-cancel)
  (buffer-set-body (current-buffer) body)
  (update-current-buffer)
  (commit-changes)
  (clear-undo-history))

(define preamble (stree->tree '(document (hide-preamble (document "defs")) "Body")))
(for-each annotate (list preamble (tree-ref preamble 0)
                         (tree-ref preamble 0 0) (tree-ref preamble 1)))
(define saved-preamble (tree-copy preamble))
(install preamble)
(buffer-show-preamble)
(check (same-header (buffer-tree) saved-preamble) "show preserves root header")
(check (same-header (tree-ref (buffer-tree) 0) (tree-ref saved-preamble 0))
       "show preserves preamble header")
(check (== (tree-ref (buffer-tree) 1 0 0) (tree-ref saved-preamble 1))
       "show preserves atomic paragraph")
(commit-changes)
(undo 0)
(check (== (buffer-tree) saved-preamble) "show undo restores exact identities")
(redo 0)
(buffer-hide-preamble)
(check (== (buffer-tree) saved-preamble) "show/hide preserves complete source")

;; Even optional metadata explicitly attached to a temporary grouping node
;; must not disappear when switching back to the visible body.
(buffer-show-preamble)
(annotate (tree-ref (buffer-tree) 1))
(annotate (tree-ref (buffer-tree) 1 0))
(define ignored (tree-copy (tree-ref (buffer-tree) 1)))
(buffer-hide-preamble)
(check (tree-func? (tree-ref (buffer-tree) 1) 'document 1) "annotated group becomes visible")
(check (same-header (tree-ref (buffer-tree) 1) ignored) "group identity is retained")
(check (== (tree-ref (buffer-tree) 1 0) (tree-ref ignored 0)) "nested group remains intact")

(define plain (stree->tree '(document "Plain")))
(for-each annotate (list plain (tree-ref plain 0)))
(define saved-plain (tree-copy plain))
(install plain)
(buffer-make-preamble)
(check (same-header (buffer-tree) saved-plain) "create preserves body root")
(check (== (tree-ref (buffer-tree) 1 0 0) (tree-ref saved-plain 0))
       "create preserves existing paragraph")

(define nested (stree->tree '(document (with "color" "red" (with "font-series" "bold" "Text")))))
(annotate (tree-ref nested 0 2))
(define saved-nested (tree-copy nested))
(install nested)
(with-merge (tree-ref (buffer-tree) 0 2))
(check (== (buffer-tree) saved-nested) "merge preserves independently identified wrapper")
(tree-with-reset (tree-ref (buffer-tree) 0 2 2) "font-series")
(check (tree-func? (tree-ref (buffer-tree) 0 2) 'with 1) "empty annotated wrapper remains")
(check (same-header (tree-ref (buffer-tree) 0 2) (tree-ref saved-nested 0 2))
       "reset retains wrapper metadata")

(define properties-only (stree->tree '(document (with "color" "red" (with "font-series" "bold" "Text")))))
(check (eq? (car (tree-update-node-properties! (tree-ref properties-only 0 2)
                  '(("test:marker" (string "no uuid required"))) '())) 'ok)
       "property-only source object")
(define saved-properties (tree-copy properties-only))
(install properties-only)
(with-merge (tree-ref (buffer-tree) 0 2))
(check (== (buffer-tree) saved-properties) "merge preserves properties without a UUID")


;; Anonymous wrappers retain the established compact representation.  The
;; retired migration harness also mixed manual UUIDs into this anonymous
;; buffer without activating the source model; that state is no longer a
;; supported editor contract and is intentionally not reconstructed here.
(install (stree->tree '(document (with "color" "red" (with "font-series" "bold" "Text")))))
(with-merge (tree-ref (buffer-tree) 0 2))
(check (equal? (tree->stree (buffer-tree))
               '(document (with "color" "red" "font-series" "bold" "Text")))
       "anonymous merge still works")
(display "ATHENA-NODE-SOURCE-EDIT-PASS\n")
