;; DataArt must preserve source metadata in cover edits and detached exports.
;; Run under an isolated headless ATHENA profile; no vault or renderer is used.
(import-from (athena athena tm-data-art))

(define (check condition label)
  (unless condition (error "DataArt node identity regression" label)))

(define (annotate node)
  (check (eq? (car (tree-ensure-node-id! node)) 'ok) "assign source identity")
  (check (eq? (car (tree-update-node-properties! node
                    `(("test:rich" (rich-text ,(stree->tree '(strong "Kept"))))
                      ("test:value" (integer 42))) '())) 'ok)
         "set source properties"))

(define body (stree->tree '(document (doc-data (doc-title "Title")) "Paragraph")))
(for-each annotate (cons body (tree-children body)))
(define before (tree-copy body))
(define cover (string->url "/unused/node-model-cover.png"))
(define result (data-art-body-with-cover body cover))
(check (equal? (tree-node-id result) (tree-node-id body)) "body identity")
(check (equal? (tree-node-properties result) (tree-node-properties body)) "body properties")
(check (= (tree-arity result) 3) "one cover inserted")
(check (== (tree-ref result 0) (tree-ref body 0)) "title metadata")
(check (== (tree-ref result 2) (tree-ref body 1)) "atomic paragraph metadata")
(check (equal? (tree-node-id (tree-ref result 1)) "") "generated cover has no source identity")
(check (== (data-art-body-with-cover result cover) result) "cover insertion is idempotent")
(tree-set! result 2 "Changed export copy")
(check (== body before) "cover output is detached from source")

(define insert-doc-data
  (@@ (athena athena tm-data-art) data-art-insert-cover-in-doc-data-tree))
(define inside (insert-doc-data (tree-copy body) cover))
(check (equal? (tree-node-id inside) (tree-node-id body)) "doc-data edit retains body identity")
(check (= (tree-arity inside) 2) "doc-data cover is not a body paragraph")
(check (= (tree-arity (tree-ref inside 0)) 2) "doc-misc inserted")
(check (equal? (tree-node-id (tree-ref inside 0)) (tree-node-id (tree-ref body 0)))
       "doc-data identity retained")
(check (equal? (tree-node-properties (tree-ref inside 0))
               (tree-node-properties (tree-ref body 0))) "doc-data properties retained")
(check (== (insert-doc-data inside cover) inside) "doc-data insertion is idempotent")
(define plain (stree->tree '(document "Plain")))
(annotate plain)
(annotate (tree-ref plain 0))
(define prepended (insert-doc-data (tree-copy plain) cover))
(check (equal? (tree-node-id prepended) (tree-node-id plain)) "fallback retains root identity")
(check (== (tree-ref prepended 1) (tree-ref plain 0)) "fallback preserves paragraph")

(define envelope (tree-rebuild (stree->tree '(document))
  (list (stree->tree '(style (tuple "generic")))
        (tree-rebuild (stree->tree '(body)) (list body)))))
(annotate envelope)
(define snapshot ((@@ (athena athena tm-data-art) data-art-export-snapshot)
                   envelope inside cover))
(check (== (tree-ref snapshot 0) envelope) "complete envelope metadata retained")
(check (== (tree-ref snapshot 1) inside) "prepared body metadata retained")
(tree-set! (tree-ref snapshot 0) 1 0 1 "Changed snapshot")
(check (== body before) "export envelope does not share mutable source children")
(check (== (tree-ref snapshot 1) inside) "export body is independent of envelope")
(check (equal? (tree->string (tree-ref snapshot 2)) (url->system cover)) "cover URL")
(display "ATHENA-NODE-DATA-ART-PASS\n")
