;; One integration block, using a real BufferActor and an isolated profile.
;; Entry is the global owner; no production vault or model activation is used.
(import-from (generic generic-edit))

(define (check condition label)
  (unless condition (error "Node source lifecycle regression" label)))
(define (ok? result) (eq? (car result) 'ok))
(define (annotate node)
  (check (ok? (tree-ensure-node-id! node)) "assign fixture identity")
  (check (ok? (tree-update-node-properties! node
                '(("test:retained" (string "native header"))) '()))
         "assign fixture property")
  node)
(define (annotate-all node)
  (annotate node)
  (unless (tree-atomic? node) (for-each annotate-all (tree-children node)))
  node)
(define (ids node)
  (append (if (equal? (tree-node-id node) "") '() (list (tree-node-id node)))
          (if (tree-atomic? node) '() (apply append (map ids (tree-children node))))))
(define (unique? values)
  (or (null? values) (and (not (member (car values) (cdr values)))
                         (unique? (cdr values)))))
(define (all? predicate values)
  (or (null? values) (and (predicate (car values)) (all? predicate (cdr values)))))
(define (retains-ids? before after)
  (let ((actual (ids after)))
    (and (unique? actual) (all? (lambda (id) (member id actual)) (ids before)))))
(define (same-header? a b)
  (and (tree? a) (tree? b)
       (equal? (tree-node-id a) (tree-node-id b))
       (equal? (tree-node-properties a) (tree-node-properties b))))
(define (header node) (list (tree-node-id node) (tree-node-properties node)))

(define test-root (getenv "ATHENA_NODE_LIFECYCLE_ROOT"))
(define name (string->url (string-append test-root "/source.ath")))
(define source
  (annotate-all
    (stree->tree
      '(document (style (tuple "generic"))
         (body (document "第一段" (concat "Second " (em "paragraph"))))
         (initial (collection (associate "test-setting" "kept")
                              (associate "zoom-factor" "1")))
         (final (collection)) (test-extra "Unknown envelope field")))))
;; Only ordinary immutable Scheme values cross into the callback below. The
;; source tree and rich metadata themselves are transferred as an independent
;; copy through the native buffer API, never shared between owner threads.
(define expected-root (header source))
(define expected-fields
  (map (lambda (field) (cons field (header (tree-ref source field))))
       '(style body initial final test-extra)))
(define expected-collection (header (tree-ref source 'initial 0)))
(define expected-association (header (tree-ref source 'initial 0 0)))
(define expected-key (header (tree-ref source 'initial 0 0 0)))
(define expected-body-ids (ids (tree-ref source 'body 0)))
(buffer-set name (tree-copy source))
(set! source #f)
(switch-to-buffer name)

(define (reset-history)
  (selection-cancel)
  (update-current-buffer)
  (commit-changes)
  (clear-undo-history))

(define (run-lifecycle)
  (init-style "generic")
  (reset-history)
  (define baseline (buffer-get-body name))
  (check (equal? (ids baseline) expected-body-ids) "source transfer preserves all identities")
  (check (not (source-node-identities-active?)) "ordinary buffers remain gated")

  ;; Adopting a legacy body must neither allocate IDs nor mark it changed.
  (buffer-set-body name '(document "Unmigrated"))
  (reset-history)
  (check (not (adopt-source-node-identities)) "reject incomplete baseline")
  (check (not (source-node-identities-active?)) "failed adoption stays disabled")
  (check (equal? (tree-node-id (buffer-tree)) "") "no implicit migration")
  (buffer-set-body name (tree-copy baseline))
  (reset-history)
  (check (== (buffer-tree) baseline) "load preserves complete baseline")
  (check (= (undo-possibilities) 0) "fresh history before adoption")
  (check (adopt-source-node-identities) "adopt complete source baseline")
  (check (source-node-identities-active?) "owner identity index enabled")
  (check (adopt-source-node-identities) "idempotent adoption")
  (check (== (buffer-tree) baseline) "adoption does not rewrite source")

  (start-editing)
  (tree-insert (buffer-tree) 2
    (list (stree->tree '(concat "Formatted " (em "inline text")))))
  (commit-changes)
  (check (not (equal? (tree-node-id (tree-ref (buffer-tree) 2)) ""))
         "formatting paragraph receives identity")
  (check (equal? (tree-node-id (tree-ref (buffer-tree) 2 1 0)) "")
         "transparent formatting does not turn inline text into a paragraph")
  (undo 0)
  (check (== (buffer-tree) baseline) "formatting transaction restores baseline")
  (reset-history)

  ;; UUID allocation belongs to the input transaction, not a later save.
  (start-editing)
  (tree-insert (buffer-tree) 2 (list (stree->tree "New paragraph")))
  (commit-changes)
  (define inserted (tree-copy (buffer-tree)))
  (check (not (equal? (tree-node-id (tree-ref inserted 2)) ""))
         "new paragraph receives identity")
  (check (same-header? inserted baseline) "root survives insertion")
  (undo 0)
  (check (== (buffer-tree) baseline) "undo removes the recorded new object")
  (redo 0)
  (check (== (buffer-tree) inserted) "redo replays the same UUID")

  (start-editing)
  (tree-split (buffer-tree) 0 (utf8-byte-length "第"))
  (commit-changes)
  (define split-source (tree-copy (buffer-tree)))
  (check (equal? (tree-node-id (tree-ref split-source 0))
                 (tree-node-id (tree-ref inserted 0))) "split retains first identity")
  (check (not (equal? (tree-node-id (tree-ref split-source 1))
                      (tree-node-id (tree-ref split-source 0)))) "split creates distinct identity")
  (undo 0)
  (check (== (buffer-tree) inserted) "split undo restores headers")
  (redo 0)
  (check (== (buffer-tree) split-source) "split redo reuses second UUID")
  (start-editing)
  (tree-join (buffer-tree) 0)
  (commit-changes)
  (check (equal? (tree-node-id (tree-ref (buffer-tree) 0))
                 (tree-node-id (tree-ref inserted 0))) "join keeps first identity")

  ;; Duplicate snapshots may not masquerade as new source objects.
  (define before-failure (tree-copy (buffer-tree)))
  (start-editing)
  (tree-insert (buffer-tree) 0 (list (tree-copy (tree-ref (buffer-tree) 0))))
  (commit-changes)
  (check (== (buffer-tree) before-failure) "duplicate insertion rolls back whole edit")
  (start-editing)
  (tree-insert (buffer-tree) 0 (list (stree->tree "Cancelled paragraph")))
  (cancel-editing)
  (check (== (buffer-tree) before-failure) "cancel restores actual source")
  (start-editing)
  (tree-insert (buffer-tree) 0 (list (tree-duplicate-source (tree-ref (buffer-tree) 0))))
  (commit-changes)
  (check (unique? (ids (buffer-tree))) "index usable after rollback")
  (check (= (tree-arity (buffer-tree)) (+ (tree-arity before-failure) 1))
         "new-object duplicate succeeds")

  ;; Baseline replacement is preflighted before old source and data are touched.
  (define before-replace (tree-copy (buffer-tree)))
  (buffer-set-body name '(document "Not migrated"))
  (check (== (buffer-tree) before-replace) "failed replacement preserves source")
  (define ambiguous (annotate-all
    (stree->tree '(document (test-unknown-role "Not classified")))))
  (buffer-set-body name ambiguous)
  (check (== (buffer-tree) before-replace) "ambiguous role preserves old baseline")
  (define replacement (annotate-all (stree->tree '(document "Replacement baseline"))))
  (buffer-set-body name replacement)
  (reset-history)
  (check (source-node-identities-active?) "replacement keeps owner model state")
  (start-editing)
  ;; IDs removed with the previous body must not linger in the disposable index.
  (tree-insert (buffer-tree) 1 (list (tree-copy (tree-ref before-replace 0))))
  (commit-changes)
  (check (= (tree-arity (buffer-tree)) 2) "replacement reindexes new baseline")

  ;; Native snapshots preserve every envelope layer while applying save policy.
  (define snapshot (buffer-get name))
  (check (equal? (header snapshot) expected-root) "document envelope header")
  (for-each
    (lambda (entry)
      (check (and (tree? (tree-ref snapshot (car entry)))
                  (equal? (header (tree-ref snapshot (car entry))) (cdr entry)))
             (list "field header" (car entry) (tree->stree snapshot))))
    expected-fields)
  (check (equal? (header (tree-ref snapshot 'initial 0)) expected-collection)
         "initial collection header")
  (define setting (tree-ref snapshot 'initial 0 0))
  (check (equal? (header setting) expected-association) "association header")
  (check (equal? (header (tree-ref setting 0)) expected-key)
         "association key header")
  (check (= (tree-arity (tree-ref snapshot 'initial 0)) 1) "viewport field stays filtered")
  (define live-before (tree-copy (buffer-tree)))
  (tree-update-node-properties! (tree-ref snapshot 'body 0)
    '(("test:snapshot-only" (boolean #t))) '())
  (check (== (buffer-tree) live-before) "snapshot owns metadata independently")

  ;; Correctors may transform anonymous content but not erase annotated nodes.
  (define math-source
    (annotate-all (stree->tree
      '(document (concat (math (concat "x" "+" "y")))
                 (math (rsup (rsup "n")))))))
  (for-each
    (lambda (correct)
      (let ((result (correct (tree-copy math-source))))
        (check (retains-ids? math-source result) "correction retains every source identity")
        (check (same-header? math-source result) "correction retains root properties")))
    (list manual-correct with-correct with-correct-superfluous
          invisible-correct-superfluous
          (lambda (t) (invisible-correct-missing t 1))
          (lambda (t) (tree-upgrade-brackets t "text"))
          tree-upgrade-big tree-downgrade-big
          (lambda (t) (tree-downgrade-brackets t #f #t))))
  (define correction-target (manual-correct (tree-copy (tree-ref (buffer-tree) 0))))
  (start-editing)
  (tree-set-diff (tree-ref (buffer-tree) 0) correction-target)
  (commit-changes)
  (check (same-header? (tree-ref (buffer-tree) 0) correction-target)
         "corrected source crosses native diff without header loss")

  ;; No global persistence-format switch: metadata must fail closed in v1.
  (check (buffer-save name) "default v1 save rejects identified source")
  (check (== (buffer-tree) live-before) "failed v1 save leaves source intact")
  (display "ATHENA-NODE-SOURCE-LIFECYCLE-PASS\n"))

(unless (exec-buffer name
  (lambda ()
    (let ((result (catch #t (lambda () (run-lifecycle) #t) (lambda args args))))
      (call-with-output-file (string-append test-root "/result.scm")
        (lambda (port) (write result port)))
      (exec-global (lambda () (quit-TeXmacs))))))
  (error "Could not enter source lifecycle owner"))
