;; New ordinary source documents are born in XML-v2/identity mode.  This runs
;; against real BufferActors in an isolated profile; no existing file is
;; upgraded by the fixture.
(define (check condition label)
  (unless condition (error "New XML v2 source regression" label)))

(define root (getenv "ATHENA_NODE_NEW_V2_ROOT"))
(define name (string->url (string-append root "/created.ath")))
(define inserted-id #f)

(define (finish value)
  (call-with-output-file (string-append root "/result.scm")
    (lambda (port) (write value port)))
  (quit-TeXmacs))

(define (fail . args)
  (exec-global (lambda () (finish args))))

(define (check-last-object-deletion content)
  (start-editing)
  (tree-assign (tree-ref (buffer-tree) 0) (stree->tree content))
  (commit-changes)
  (clear-undo-history)
  (let ((root-id (tree-node-id (buffer-tree)))
        (old-id (tree-node-id (tree-ref (buffer-tree) 0))))
    (check (not (equal? old-id "")) "deletion fixture has source identity")
    (tree-select (tree-ref (buffer-tree) 0))
    (start-editing)
    (kbd-remove (buffer-tree) #f)
    (commit-changes)
    (check (equal? (tree->stree (buffer-tree)) '(document ""))
           "deleting last identified object leaves an empty paragraph")
    (check (equal? (tree-node-id (buffer-tree)) root-id)
           "deletion preserves document identity")
    (let ((empty-id (tree-node-id (tree-ref (buffer-tree) 0))))
      (check (and (not (equal? empty-id ""))
                  (not (equal? empty-id old-id)))
             "replacement paragraph has a new identity")
      (undo 0)
      (check (and (equal? (tree->stree (tree-ref (buffer-tree) 0)) content)
                  (equal? (tree-node-id (tree-ref (buffer-tree) 0)) old-id))
             "undo restores deleted object and identity")
      (redo 0)
      (check (and (equal? (tree->stree (buffer-tree)) '(document ""))
                  (equal? (tree-node-id (tree-ref (buffer-tree) 0)) empty-id))
             "redo preserves the recorded replacement identity")))
  (start-editing)
  (insert "Still editable")
  (commit-changes)
  (check (equal? (tree->stree (buffer-tree)) '(document "Still editable"))
         "cursor remains in the replacement paragraph"))

(define (run-created)
  (catch #t
    (lambda ()
      (check (source-node-identities-active?)
             "new named source did not activate node identities")
      (check (not (equal? (tree-node-id (buffer-tree)) ""))
             "new source body has no UUID")
      (check (and (> (tree-arity (buffer-tree)) 0)
                  (not (equal? (tree-node-id (tree-ref (buffer-tree) 0)) "")))
             "new source initial paragraph has no UUID")
      (buffer-set-default-style)
      (check-last-object-deletion '(equation* "x=1"))
      (check-last-object-deletion "Last paragraph")
      (start-editing)
      (tree-insert (buffer-tree) (tree-arity (buffer-tree))
                   (list (stree->tree "Created paragraph")))
      (commit-changes)
      (set! inserted-id
            (tree-node-id
              (tree-ref (buffer-tree) (- (tree-arity (buffer-tree)) 1))))
      (check (not (equal? inserted-id ""))
             "ordinary edit in new source did not receive UUID")
      (check (not (buffer-save name)) "first save of new source failed")

      ;; The user-facing New command uses a separate source-buffer allocator;
      ;; transient DataArt still uses make_new_buffer and is not tested here.
      (exec-global
        (lambda ()
          (let ((scratch (new-buffer)))
            (check (exec-buffer scratch
                     (lambda ()
                       (check (source-node-identities-active?)
                              "New scratch buffer is not identity-active")
                       (check (not (equal? (tree-node-id (buffer-tree)) ""))
                              "New scratch body has no UUID")))
                   "could not enter New scratch BufferActor")
            (finish (list #t inserted-id))))))
    fail))

(catch #t
  (lambda ()
    (check (not (buffer-create-source name)) "native v2 source creation failed")
    (switch-to-buffer name)
    (check (exec-buffer name run-created) "could not enter created source owner"))
  (lambda args (finish args)))
