;; Owner-local native reconstruction and in-memory history transport. No vault
;; or source document is opened or saved by this check.
(import-from (kernel library patch))

(define (check condition label)
  (unless condition (error "Node model bridge regression" label)))

(define source (stree->tree '(document (concat "left" (strong "right")))))
(check (equal? (tree-node-id source) "") "unassigned identity")
(check (== (tree-duplicate-source source) source) "copy without identity")
(check (equal? (tree->stree
                (tree-rebuild source (list (stree->tree "replacement"))))
               '(document "replacement")) "native reconstruction")
(check (equal? (tree->stree source)
               '(document (concat "left" (strong "right"))))
       "reconstruction leaves source untouched")
(define replaced (tm-replace source "left" "changed"))
(check (tree? replaced) "native replacement does not become stree")
(check (equal? (tree->stree replaced)
               '(document (concat "changed" (strong "right"))))
       "native replacement content")
(check (equal? (tm-replace '(document "left") "left" "changed")
               '(document "changed")) "stree callers remain stree")

(define direct (modification-assign '(0) (stree->tree "new")))
(define inverse (modification-invert direct source))
(define pair-patch (patch-pair direct inverse))
(define authored (patch-author 7.0 pair-patch))
(define encoded (modification->scheme direct))
(check (tree? (caddr encoded)) "history carries native trees")
(check (== direct (scheme->modification encoded)) "modification round trip")
(check (== pair-patch (scheme->patch (patch->scheme pair-patch)))
       "patch round trip")
(check (== authored (scheme->patch (patch->scheme authored)))
       "author wrapper round trip")
(define birth (patch-birth 9.0 #t))
(check (== birth (scheme->patch (patch->scheme birth)))
       "birth wrapper preserves author and direction")
(define compound-patch (patch-compound (list birth authored)))
(check (== compound-patch (scheme->patch (patch->scheme compound-patch)))
       "compound history round trip")
(display "ATHENA-NODE-BRIDGE-PASS\n")
