;; New ordinary source documents are born in XML-v2/identity mode.  This runs
;; against real BufferActors in an isolated profile; no existing file is
;; upgraded by the fixture.
(define (check condition label)
  (unless condition (error "New XML v2 source regression" label)))

(define root (getenv "ATHENA_NODE_NEW_V2_ROOT"))
(define name (string->url (string-append root "/created.ath")))
(define inserted-id #f)
(set-preference "check for updates" "off")
(set-preference "document save mode" "manual")

(define (run-maintenance)
  (define vault (getenv "ATHENA_TEST_MAINTENANCE_ROOT"))
  (check (equal? (vault-load-with-ns (string->url vault) "Maintenance fixture"
                                    "map.sqlite" "ns.sqlite") "") "load maintenance vault")
  (let ((live (string->url (string-append vault "/live.ath"))))
    (check (not (buffer-load live)) "load live legacy enunciation")
    (switch-to-buffer live)
    (exec-buffer live
      (lambda ()
        (start-editing)
        (tree-go-to (tree-ref (buffer-tree) 0 0 0) :end)
        (insert " UNSAVED EDIT")
        (commit-changes)))
    (delayed (:pause 8000)
      (exec-global (lambda () (exec-buffer live
        (lambda ()
          (catch #t
            (lambda ()
              (let* ((node (tree-ref (buffer-tree) 0)) (id (tree-node-id node)))
                (check (tree-func? node 'enunciation 1) "live maintenance canonicalized source")
                (check (equal? (tree->stree (tree-ref node 0))
                               '(document "Original body UNSAVED EDIT")) "maintenance retains unsaved edit")
                (undo 0)
                (check (tree-func? (tree-ref (buffer-tree) 0) 'definition 1) "maintenance is undoable")
                (redo 0)
                (check (equal? (tree-node-id (tree-ref (buffer-tree) 0)) id) "maintenance redo retains identity"))
              (exec-global (lambda () (finish (list #t inserted-id)))))
            fail))))))))

(define (finish value)
  (call-with-output-file (string-append root "/result.scm")
    (lambda (port) (write value port)))
  (quit-TeXmacs))

(define (fail . args)
  (exec-global (lambda () (finish args))))

(define (check-last-object-deletion content)
  (start-editing)
  (tree-assign (tree-ref (buffer-tree) 0) (stree->tree content))
  (commit-changes)
  (clear-undo-history)
  (let ((root-id (tree-node-id (buffer-tree)))
        (old-id (tree-node-id (tree-ref (buffer-tree) 0))))
    (check (not (equal? old-id "")) "deletion fixture has source identity")
    (tree-select (tree-ref (buffer-tree) 0))
    (start-editing)
    (kbd-remove (buffer-tree) #f)
    (commit-changes)
    (check (equal? (tree->stree (buffer-tree)) '(document ""))
           "deleting last identified object leaves an empty paragraph")
    (check (equal? (tree-node-id (buffer-tree)) root-id)
           "deletion preserves document identity")
    (let ((empty-id (tree-node-id (tree-ref (buffer-tree) 0))))
      (check (and (not (equal? empty-id ""))
                  (not (equal? empty-id old-id)))
             "replacement paragraph has a new identity")
      (undo 0)
      (check (and (equal? (tree->stree (tree-ref (buffer-tree) 0)) content)
                  (equal? (tree-node-id (tree-ref (buffer-tree) 0)) old-id))
             "undo restores deleted object and identity")
      (redo 0)
      (check (and (equal? (tree->stree (buffer-tree)) '(document ""))
                  (equal? (tree-node-id (tree-ref (buffer-tree) 0)) empty-id))
             "redo preserves the recorded replacement identity")))
  (start-editing)
  (insert "Still editable")
  (commit-changes)
  (check (equal? (tree->stree (buffer-tree)) '(document "Still editable"))
         "cursor remains in the replacement paragraph"))

(define (run-created)
  (catch #t
    (lambda ()
      (check (source-node-identities-active?)
             "new named source did not activate node identities")
      (check (not (equal? (tree-node-id (buffer-tree)) ""))
             "new source body has no UUID")
      (check (and (> (tree-arity (buffer-tree)) 0)
                  (not (equal? (tree-node-id (tree-ref (buffer-tree) 0)) "")))
             "new source initial paragraph has no UUID")
      (buffer-set-default-style)
      (for-each
        (lambda (entry)
          (start-editing)
          (tree-assign (tree-ref (buffer-tree) 0) "")
          (tree-go-to (tree-ref (buffer-tree) 0) :start)
          (cpp-make-hybrid)
          (insert (car entry))
          (activate-hybrid #f)
          (commit-changes)
          (let ((node (tree-ref (buffer-tree) 0)))
            (check (tree-func? node 'enunciation 1) "LaTeX command creates canonical enunciation")
            (check (tree-func? (tree-ref node 0) 'document) "enunciation has DOCUMENT body")
            (check (equal? (cadr (assoc "kind" (tree-node-properties node)))
                           (list 'string (cadr entry))) "enunciation kind")
            (let ((id (tree-node-id node)))
              (check (not (equal? id "")) "enunciation received UUID")
              (undo 0)
              (redo 0)
              (check (equal? (tree-node-id (tree-ref (buffer-tree) 0)) id)
                     "enunciation redo retains UUID"))))
        '(("def" "definition") ("cor" "corollary") ("thm" "theorem")
          ("lem" "lemma") ("eg" "example") ("pf" "proof")))
      (check-last-object-deletion '(equation* "x=1"))
      (check-last-object-deletion "Last paragraph")
      (start-editing)
      (tree-insert (buffer-tree) (tree-arity (buffer-tree))
                   (list (stree->tree "Created paragraph")))
      (commit-changes)
      (set! inserted-id
            (tree-node-id
              (tree-ref (buffer-tree) (- (tree-arity (buffer-tree)) 1))))
      (check (not (equal? inserted-id ""))
             "ordinary edit in new source did not receive UUID")
      (check (not (buffer-save name)) "first save of new source failed")

      ;; The user-facing New command uses a separate source-buffer allocator;
      ;; transient DataArt still uses make_new_buffer and is not tested here.
      (exec-global
        (lambda ()
          (let ((scratch (new-buffer)))
            (check (exec-buffer scratch
                     (lambda ()
                       (check (source-node-identities-active?)
                              "New scratch buffer is not identity-active")
                       (check (not (equal? (tree-node-id (buffer-tree)) ""))
                              "New scratch body has no UUID")))
                   "could not enter New scratch BufferActor")
            (if (getenv "ATHENA_TEST_CONTINUOUS_MAINTENANCE")
                (run-maintenance)
                (finish (list #t inserted-id)))))))
    fail))

(catch #t
  (lambda ()
    (check (not (buffer-create-source name)) "native v2 source creation failed")
    (switch-to-buffer name)
    (check (exec-buffer name run-created) "could not enter created source owner"))
  (lambda args (finish args)))
