;; Native exact tree updates on a real owner editor. No vault or saved file.
(import-from (generic generic-edit))
(init-style "generic")
(define (check condition label)
  (unless condition (error "Native tree diff regression" label)))
(define (annotate node)
  (check (eq? (car (tree-ensure-node-id! node)) 'ok) "assign identity")
  (check (eq? (car (tree-update-node-properties! node
                    '(("test:marker" (string "before"))) '())) 'ok) "assign property"))
(define (install node)
  (selection-cancel)
  (buffer-set-body (current-buffer)
    (tree-rebuild (stree->tree '(document)) (list node)))
  (update-current-buffer)
  (commit-changes)
  (clear-undo-history)
  ;; Match a normal editor command's author, not the ambient Scheme author.
  (start-editing))
(define (current) (tree-ref (buffer-tree) 0))
(define (describe node)
  (list (tree->stree node) (tree-node-id node) (tree-node-properties node)
        (if (tree-atomic? node) '() (map describe (tree-children node)))))
(define (replace-text-copy source text)
  (let ((target (tree-copy source)))
    (tree-remove target 0 (utf8-byte-length (tree->string target)))
    (tree-var-insert target 0 text)
    target))

;; Includes matching scalar prefixes that are NOT whole grapheme prefixes.
(for-each
  (lambda (texts)
    (let ((source (stree->tree (car texts))))
      (annotate source)
      (install source)
      (let* ((original (tree-copy (current)))
             (target (replace-text-copy original (cadr texts)))
             (pointer (tree->tree-pointer (current))))
        (tree-go-to (current) :end)
        (tree-set-diff (current) target)
        (check (== (current) target) "exact UTF-8 text and metadata")
        (check (equal? (tree->path (tree-pointer->tree pointer)) (tree->path (current)))
               "text observer survives local edit")
        (check (equal? (cursor-path) (tree->path (current) :end)) "suffix cursor follows byte edits")
        (commit-changes)
        (undo 0)
        (check (== (current) original) "text undo restores identity")
        (redo 0)
        (check (== (current) target) "text redo reuses identity")
        (tree-pointer-detach pointer))))
  '(("你好尾" "你好新尾") ("你好新尾" "你好尾")
    ("é tail" "è tail") ("e tail" "é tail")
    ("👩‍💻 end" "👩‍🔬 end") ("🇨🇳 end" "🇫🇷 end")
    ("" "中文") ("中文" "") ("same" "same")))

(define compound-source (stree->tree '(strong "Left" "Right")))
(annotate compound-source)
(annotate (tree-ref compound-source 0))
(install compound-source)
(define original (tree-copy (current)))
(define target (tree-copy original))
(check (eq? (car (tree-update-node-properties! target
                  '(("test:marker" (string "after"))) '())) 'ok) "change target header")
(define pointer (tree->tree-pointer (tree-ref (current) 0)))
(tree-set-diff (current) target)
(check (== (current) target) "same children still apply target metadata")
(check (equal? (tree->path (tree-pointer->tree pointer)) (tree->path (current) 0))
       "header edit retains child observers")
(commit-changes)
(undo 0)
(check (== (current) original) "header edit undo")
(redo 0)
(check (== (current) target) "header edit redo")
(tree-pointer-detach pointer)

;; Insertion, deletion and label changes must also apply the complete header.
(define added (tree-rebuild target
  (list (tree-ref target 0) (stree->tree "Middle") (tree-ref target 1))))
(tree-update-node-properties! added '(("test:marker" (string "inserted"))) '())
(tree-set-diff (current) added)
(check (== (current) added) "child insertion and metadata")
(define removed (tree-rebuild added (list (tree-ref added 0) (tree-ref added 2))))
(tree-update-node-properties! removed '(("test:marker" (string "removed"))) '())
(tree-set-diff (current) removed)
(check (== (current) removed) "child deletion and metadata")
(define relabeled (tree-copy removed))
(tree-assign-node relabeled 'em)
(tree-update-node-properties! relabeled '(("test:marker" (string "relabeled"))) '())
(tree-set-diff (current) relabeled)
(check (== (current) relabeled) "label and metadata are both updated")

;; A genuinely new target is not silently given the replaced object's header.
(tree-set-diff (current) '(em "Left" "Right"))
(check (equal? (tree-node-id (current)) "") "explicit anonymous replacement clears identity")
(check (null? (tree-node-properties (current))) "explicit replacement clears properties")

(define live-text (stree->tree "Tracked"))
(annotate live-text)
(install live-text)
(define live (current))
(define live-id (tree-node-id live))
(define live-pointer (tree->tree-pointer live))
(tree-go-to live 3)
(define inner (tree-rebuild (stree->tree '(em)) (list live)))
(define wrapper (tree-rebuild (stree->tree '(strong)) (list inner)))
(annotate inner)
(annotate wrapper)
(tree-set-diff live wrapper)
(check (== (current) wrapper) "nested native wrapper target")
(check (equal? (tree-node-id (tree-ref (current) 0 0)) live-id) "wrapped source retains identity")
(check (equal? (tree->path (tree-pointer->tree live-pointer)) (tree->path (current) 0 0))
       "wrapper preserves source observer")
(check (equal? (cursor-path) (tree->path (current) 0 0 3)) "wrapper preserves cursor")
(define wrapped-snapshot (tree-copy (current)))
(commit-changes)
(start-editing)
(tree-set-diff (current) (tree-ref (current) 0 0))
(check (equal? (tree-node-id (current)) live-id) "explicit unwrapping keeps actual descendant")
(check (equal? (cursor-path) (tree->path (current) 3)) "unwrap preserves cursor")
(commit-changes)
(undo 0)
(unless (== (current) wrapped-snapshot)
  (error "unwrap undo restores both wrapper identities"
         (describe (current)) (describe wrapped-snapshot)))
(redo 0)
(check (equal? (tree-node-id (current)) live-id) "unwrap redo retains descendant identity")
(tree-pointer-detach live-pointer)

(import-from (athena athena tm-materials))
(define bibliography
  (stree->tree '(referenced-materials "" (tuple "material") (document "Rendered bibliography"))))
(annotate bibliography)
(annotate (tree-ref bibliography 2))
(annotate (tree-ref bibliography 2 0))
(define original-bibliography (tree-copy bibliography))
(install bibliography)
(tree-go-to (current) 2 0 :end)
(materials-set-reference-style "apa")
(check (equal? (tree-node-id (current)) (tree-node-id original-bibliography))
       "bibliography style edit retains root identity")
(check (== (tree-ref (current) 2) (tree-ref original-bibliography 2))
       "bibliography style edit does not reconstruct its body")
(check (equal? (tree->string (tree-ref (current) 0)) "apa") "style field changed")
(display "ATHENA-NODE-TREE-DIFF-PASS\n")
