;; Owner-local native reconstruction and in-memory history transport. No vault
;; or source document is opened or saved by this check.
(import-from (kernel library patch))

(define (check condition label)
  (unless condition (error "Node model bridge regression" label)))

(define source (stree->tree '(document (concat "left" (strong "right")))))
(check (equal? (tree-node-id source) "") "unassigned identity")
(check (== (tree-duplicate-source source) source) "copy without identity")
(check (equal? (tree->stree
                (tree-rebuild source (list (stree->tree "replacement"))))
               '(document "replacement")) "native reconstruction")
(check (equal? (tree->stree source)
               '(document (concat "left" (strong "right"))))
       "reconstruction leaves source untouched")
(define replaced (tm-replace source "left" "changed"))
(check (tree? replaced) "native replacement does not become stree")
(check (equal? (tree->stree replaced)
               '(document (concat "changed" (strong "right"))))
       "native replacement content")
(check (equal? (tm-replace '(document "left") "left" "changed")
               '(document "changed")) "stree callers remain stree")

(define direct (modification-assign '(0) (stree->tree "new")))
(define inverse (modification-invert direct source))
(define pair-patch (patch-pair direct inverse))
(define authored (patch-author 7.0 pair-patch))
(define encoded (modification->scheme direct))
(check (tree? (caddr encoded)) "history carries native trees")
(check (== direct (scheme->modification encoded)) "modification round trip")
(check (== pair-patch (scheme->patch (patch->scheme pair-patch)))
       "patch round trip")
(check (== authored (scheme->patch (patch->scheme authored)))
       "author wrapper round trip")
(define birth (patch-birth 9.0 #t))
(check (== birth (scheme->patch (patch->scheme birth)))
       "birth wrapper preserves author and direction")
(define compound-patch (patch-compound (list birth authored)))
(check (== compound-patch (scheme->patch (patch->scheme compound-patch)))
       "compound history round trip")
(define (ok? result) (eq? (car result) 'ok))
(define (error? result) (eq? (car result) 'error))
(define paragraph (stree->tree "Atomic paragraph"))
(define assigned (tree-ensure-node-id! paragraph))
(check (ok? assigned) "assign identity")
(define identity (cadr assigned))
(check (equal? (tree-node-id paragraph) identity) "identity is stored")
(check (equal? assigned (tree-ensure-node-id! paragraph)) "assignment is idempotent")
(define rich (stree->tree '(concat "Structured " (em "name"))))
(define properties
  `(("test:string" (string "Unicode λ 中文"))
    ("test:boolean" (boolean #f))
    ("test:integer" (integer 9223372036854775807))
    ("test:min-integer" (integer -9223372036854775808))
    ("test:real" (real 1.25))
    ("test:reference" (reference ,identity))
    ("test:rich" (rich-text ,rich))
    ("test:list" (list ((string "entry") (boolean #t))))
    ("test:dictionary" (dictionary (("nested" (integer 7)))))))
(check (ok? (tree-update-node-properties! paragraph properties '()))
       "all eight property types")
(define stored (tree-node-properties paragraph))
(check (equal? (cadr (assoc "test:integer" stored)) '(integer 9223372036854775807))
       "int64 is not narrowed")
(check (equal? (cadr (assoc "test:min-integer" stored)) '(integer -9223372036854775808))
       "negative int64 is not narrowed")
(check (equal? (cadr (assoc "test:boolean" stored)) '(boolean #f)) "false is not absence")
(tree-assign rich (stree->tree "Changed caller tree"))
(define rich-copy (cadr (cadr (assoc "test:rich" stored))))
(check (equal? (tree->stree rich-copy) '(concat "Structured " (em "name")))
       "incoming rich text is owned")
(tree-assign rich-copy (stree->tree "Changed returned tree"))
(check (equal? (tree->stree (cadr (cadr (assoc "test:rich" (tree-node-properties paragraph)))))
               '(concat "Structured " (em "name"))) "getter does not expose mutable properties")
(define before-errors (tree-copy paragraph))
(for-each
  (lambda (bad)
    (check (error? (tree-update-node-properties! paragraph bad '())) "reject invalid property")
    (check (== paragraph before-errors) "failed edit is atomic"))
  '((("id" (string "replace identity")))
    (("athena:artifact-bindings" (dictionary ())))
    (("year" (string "not an enunciation")))
    (("test:integer" (integer 9223372036854775808)))
    (("test:integer" (integer 1.0)))
    (("test:real" (real +inf.0)))
    (("test:real" (real 1/3)))
    (("test:boolean" (boolean 0)))
    (("test:reference" (reference "not a uuid")))
    (("test:rich" (rich-text (em "stree is not a native tree"))))
    (("test:duplicate" (string "a")) ("test:duplicate" (string "b")))))
(define cycle (list (list "test:cycle" '(string "value"))))
(set-cdr! cycle cycle)
(check (error? (tree-update-node-properties! paragraph cycle '())) "reject cyclic lists")
(check (ok? (tree-update-node-properties! paragraph '() '("test:real"))) "remove property")
(check (not (assoc "test:real" (tree-node-properties paragraph))) "removed entry")
(check (equal? identity (tree-node-id paragraph)) "property edits preserve identity")
(define duplicated (tree-duplicate-source paragraph))
(check (not (equal? (tree-node-id duplicated) identity)) "new object identity")
(check (equal? (cadr (assoc "test:reference" (tree-node-properties duplicated)))
               (list 'reference (tree-node-id duplicated))) "self-reference remaps")
(define replaced-native (tm-replace (tree-rebuild source (list paragraph))
                                   "Atomic paragraph" "Replacement"))
(check (tree? replaced-native) "metadata reconstruction remains native")
(display "ATHENA-NODE-BRIDGE-PASS\n")
