;; Isolated real-actor check: vault-wide overlay, deletion masking, discard and
;; successful-save-only persistence. No models or production documents.
(define root (getenv "ATHENA_REALTIME_ARTIFACT_TEST_ROOT"))
(define vault (string-append root "/vault"))
(define source (string->url (string-append vault "/source.ath")))
(define reader (string->url (string-append vault "/reader.ath")))
(define (check value label) (unless value (error "Realtime artifacts" label)))
(define (finish result)
  (call-with-output-file (string-append root "/result.scm")
    (lambda (port) (write result port)))
  (quit-TeXmacs))
(define (guard thunk)
  (catch #t thunk (lambda args (exec-global (lambda () (finish args))))))
(define (later thunk)
  (delayed (:pause 2500) (exec-global (lambda () (guard thunk)))))
(define (in-buffer target thunk after)
  (exec-buffer target (lambda () (guard (lambda ()
    (thunk)
    (exec-global after))))))
(define (has-link? value)
  (and (pair? value)
    (or (eq? (car value) 'hlink)
        (has-link? (car value)) (has-link? (cdr value)))))
(define (found? name)
  (let* ((url (artifact-name-query-url (stree->tree name)))
         (encoded (substring url (string-length "tmfs://artifact-name-query/"))))
    (has-link? (tree->stree (artifact-name-query-page encoded)))))
(define (put target name)
  (exec-buffer target (lambda ()
    (start-editing)
    (tree-assign (tree-ref (buffer-tree) 0)
      (stree->tree `(concat (strong ,name) " is the definition.")))
    (commit-changes))))

(set-preference "check for updates" "off")
(set-preference "document save mode" "manual")
(guard (lambda ()
  (check (equal? (vault-load-with-ns (string->url vault) "Realtime fixture"
                                    "map.sqlite" "ns.sqlite") "") "load vault")
  (check (not (buffer-create-source source)) "create source")
  (switch-to-buffer source)
  (put source "quasar operator")
  (exec-buffer source (lambda () (check (not (buffer-save source)) "save source")))
  (check (not (buffer-create-source reader)) "create reader")
  (switch-to-buffer reader)
  (later (lambda ()
    (in-buffer reader
      (lambda () (check (found? "quasar operator") "saved name visible"))
      (lambda ()
        (put source "stellar operator")
        (later (lambda ()
          (in-buffer reader
            (lambda ()
              (check (found? "stellar operator") "unsaved name visible in another buffer")
              (check (not (found? "quasar operator")) "old saved name masked"))
            (lambda ()
              (cpp-buffer-close source)
              (later (lambda ()
                (in-buffer reader
                  (lambda ()
                    (check (found? "quasar operator") "discard reveals saved name")
                    (check (not (found? "stellar operator")) "discard removes unsaved name"))
                  (lambda ()
                    (put reader "quasar field")
                    (in-buffer reader
                      (lambda () (check (not (buffer-save reader)) "save before exit"))
                      (lambda () (finish '(#t))))))))))))))))))
