;; Native structured commands execute against a real BufferActor-owned tree.
(import-from (generic generic-edit))
(init-style "generic")

(define (body) (tree->stree (buffer-tree)))
(define (check condition message)
  (unless condition (error message (body) (cursor-path))))
(define (reset-tree)
  (selection-cancel)
  (buffer-set-body (current-buffer)
                   (stree->tree '(document (tree "root" "a" "b"))))
  (update-current-buffer)
  (tree-go-to (tree-ref (buffer-tree) 0 2) :start)
  (commit-changes)
  (clear-undo-history))
(define (branch) (tree-ref (buffer-tree) 0))

(check (generic-context? (stree->tree '(foo "x")))
       "generic context defaults to true")
(check (complex-context? (stree->tree '(foo "x"))) "extension is complex")
(check (not (complex-context? (stree->tree '(document "x"))))
       "document is simple markup")
(check (document-context? (stree->tree '(document "x"))) "document context")
(check (table-markup-context?
        (stree->tree '(wrapper (document (table "x")))))
       "wrapped table markup context")
(check (structured-vertical? (stree->tree '(tree "root" "a")))
       "tree is vertically structured")

(reset-tree)
(structured-insert-horizontal (focus-tree) #f)
(check (equal? (body) '(document (tree "root" "a" "" "b")))
       "insert branch before current")
(check (equal? (cursor-path) '(0 0 2 0)) "insert-left cursor")

(reset-tree)
(structured-insert-horizontal (focus-tree) #t)
(check (equal? (body) '(document (tree "root" "a" "b" "")))
       "insert branch after current")
(check (equal? (cursor-path) '(0 0 3 0)) "insert-right cursor")

(reset-tree)
(structured-insert-left)
(check (equal? (body) '(document (tree "root" "a" "" "b")))
       "no-argument structured insert-left")
(check (equal? (cursor-path) '(0 0 2 0)) "no-argument insert-left cursor")

(reset-tree)
(structured-remove-horizontal (focus-tree) #f)
(check (equal? (body) '(document (tree "root" "b")))
       "remove previous branch")
(check (equal? (cursor-path) '(0 0 1 0)) "remove-left cursor")

(reset-tree)
(structured-remove-horizontal (focus-tree) #t)
(check (equal? (body) '(document (tree "root" "a")))
       "remove current branch forwards")
(check (equal? (cursor-path) '(0 0 1)) "remove-right cursor")

(reset-tree)
(structured-insert-vertical (focus-tree) #f)
(check (equal? (body) '(document (tree "root" "a" (tree "" "b"))))
       "insert parent branch above")
(check (equal? (cursor-path) '(0 0 2 0 0)) "insert-up cursor")

(reset-tree)
(structured-insert-vertical (focus-tree) #t)
(check (equal? (body) '(document (tree "root" "a" (tree "b" ""))))
       "insert child branch below")
(check (equal? (cursor-path) '(0 0 2 1 0)) "insert-down cursor")

(reset-tree)
(structured-horizontal (focus-tree) #f)
(check (equal? (cursor-path) '(0 0 1 1)) "move to previous branch")
(reset-tree)
(structured-left)
(check (equal? (cursor-path) '(0 0 1 1)) "no-argument structured left")
(reset-tree)
(structured-horizontal (focus-tree) #t)
(check (equal? (cursor-path) '(0 0 2 0)) "right edge stays on last branch")
(reset-tree)
(structured-vertical (focus-tree) #f)
(check (equal? (cursor-path) '(0 0 0 4)) "move to tree label")
(reset-tree)
(structured-vertical (focus-tree) #t)
(check (equal? (cursor-path) '(0 0 2 0)) "down on a branch is stable")
(reset-tree)
(structured-extremal (focus-tree) #f)
(check (equal? (cursor-path) '(0 0 1 0)) "move to first branch")
(reset-tree)
(structured-extremal (focus-tree) #t)
(check (equal? (cursor-path) '(0 0 2 1)) "move to last branch end")

;; Later Scheme overloads still intercept native generic fallback, including
;; when native code walks outward from an inner atomic node.
(tm-define (structured-horizontal t forwards?)
  (:require (tree-is? t 'structured-test-extension))
  (tree-set! t 0 (if forwards? "right" "left")))
(buffer-set-body (current-buffer)
                 (stree->tree '(document (structured-test-extension "x"))))
(update-current-buffer)
(tree-go-to (tree-ref (buffer-tree) 0 0) :end)
(structured-horizontal (tree-ref (buffer-tree) 0 0) #t)
(check (equal? (body) '(document (structured-test-extension "right")))
       "outward dispatch reaches Scheme extension")
(tree-set! (tree-ref (buffer-tree) 0) 0 "x")
(structured-extremal (tree-ref (buffer-tree) 0) #t)
(check (equal? (body) '(document (structured-test-extension "right")))
       "compound native command dispatches through Scheme specialization")

(tm-define (special-horizontal t forwards?)
  (:require (tree-is? t 'special-test-extension))
  (tree-set! t 0 (if forwards? "right" "left")))
(buffer-set-body (current-buffer)
                 (stree->tree '(document (special-test-extension "x"))))
(update-current-buffer)
(tree-go-to (tree-ref (buffer-tree) 0 0) :end)
(special-right)
(check (equal? (body) '(document (special-test-extension "right")))
       "no-argument special movement reaches Scheme extension")

(tm-define (special-navigate t direction)
  (:require (tree-is? t 'special-navigate-extension))
  (tree-set! t 0 (if (== direction :previous) "previous" "other")))
(buffer-set-body (current-buffer)
                 (stree->tree '(document (special-navigate-extension "x"))))
(update-current-buffer)
(tree-go-to (tree-ref (buffer-tree) 0 0) :end)
(special-back)
(check (equal? (body) '(document (special-navigate-extension "previous")))
       "native special-back preserves keyword direction")

(init-env "page-medium" "paper")
(update-current-buffer)
(update-forced)
(print-to-file (string->url (string-append (getenv "HOME") "/evaluation.pdf")))
#t
