;; Run with: guile --no-auto-compile tests/scheme/unsaved-buffers-test.scm ROOT
;; Exercise the shipped Scheme procedures with explicit UI/actor queues.
(use-modules (srfi srfi-1))

(define root (cadr (command-line)))
(define (load-procedures path names)
  (call-with-input-file (string-append root path)
    (lambda (port)
      (let loop ((form (read port)))
        (unless (eof-object? form)
          (when (and (pair? form) (memq (car form) '(define tm-define))
                     (pair? (cadr form)) (memq (caadr form) names))
            (eval (cons 'define (cdr form)) (current-module)))
          (loop (read port)))))))

(define domain 'ui)
(define pending '())
(define saves '())
(define completions '())
(define finished #f)
(define modified '("one" "two"))
(define (check condition message)
  (unless condition (error message)))
(define (require-domain expected)
  (check (equal? expected domain) (list 'wrong-domain expected domain)))
(define (exec-global command)
  (if (eq? domain 'ui) (command)
      (set! pending (append pending (list command)))))
(define (drain-ui)
  (set! domain 'ui)
  (let ((commands pending))
    (set! pending '())
    (for-each (lambda (command) (command)) commands)))
(define (url->url name) name)
(define (buffer-exists? name) (not (equal? name "gone")))
(define (buffer-modified? name) (member name modified))
(define (switch-to-buffer name) (require-domain 'ui))
(define (notify-now text) (error text))
(define (quit-TeXmacs) (require-domain 'ui) (set! finished 'exit))
(define (restart-TeXmacs)
  (require-domain 'ui) (set! finished 'restart) #t)
(define (exec-buffer name command)
  (require-domain 'ui)
  (set! domain name)
  (command)
  (set! domain 'ui)
  #t)
(define (save-buffer-manual name callback)
  (require-domain name)
  (set! saves (append saves (list name)))
  (set! completions (append completions (list (cons name (cdr callback))))))
(define (save-success)
  (let ((completion (car completions)))
    (set! completions (cdr completions))
    (set! domain (car completion))
    ((cdr completion))
    (drain-ui)))

(load-procedures "/ATHENA/progs/athena/athena/tm-server.scm"
  '(finish-ATHENA save-selected-unsaved-buffers-and-finish
    safely-quit-ATHENA safely-restart-ATHENA))

;; Creation must leave the initiating actor before touching any Qt widget.
(define (confirm-finish-ATHENA restart?)
  (require-domain 'ui) (set! finished restart?))
(set! domain "one")
(safely-quit-ATHENA)
(check (pair? pending) "exit dialog was not queued for the UI")
(drain-ui)
(set! domain "one")
(safely-restart-ATHENA)
(drain-ui)
(check (eq? finished #t) "restart dialog was not created")

(set! finished #f)
(save-selected-unsaved-buffers-and-finish '("one" "two") #f)
(check (equal? saves '("one")) "saves must be serialized")
(check (not finished) "must wait for save-as/confirmation, including cancellation")
(save-success)
(check (equal? saves '("one" "two")) "second save must follow first completion")
(check (not finished) "must not exit while second save is pending/failed")
(save-success)
(check (eq? finished 'exit) "exit after all successful saves")

(set! finished #f)
(save-selected-unsaved-buffers-and-finish '("gone" "unchanged") #t)
(check (eq? finished 'restart) "skip removed and unchanged buffers")
(set! finished #f)
(save-selected-unsaved-buffers-and-finish '() #f)
(check (eq? finished 'exit) "empty selection permits discard")

;; The completion option survives save-as and is delivered by the existing
;; successful-save path, after backup dispatch.
(define (defined? name) (eq? name 'vault-backup-dispatch-realtime))
(define backup #f)
(define (vault-backup-dispatch-realtime name) (set! backup name))
(load-procedures "/ATHENA/progs/athena/athena/tm-files.scm" '(save-buffer-post))
(define completed #f)
(save-buffer-post "renamed.ath"
  (list ':manual (cons 'on-saved
                  (lambda ()
                    (check (equal? backup "renamed.ath") "backup precedes completion")
                    (set! completed #t)))))
(check completed "successful save must invoke completion")
(display "PASS: unsaved buffer UI ownership and save completion sequencing\n")
