
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;
;; MODULE      : latex-kbd.scm
;; DESCRIPTION : setup key combinations for frequently used commands
;; COPYRIGHT   : (C) 1999  Joris van der Hoeven
;;
;; This software falls under the GNU general public license version 3 or later.
;; It comes WITHOUT ANY WARRANTY WHATSOEVER. For details, see the file LICENSE
;; in the root directory or <http://www.gnu.org/licenses/gpl-3.0.html>.
;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(texmacs-module (athena keyboard latex-kbd)
  (:use (utils edit auto-close)
	(athena athena tm-reverse-hierarchy-graph)
	(generic format-drd)
	(generic generic-edit)
	(text text-edit)))

(kbd-commands
  ("alpha" "Insert α" (kbd-insert "α"))
  ("beta" "Insert β" (kbd-insert "β"))
  ("gamma" "Insert γ" (kbd-insert "γ"))
  ("delta" "Insert δ" (kbd-insert "δ"))
  ("epsilon" "Insert ϵ" (kbd-insert "ϵ"))
  ("zeta" "Insert ζ" (kbd-insert "ζ"))
  ("eta" "Insert η" (kbd-insert "η"))
  ("theta" "Insert θ" (kbd-insert "θ"))
  ("iota" "Insert ι" (kbd-insert "ι"))
  ("kappa" "Insert κ" (kbd-insert "κ"))
  ("lambda" "Insert λ" (kbd-insert "λ"))
  ("mu" "Insert μ" (kbd-insert "μ"))
  ("nu" "Insert ν" (kbd-insert "ν"))
  ("xi" "Insert ξ" (kbd-insert "ξ"))
  ("omicron" "Insert ο" (kbd-insert "ο"))
  ("pi" "Insert π" (kbd-insert "π"))
  ("rho" "Insert ρ" (kbd-insert "ρ"))
  ("sigma" "Insert σ" (kbd-insert "σ"))
  ("tau" "Insert τ" (kbd-insert "τ"))
  ("upsilon" "Insert υ" (kbd-insert "υ"))
  ("phi" "Insert ϕ" (kbd-insert "ϕ"))
  ("chi" "Insert χ" (kbd-insert "χ"))
  ("psi" "Insert ψ" (kbd-insert "ψ"))
  ("omega" "Insert ω" (kbd-insert "ω"))
  ("varepsilon" "Insert ε" (kbd-insert "ε"))
  ("vartheta" "Insert ϑ" (kbd-insert "ϑ"))
  ("varpi" "Insert ϖ" (kbd-insert "ϖ"))
  ("varrho" "Insert ϱ" (kbd-insert "ϱ"))
  ("varsigma" "Insert ς" (kbd-insert "ς"))
  ("varphi" "Insert φ" (kbd-insert "φ"))
  ("leftharpoonup" "Insert ↼" (kbd-insert "↼"))
  ("leftharpoondown" "Insert ↽" (kbd-insert "↽"))
  ("rightharpoonup" "Insert ⇀" (kbd-insert "⇀"))
  ("rightharpoondown" "Insert ⇁" (kbd-insert "⇁"))
  ("lefthook" "Insert lefthook" (insert '(named-symbol "texmacs:lefthook")))
  ("righthook" "Insert righthook" (insert '(named-symbol "texmacs:righthook")))
  ("triangleright" "Insert ▹" (kbd-insert "▹"))
  ("triangleleft" "Insert ◃" (kbd-insert "◃"))
  ("star" "Insert ⋆" (kbd-insert "⋆"))
  ("partial" "Insert ∂" (kbd-insert "∂"))
  ("flat" "Insert ♭" (kbd-insert "♭"))
  ("natural" "Insert ♮" (kbd-insert "♮"))
  ("sharp" "Insert ♯" (kbd-insert "♯"))
  ("smile" "Insert ⌣" (kbd-insert "⌣"))
  ("frown" "Insert ⌢" (kbd-insert "⌢"))
  ("ell" "Insert ℓ" (kbd-insert "ℓ"))
  ("imath" "Insert ı" (kbd-insert "ı"))
  ("jmath" "Insert jmath" (insert '(named-symbol "texmacs:jmath")))
  ("wp" "Insert ℘" (kbd-insert "℘"))
  ("vect" "Insert vect" (insert '(named-symbol "texmacs:vect")))
  ("Alpha" "Insert Α" (kbd-insert "Α"))
  ("Beta" "Insert Β" (kbd-insert "Β"))
  ("Gamma" "Insert Γ" (kbd-insert "Γ"))
  ("Delta" "Insert Δ" (kbd-insert "Δ"))
  ("Epsilon" "Insert Ε" (kbd-insert "Ε"))
  ("Zeta" "Insert Ζ" (kbd-insert "Ζ"))
  ("Eta" "Insert Η" (kbd-insert "Η"))
  ("Theta" "Insert Θ" (kbd-insert "Θ"))
  ("Iota" "Insert Ι" (kbd-insert "Ι"))
  ("Kappa" "Insert Κ" (kbd-insert "Κ"))
  ("Lambda" "Insert Λ" (kbd-insert "Λ"))
  ("Mu" "Insert Μ" (kbd-insert "Μ"))
  ("Nu" "Insert Ν" (kbd-insert "Ν"))
  ("Xi" "Insert Ξ" (kbd-insert "Ξ"))
  ("Omicron" "Insert Ο" (kbd-insert "Ο"))
  ("Pi" "Insert Π" (kbd-insert "Π"))
  ("Rho" "Insert Ρ" (kbd-insert "Ρ"))
  ("Sigma" "Insert Σ" (kbd-insert "Σ"))
  ("Tau" "Insert Τ" (kbd-insert "Τ"))
  ("Upsilon" "Insert Υ" (kbd-insert "Υ"))
  ("Phi" "Insert Φ" (kbd-insert "Φ"))
  ("Chi" "Insert Χ" (kbd-insert "Χ"))
  ("Psi" "Insert Ψ" (kbd-insert "Ψ"))
  ("Omega" "Insert Ω" (kbd-insert "Ω"))
  ("grave" "Insert `" (kbd-insert "`"))
  ("acute" "Insert ´" (kbd-insert "´"))
  ("check" "Insert ˇ" (kbd-insert "ˇ"))
  ("breve" "Insert ˘" (kbd-insert "˘"))
  ("invbreve" "Insert ̑" (kbd-insert "̑"))
  ("bar" "Insert ¯" (kbd-insert "¯"))
  ("cedille" "Insert ¸" (kbd-insert "¸"))
  ("degree" "Insert °" (kbd-insert "°"))
  ("ast" "Insert ∗" (kbd-insert "∗"))
  ("asterisk" "Insert asterisk" (insert '(named-symbol "texmacs:asterisk")))
  ("cdot" "Insert ⋅" (kbd-insert "⋅"))
  ("times" "Insert ×" (kbd-insert "×"))
  ("asterisk" "Insert asterisk" (insert '(named-symbol "texmacs:asterisk")))
  ("div" "Insert ÷" (kbd-insert "÷"))
  ("diamond" "Insert ⋄" (kbd-insert "⋄"))
  ("pm" "Insert ±" (kbd-insert "±"))
  ("mp" "Insert ∓" (kbd-insert "∓"))
  ("oplus" "Insert oplus" (insert '(named-symbol "texmacs:oplus")))
  ("ominus" "Insert ominus" (insert '(named-symbol "texmacs:ominus")))
  ("otimes" "Insert otimes" (insert '(named-symbol "texmacs:otimes")))
  ("oslash" "Insert oslash" (insert '(named-symbol "texmacs:oslash")))
  ("odot" "Insert odot" (insert '(named-symbol "texmacs:odot")))
  ("bigcirc" "Insert bigcirc" (insert '(named-symbol "texmacs:bigcirc")))
  ("circ" "Insert ∘" (kbd-insert "∘"))
  ("bullet" "Insert •" (kbd-insert "•"))
  ("asymp" "Insert ≍" (kbd-insert "≍"))
  ("equiv" "Insert ≡" (kbd-insert "≡"))
  ("subseteq" "Insert ⊆" (kbd-insert "⊆"))
  ("supseteq" "Insert ⊇" (kbd-insert "⊇"))
  ("leq" "Insert ≤" (kbd-insert "≤"))
  ("geq" "Insert ≥" (kbd-insert "≥"))
  ("preceq" "Insert ⪯" (kbd-insert "⪯"))
  ("succeq" "Insert ⪰" (kbd-insert "⪰"))
  ("sim" "Insert ∼" (kbd-insert "∼"))
  ("approx" "Insert ≈" (kbd-insert "≈"))
  ("subset" "Insert ⊂" (kbd-insert "⊂"))
  ("supset" "Insert ⊃" (kbd-insert "⊃"))
  ("ll" "Insert ≪" (kbd-insert "≪"))
  ("gg" "Insert ≫" (kbd-insert "≫"))
  ("prec" "Insert ≺" (kbd-insert "≺"))
  ("succ" "Insert ≻" (kbd-insert "≻"))
  ("leftarrow" "Insert ←" (kbd-insert "←"))
  ("rightarrow" "Insert →" (kbd-insert "→"))
  ("uparrow" "Insert ↑" (kbd-insert "↑"))
  ("downarrow" "Insert ↓" (kbd-insert "↓"))
  ("leftrightarrow" "Insert ↔" (kbd-insert "↔"))
  ("nearrow" "Insert ↗" (kbd-insert "↗"))
  ("searrow" "Insert ↘" (kbd-insert "↘"))
  ("simeq" "Insert ≃" (kbd-insert "≃"))
  ("Leftarrow" "Insert ⇐" (kbd-insert "⇐"))
  ("Rightarrow" "Insert ⇒" (kbd-insert "⇒"))
  ("Uparrow" "Insert ⇑" (kbd-insert "⇑"))
  ("Downarrow" "Insert ⇓" (kbd-insert "⇓"))
  ("Leftrightarrow" "Insert ⇔" (kbd-insert "⇔"))
  ("nwarrow" "Insert ↖" (kbd-insert "↖"))
  ("swarrow" "Insert ↙" (kbd-insert "↙"))
  ("propto" "Insert ∝" (kbd-insert "∝"))
  ("infty" "Insert ∞" (kbd-insert "∞"))
  ("in" "Insert ∈" (kbd-insert "∈"))
  ("ni" "Insert ∋" (kbd-insert "∋"))
  ("mid" "Insert ∣" (kbd-insert "∣"))
  ("bigtriangleup" "Insert △" (kbd-insert "△"))
  ("triangle" "Insert triangle" (insert '(named-symbol "texmacs:triangle")))
  ("bigtriangledown" "Insert ▽" (kbd-insert "▽"))
  ("negate" "Insert negate" (insert '(named-symbol "texmacs:negate")))
  ("varshortmid" "Insert varshortmid" (insert '(named-symbol "texmacs:varshortmid")))
  ("forall" "Insert ∀" (kbd-insert "∀"))
  ("exists" "Insert ∃" (kbd-insert "∃"))
  ("neg" "Insert ¬" (kbd-insert "¬"))
  ("emptyset" "Insert ∅" (kbd-insert "∅"))
  ("Re" "Insert Re" (insert '(named-symbol "texmacs:Re")))
  ("Im" "Insert Im" (insert '(named-symbol "texmacs:Im")))
  ("top" "Insert ⊤" (kbd-insert "⊤"))
  ("bot" "Insert ⊥" (kbd-insert "⊥"))
  ("aleph" "Insert ℵ" (kbd-insert "ℵ"))
  ("perp" "Insert perp" (insert '(named-symbol "texmacs:perp")))
  ("cup" "Insert ∪" (kbd-insert "∪"))
  ("cap" "Insert ∩" (kbd-insert "∩"))
  ("uplus" "Insert ⊎" (kbd-insert "⊎"))
  ("wedge" "Insert ∧" (kbd-insert "∧"))
  ("vee" "Insert ∨" (kbd-insert "∨"))
  ("vdash" "Insert ⊢" (kbd-insert "⊢"))
  ("dashv" "Insert ⊣" (kbd-insert "⊣"))
  ("lfloor" "Insert ⌊" (kbd-insert "⌊"))
  ("rfloor" "Insert ⌋" (kbd-insert "⌋"))
  ("lceil" "Insert ⌈" (kbd-insert "⌈"))
  ("rceil" "Insert ⌉" (kbd-insert "⌉"))
  ("langle" "Insert ⟨" (kbd-insert "⟨"))
  ("rangle" "Insert ⟩" (kbd-insert "⟩"))
  ("updownarrow" "Insert ↕" (kbd-insert "↕"))
  ("Updownarrow" "Insert ⇕" (kbd-insert "⇕"))
  ("wr" "Insert ≀" (kbd-insert "≀"))
  ("amalg" "Insert ⨿" (kbd-insert "⨿"))
  ("nabla" "Insert ∇" (kbd-insert "∇"))
  ("sqcup" "Insert ⊔" (kbd-insert "⊔"))
  ("sqcap" "Insert ⊓" (kbd-insert "⊓"))
  ("sqsubseteq" "Insert ⊑" (kbd-insert "⊑"))
  ("sqsupseteq" "Insert ⊒" (kbd-insert "⊒"))
  ("dag" "Insert dag" (insert '(named-symbol "texmacs:dag")))
  ("ddag" "Insert ddag" (insert '(named-symbol "texmacs:ddag")))
  ("endofline" "Insert endofline" (insert '(named-symbol "texmacs:endofline")))
  ("clubsuit" "Insert ♣" (kbd-insert "♣"))
  ("diamondsuit" "Insert ♦" (kbd-insert "♦"))
  ("heartsuit" "Insert ♥" (kbd-insert "♥"))
  ("spadesuit" "Insert ♠" (kbd-insert "♠"))
  ("backslash" "Insert \\" (kbd-insert "\\"))
  ("setminus" "Insert ∖" (kbd-insert "∖"))
  ("boxdot" "Insert ⊡" (kbd-insert "⊡"))
  ("boxplus" "Insert ⊞" (kbd-insert "⊞"))
  ("boxtimes" "Insert ⊠" (kbd-insert "⊠"))
  ("box" "Insert box" (insert '(named-symbol "texmacs:box")))
  ("blacksquare" "Insert ■" (kbd-insert "■"))
  ("centerdot" "Insert ·" (kbd-insert "·"))
  ("lozenge" "Insert ◊" (kbd-insert "◊"))
  ("blacklozenge" "Insert ⧫" (kbd-insert "⧫"))
  ("circlearrowright" "Insert ↻" (kbd-insert "↻"))
  ("circlearrowleft" "Insert ↺" (kbd-insert "↺"))
  ("rightleftharpoons" "Insert ⇌" (kbd-insert "⇌"))
  ("leftrightharpoons" "Insert ⇋" (kbd-insert "⇋"))
  ("boxminus" "Insert ⊟" (kbd-insert "⊟"))
  ("Vdash" "Insert ⊩" (kbd-insert "⊩"))
  ("Vvdash" "Insert ⊪" (kbd-insert "⊪"))
  ("dashV" "Insert dashV" (insert '(named-symbol "texmacs:dashV")))
  ("twoheadrightarrow" "Insert ↠" (kbd-insert "↠"))
  ("twoheadleftarrow" "Insert ↞" (kbd-insert "↞"))
  ("leftleftarrows" "Insert ⇇" (kbd-insert "⇇"))
  ("rightrightarrows" "Insert ⇉" (kbd-insert "⇉"))
  ("upuparrows" "Insert ⇈" (kbd-insert "⇈"))
  ("downdownarrows" "Insert ⇊" (kbd-insert "⇊"))
  ("upharpoonright" "Insert ↾" (kbd-insert "↾"))
  ("downharpoonright" "Insert ⇂" (kbd-insert "⇂"))
  ("upharpoonleft" "Insert ↿" (kbd-insert "↿"))
  ("downharpoonleft" "Insert ⇃" (kbd-insert "⇃"))
  ("rightarrowtail" "Insert ↣" (kbd-insert "↣"))
  ("leftarrowtail" "Insert ↢" (kbd-insert "↢"))
  ("leftrightarrows" "Insert ⇆" (kbd-insert "⇆"))
  ("rightleftarrows" "Insert ⇄" (kbd-insert "⇄"))
  ("Lsh" "Insert ↰" (kbd-insert "↰"))
  ("Rsh" "Insert ↱" (kbd-insert "↱"))
  ("rightsquigarrow" "Insert ↝" (kbd-insert "↝"))
  ("leftrightsquigarrow" "Insert ↭" (kbd-insert "↭"))
  ("looparrowleft" "Insert ↫" (kbd-insert "↫"))
  ("looparrowright" "Insert ↬" (kbd-insert "↬"))
  ("circeq" "Insert ≗" (kbd-insert "≗"))
  ("succsim" "Insert ≿" (kbd-insert "≿"))
  ("gtrsim" "Insert ≳" (kbd-insert "≳"))
  ("gtrapprox" "Insert ⪆" (kbd-insert "⪆"))
  ("multimap" "Insert ⊸" (kbd-insert "⊸"))
  ("therefore" "Insert ∴" (kbd-insert "∴"))
  ("because" "Insert ∵" (kbd-insert "∵"))
  ("doteqdot" "Insert ≑" (kbd-insert "≑"))
  ("triangleq" "Insert ≜" (kbd-insert "≜"))
  ("precsim" "Insert ≾" (kbd-insert "≾"))
  ("lesssim" "Insert ≲" (kbd-insert "≲"))
  ("lessapprox" "Insert ⪅" (kbd-insert "⪅"))
  ("eqslantless" "Insert ⪕" (kbd-insert "⪕"))
  ("eqslantgtr" "Insert ⪖" (kbd-insert "⪖"))
  ("curlyeqprec" "Insert ⋞" (kbd-insert "⋞"))
  ("curlyeqsucc" "Insert ⋟" (kbd-insert "⋟"))
  ("preccurlyeq" "Insert ≼" (kbd-insert "≼"))
  ("leqq" "Insert ≦" (kbd-insert "≦"))
  ("leqslant" "Insert ⩽" (kbd-insert "⩽"))
  ("lessgtr" "Insert ≶" (kbd-insert "≶"))
  ("smalldash" "Insert smalldash" (insert '(named-symbol "texmacs:smalldash")))
  ("risingdotseq" "Insert risingdotseq" (insert '(named-symbol "texmacs:risingdotseq")))
  ("fallingdotseq" "Insert fallingdotseq" (insert '(named-symbol "texmacs:fallingdotseq")))
  ("succcurlyeq" "Insert ≽" (kbd-insert "≽"))
  ("geqq" "Insert ≧" (kbd-insert "≧"))
  ("geqslant" "Insert ⩾" (kbd-insert "⩾"))
  ("gtrless" "Insert ≷" (kbd-insert "≷"))
  ("sqsubset" "Insert ⊏" (kbd-insert "⊏"))
  ("sqsupset" "Insert ⊐" (kbd-insert "⊐"))
  ("vartriangleright" "Insert ⊳" (kbd-insert "⊳"))
  ("vartriangleleft" "Insert ⊲" (kbd-insert "⊲"))
  ("trianglerighteq" "Insert ⊵" (kbd-insert "⊵"))
  ("trianglelefteq" "Insert ⊴" (kbd-insert "⊴"))
  ("bigstar" "Insert ★" (kbd-insert "★"))
  ("between" "Insert ≬" (kbd-insert "≬"))
  ("blacktriangledown" "Insert ▾" (kbd-insert "▾"))
  ("blacktriangleright" "Insert ▸" (kbd-insert "▸"))
  ("blacktriangleleft" "Insert ◂" (kbd-insert "◂"))
  ("shortrightarrow" "Insert shortrightarrow" (insert '(named-symbol "texmacs:shortrightarrow")))
  ("shortleftarrow" "Insert shortleftarrow" (insert '(named-symbol "texmacs:shortleftarrow")))
  ("vartriangle" "Insert ▵" (kbd-insert "▵"))
  ("blacktriangle" "Insert ▴" (kbd-insert "▴"))
  ("triangledown" "Insert ▿" (kbd-insert "▿"))
  ("eqcirc" "Insert ≖" (kbd-insert "≖"))
  ("lesseqgtr" "Insert ⋚" (kbd-insert "⋚"))
  ("gtreqless" "Insert ⋛" (kbd-insert "⋛"))
  ("lesseqqgtr" "Insert ⪋" (kbd-insert "⪋"))
  ("gtreqqless" "Insert ⪌" (kbd-insert "⪌"))
  ("yen" "Insert ¥" (kbd-insert "¥"))
  ("Rrightarrow" "Insert ⇛" (kbd-insert "⇛"))
  ("Lleftarrow" "Insert ⇚" (kbd-insert "⇚"))
  ("checkmark" "Insert ✓" (kbd-insert "✓"))
  ("veebar" "Insert ⊻" (kbd-insert "⊻"))
  ("barwedge" "Insert ⌅" (kbd-insert "⌅"))
  ("doublebarwedge" "Insert ⌆" (kbd-insert "⌆"))
  ("angle" "Insert ∠" (kbd-insert "∠"))
  ("measuredangle" "Insert ∡" (kbd-insert "∡"))
  ("sphericalangle" "Insert ∢" (kbd-insert "∢"))
  ("varpropto" "Insert varpropto" (insert '(named-symbol "texmacs:varpropto")))
  ("smallsmile" "Insert smallsmile" (insert '(named-symbol "texmacs:smallsmile")))
  ("smallfrown" "Insert smallfrown" (insert '(named-symbol "texmacs:smallfrown")))
  ("Subset" "Insert ⋐" (kbd-insert "⋐"))
  ("Supset" "Insert ⋑" (kbd-insert "⋑"))
  ("Cup" "Insert ⋓" (kbd-insert "⋓"))
  ("Cap" "Insert ⋒" (kbd-insert "⋒"))
  ("curlyvee" "Insert ⋎" (kbd-insert "⋎"))
  ("curlywedge" "Insert ⋏" (kbd-insert "⋏"))
  ("leftthreetimes" "Insert ⋋" (kbd-insert "⋋"))
  ("rightthreetimes" "Insert ⋌" (kbd-insert "⋌"))
  ("subseteqq" "Insert ⫅" (kbd-insert "⫅"))
  ("supseteqq" "Insert ⫆" (kbd-insert "⫆"))
  ("bumpeq" "Insert ≏" (kbd-insert "≏"))
  ("Bumpeq" "Insert ≎" (kbd-insert "≎"))
  ("lll" "Insert ⋘" (kbd-insert "⋘"))
  ("ggg" "Insert ⋙" (kbd-insert "⋙"))
  ("ulcorner" "Insert ⌜" (kbd-insert "⌜"))
  ("urcorner" "Insert ⌝" (kbd-insert "⌝"))
  ("circledR" "Insert ®" (kbd-insert "®"))
  ("circledS" "Insert Ⓢ" (kbd-insert "Ⓢ"))
  ("pitchfork" "Insert ⋔" (kbd-insert "⋔"))
  ("dotplus" "Insert ∔" (kbd-insert "∔"))
  ("backsim" "Insert ∽" (kbd-insert "∽"))
  ("backsimeq" "Insert ⋍" (kbd-insert "⋍"))
  ("llcorner" "Insert ⌞" (kbd-insert "⌞"))
  ("lrcorner" "Insert ⌟" (kbd-insert "⌟"))
  ("maltese" "Insert ✠" (kbd-insert "✠"))
  ("complement" "Insert ∁" (kbd-insert "∁"))
  ("intercal" "Insert ⊺" (kbd-insert "⊺"))
  ("circledcirc" "Insert circledcirc" (insert '(named-symbol "texmacs:circledcirc")))
  ("circledast" "Insert circledast" (insert '(named-symbol "texmacs:circledast")))
  ("circleddash" "Insert ⊝" (kbd-insert "⊝"))
  ("lvertneqq" "Insert lvertneqq" (insert '(named-symbol "texmacs:lvertneqq")))
  ("gvertneqq" "Insert gvertneqq" (insert '(named-symbol "texmacs:gvertneqq")))
  ("nleq" "Insert ≰" (kbd-insert "≰"))
  ("ngeq" "Insert ≱" (kbd-insert "≱"))
  ("nless" "Insert ≮" (kbd-insert "≮"))
  ("ngtr" "Insert ≯" (kbd-insert "≯"))
  ("nprec" "Insert ⊀" (kbd-insert "⊀"))
  ("nsucc" "Insert ⊁" (kbd-insert "⊁"))
  ("lneqq" "Insert ≨" (kbd-insert "≨"))
  ("gneqq" "Insert ≩" (kbd-insert "≩"))
  ("nleqslant" "Insert nleqslant" (insert '(named-symbol "texmacs:nleqslant")))
  ("ngeqslant" "Insert ngeqslant" (insert '(named-symbol "texmacs:ngeqslant")))
  ("lneq" "Insert ⪇" (kbd-insert "⪇"))
  ("gneq" "Insert ⪈" (kbd-insert "⪈"))
  ("npreceq" "Insert npreceq" (insert '(named-symbol "texmacs:npreceq")))
  ("nsucceq" "Insert nsucceq" (insert '(named-symbol "texmacs:nsucceq")))
  ("precnsim" "Insert ⋨" (kbd-insert "⋨"))
  ("succnsim" "Insert ⋩" (kbd-insert "⋩"))
  ("lnsim" "Insert ⋦" (kbd-insert "⋦"))
  ("gnsim" "Insert ⋧" (kbd-insert "⋧"))
  ("nleqq" "Insert nleqq" (insert '(named-symbol "texmacs:nleqq")))
  ("ngeqq" "Insert ngeqq" (insert '(named-symbol "texmacs:ngeqq")))
  ("precneqq" "Insert ⪵" (kbd-insert "⪵"))
  ("succneqq" "Insert ⪶" (kbd-insert "⪶"))
  ("precnapprox" "Insert ⪹" (kbd-insert "⪹"))
  ("succnapprox" "Insert ⪺" (kbd-insert "⪺"))
  ("lnapprox" "Insert ⪉" (kbd-insert "⪉"))
  ("gnapprox" "Insert ⪊" (kbd-insert "⪊"))
  ("nsim" "Insert ≁" (kbd-insert "≁"))
  ("ncong" "Insert ≇" (kbd-insert "≇"))
  ("diagup" "Insert diagup" (insert '(named-symbol "texmacs:diagup")))
  ("diagdown" "Insert diagdown" (insert '(named-symbol "texmacs:diagdown")))
  ("varsubsetneq" "Insert varsubsetneq" (insert '(named-symbol "texmacs:varsubsetneq")))
  ("varsupsetneq" "Insert varsupsetneq" (insert '(named-symbol "texmacs:varsupsetneq")))
  ("nsubseteqq" "Insert nsubseteqq" (insert '(named-symbol "texmacs:nsubseteqq")))
  ("nsupseteqq" "Insert nsupseteqq" (insert '(named-symbol "texmacs:nsupseteqq")))
  ("subsetneqq" "Insert ⫋" (kbd-insert "⫋"))
  ("supsetneqq" "Insert ⫌" (kbd-insert "⫌"))
  ("varsubsetneqq" "Insert varsubsetneqq" (insert '(named-symbol "texmacs:varsubsetneqq")))
  ("varsupsetneqq" "Insert varsupsetneqq" (insert '(named-symbol "texmacs:varsupsetneqq")))
  ("subsetneq" "Insert ⊊" (kbd-insert "⊊"))
  ("supsetneq" "Insert ⊋" (kbd-insert "⊋"))
  ("nsubseteq" "Insert ⊈" (kbd-insert "⊈"))
  ("nsupseteq" "Insert ⊉" (kbd-insert "⊉"))
  ("parallel" "Insert ∥" (kbd-insert "∥"))
  ("nparallel" "Insert ∦" (kbd-insert "∦"))
  ("nmid" "Insert ∤" (kbd-insert "∤"))
  ("nshortmid" "Insert nshortmid" (insert '(named-symbol "texmacs:nshortmid")))
  ("nshortparallel" "Insert nshortparallel" (insert '(named-symbol "texmacs:nshortparallel")))
  ("nvdash" "Insert ⊬" (kbd-insert "⊬"))
  ("nVdash" "Insert ⊮" (kbd-insert "⊮"))
  ("nvDash" "Insert ⊭" (kbd-insert "⊭"))
  ("nVDash" "Insert ⊯" (kbd-insert "⊯"))
  ("models" "Insert ⊧" (kbd-insert "⊧"))
  ("ntrianglerighteq" "Insert ⋭" (kbd-insert "⋭"))
  ("ntrianglelefteq" "Insert ⋬" (kbd-insert "⋬"))
  ("ntriangleleft" "Insert ⋪" (kbd-insert "⋪"))
  ("ntriangleright" "Insert ⋫" (kbd-insert "⋫"))
  ("nleftarrow" "Insert ↚" (kbd-insert "↚"))
  ("nrightarrow" "Insert ↛" (kbd-insert "↛"))
  ("nLeftarrow" "Insert ⇍" (kbd-insert "⇍"))
  ("nRightarrow" "Insert ⇏" (kbd-insert "⇏"))
  ("nLeftrightarrow" "Insert ⇎" (kbd-insert "⇎"))
  ("nleftrightarrow" "Insert ↮" (kbd-insert "↮"))
  ("divideontimes" "Insert ⋇" (kbd-insert "⋇"))
  ("varnothing" "Insert varnothing" (insert '(named-symbol "texmacs:varnothing")))
  ("nexists" "Insert ∄" (kbd-insert "∄"))
  ("Mho" "Insert ℧" (kbd-insert "℧"))
  ("thorn" "Insert þ" (kbd-insert "þ"))
  ("eth" "Insert eth" (insert '(named-symbol "texmacs:eth")))
  ("eqsim" "Insert ≂" (kbd-insert "≂"))
  ("beth" "Insert ℶ" (kbd-insert "ℶ"))
  ("gimel" "Insert ℷ" (kbd-insert "ℷ"))
  ("daleth" "Insert ℸ" (kbd-insert "ℸ"))
  ("lessdot" "Insert ⋖" (kbd-insert "⋖"))
  ("gtrdot" "Insert ⋗" (kbd-insert "⋗"))
  ("ltimes" "Insert ⋉" (kbd-insert "⋉"))
  ("rtimes" "Insert ⋊" (kbd-insert "⋊"))
  ("shortmid" "Insert shortmid" (insert '(named-symbol "texmacs:shortmid")))
  ("shortparallel" "Insert shortparallel" (insert '(named-symbol "texmacs:shortparallel")))
  ("smallsetminus" "Insert smallsetminus" (insert '(named-symbol "texmacs:smallsetminus")))
  ("thicksim" "Insert thicksim" (insert '(named-symbol "texmacs:thicksim")))
  ("thickapprox" "Insert thickapprox" (insert '(named-symbol "texmacs:thickapprox")))
  ("approxeq" "Insert ≊" (kbd-insert "≊"))
  ("succapprox" "Insert ⪸" (kbd-insert "⪸"))
  ("precapprox" "Insert ⪷" (kbd-insert "⪷"))
  ("curvearrowleft" "Insert ↶" (kbd-insert "↶"))
  ("curvearrowright" "Insert ↷" (kbd-insert "↷"))
  ("digamma" "Insert ϝ" (kbd-insert "ϝ"))
  ("varkappa" "Insert ϰ" (kbd-insert "ϰ"))
  ("hslash" "Insert ℏ" (kbd-insert "ℏ"))
  ("hbar" "Insert hbar" (insert '(named-symbol "texmacs:hbar")))
  ("backepsilon" "Insert ϶" (kbd-insert "϶"))
  ("mapsto" "Insert ↦" (kbd-insert "↦"))
  ("longmapsto" "Insert ⟼" (kbd-insert "⟼"))
  ("longrightarrow" "Insert ⟶" (kbd-insert "⟶"))
  ("longleftarrow" "Insert ⟵" (kbd-insert "⟵"))
  ("longleftrightarrow" "Insert ⟷" (kbd-insert "⟷"))
  ("longRightarrow" "Insert longRightarrow" (insert '(named-symbol "texmacs:longRightarrow")))
  ("longLeftarrow" "Insert longLeftarrow" (insert '(named-symbol "texmacs:longLeftarrow")))
  ("longLeftrightarrow" "Insert longLeftrightarrow" (insert '(named-symbol "texmacs:longLeftrightarrow")))
  ("ldots" "Insert …" (kbd-insert "…"))
  ("cdots" "Insert ⋯" (kbd-insert "⋯"))
  ("vdots" "Insert ⋮" (kbd-insert "⋮"))
  ("ddots" "Insert ⋱" (kbd-insert "⋱"))
  ("dotamalg" "Insert dotamalg" (insert '(named-symbol "texmacs:dotamalg")))
  ("dottimes" "Insert dottimes" (insert '(named-symbol "texmacs:dottimes")))
  ("dotoplus" "Insert dotoplus" (insert '(named-symbol "texmacs:dotoplus")))
  ("dototimes" "Insert dototimes" (insert '(named-symbol "texmacs:dototimes")))
  ("venus" "Insert venus" (insert '(named-symbol "texmacs:venus")))
  ("mars" "Insert mars" (insert '(named-symbol "texmacs:mars")))
  ("earth" "Insert ♁" (kbd-insert "♁"))
  ("aries" "Insert ♈" (kbd-insert "♈"))
  ("fullmoon" "Insert fullmoon" (insert '(named-symbol "texmacs:fullmoon")))
  ("newmoon" "Insert newmoon" (insert '(named-symbol "texmacs:newmoon")))
  ("astrosun" "Insert ☉" (kbd-insert "☉"))
  ("leo" "Insert ♌" (kbd-insert "♌"))
  ("LEFTcircle" "Insert ◐" (kbd-insert "◐"))
  ("RIGHTcircle" "Insert ◑" (kbd-insert "◑"))
  ("Square" "Insert □" (kbd-insert "□"))
  ("CheckedBox" "Insert ☒" (kbd-insert "☒"))
  ("photon" "Insert photon" (insert '(named-symbol "texmacs:photon")))
  ("gluon" "Insert gluon" (insert '(named-symbol "texmacs:gluon")))
  ("neq" "Insert ≠" (kbd-insert "≠"))
  ("notin" "Insert notin" (insert '(named-symbol "texmacs:notin")))
  ("nin" "Insert ∉" (kbd-insert "∉"))
  ("notni" "Insert notni" (insert '(named-symbol "texmacs:notni")))
  ("nni" "Insert ∌" (kbd-insert "∌"))
  ("nll" "Insert nll" (insert '(named-symbol "texmacs:nll")))
  ("nlll" "Insert nlll" (insert '(named-symbol "texmacs:nlll")))
  ("ngg" "Insert ngg" (insert '(named-symbol "texmacs:ngg")))
  ("nggg" "Insert nggg" (insert '(named-symbol "texmacs:nggg")))
  ("dagger" "Insert †" (kbd-insert "†"))
  ("ddagger" "Insert ‡" (kbd-insert "‡"))
  ("boxbar" "Insert boxbar" (insert '(named-symbol "texmacs:boxbar")))
  ("checked" "Insert checked" (insert '(named-symbol "texmacs:checked")))
  ("obar" "Insert obar" (insert '(named-symbol "texmacs:obar")))
  ("kreuz" "Insert kreuz" (insert '(named-symbol "texmacs:kreuz"))))

(kbd-commands
  ("lhd" "Insert left normal subgroup relation" (insert "⊲"))
  ("rhd" "Insert right normal subgroup relation" (insert "⊳"))
  ("unlhd" "Insert left normal subgroup or equal relation"
   (insert "⊴"))
  ("unrhd" "Insert right normal subgroup or equal relation"
   (insert "⊵"))
  ("cd" "Insert a commutative diagram" (make-cd))
  ("#" "Insert sharp" (insert "#"))
  ("$" "Insert dollar" (insert "$"))
  ("(" "Insert formula" (make-with "mode" "math"))
  ("," "Insert small horizontal space" (make-space "0.2spc"))
  (":" "Insert medium horizontal space" (make-space "0.4spc"))
  (";" "Insert thick horizontal space" (make-space "0.6spc"))
  (" " "Insert horizontal interword space" (make-space "1spc"))
  ("!" "Insert negative horizontal space" (make-space "-0.2spc"))
  ("|" "Insert norm" (insert "‖"))
  ("quad" "Insert a quad space" (make-space "1em"))
  ("qquad" "Insert a qquad space" (make-space "2em"))
  ("\\" "Go to the next line" (make 'next-line))

  ("[" "Insert equation" (make-equation*))
  ("equation" "Insert numbered equation" (make-equation))
  ("eqnarray" "Insert equation array" (make-eqnarray))
  ("eqnarray*" "Insert equation array" (make-eqnarray*))

  ("cC" "Make Ç" (emulate-keyboard "cedilla C"))
  ("cc" "Make ç" (emulate-keyboard "cedilla c"))
  ("'E" "Insert É" (emulate-keyboard "acute E"))
  ("'e" "Insert é" (emulate-keyboard "acute e"))
  ("`A" "Insert À" (emulate-keyboard "grave A"))
  ("`E" "Insert È" (emulate-keyboard "grave E"))
  ("`U" "Insert Ù" (emulate-keyboard "grave U"))
  ("`a" "Insert à" (emulate-keyboard "grave a"))
  ("`e" "Insert è" (emulate-keyboard "grave e"))
  ("`u" "Insert ù" (emulate-keyboard "grave u"))
  ("^A" "Insert Â" (emulate-keyboard "hat A"))
  ("^E" "Insert Ê" (emulate-keyboard "hat E"))
  ("^I" "Insert Î" (emulate-keyboard "hat I"))
  ("^O" "Insert Ô" (emulate-keyboard "hat O"))
  ("^U" "Insert Û" (emulate-keyboard "hat U"))
  ("^a" "Insert â" (emulate-keyboard "hat a"))
  ("^e" "Insert ê" (emulate-keyboard "hat e"))
  ("^i" "Insert î" (emulate-keyboard "hat i"))
  ("^o" "Insert ô" (emulate-keyboard "hat o"))
  ("^u" "Insert û" (emulate-keyboard "hat u"))
  ("S" "Make " (emulate-keyboard "S-F5 p"))
  ("aa" "Insert å" (insert "å"))
  ("ae" "Insert ae" (emulate-keyboard "S-F5 a"))
  ("dh" "Insert Ã°" (insert "ð"))
  ("dj" "Insert <#0111>" (insert "đ"))
  ("i" "Insert " (insert ""))
  ("j" "Insert <#0237>" (insert "ȷ"))
  ("l" "Insert <#0142>" (insert "ł"))
  ("ng" "Insert <#014B>" (insert "ŋ"))
  ("o" "Insert <#00F8>" (insert "ø"))
  ("oe" "Insert oe" (emulate-keyboard "S-F5 o e"))
  ("ss" "Insert ÿ" (emulate-keyboard "S-F5 s"))
  ("sz" "Insert ÿ" (emulate-keyboard "S-F5 s"))
  ("th" "Insert <#00FE>" (insert "þ"))
  ("AA" "Insert Å" (insert "Å"))
  ("AE" "Insert AE" (emulate-keyboard "S-F5 A"))
  ("DH" "Insert Ã" (insert "Ð"))
  ("L" "Insert <#0141>" (insert "Ł"))
  ("NG" "Insert <#014A>" (insert "Ŋ"))
  ("O" "Insert <#00D8>" (insert "Ø"))
  ("OE" "Insert OE" (emulate-keyboard "S-F5 O E"))
  ("S" "Insert <#00A7>" (insert "§"))
  ("SS" "Insert SS" (emulate-keyboard "S-F5 S"))
  ("TH" "Insert <#00DE>" (insert "Þ"))

  ("arccos" "Insert arccos" (insert "arccos"))
  ("arcsin" "Insert arcsin" (insert "arcsin"))
  ("arctan" "Insert arctan" (insert "arctan"))
  ("arg" "Insert arg" (insert "arg"))
  ("cos" "Insert cos" (insert "cos"))
  ("cosh" "Insert cosh" (insert "cosh"))
  ("cot" "Insert cot" (insert "cot"))
  ("coth" "Insert coth" (insert "coth"))
  ("csc" "Insert csc" (insert "csc"))
  ("deg" "Insert deg" (insert "deg"))
  ("det" "Insert det" (insert "det"))
  ("dim" "Insert dim" (insert "dim"))
  ("exp" "Insert exp" (insert "exp"))
  ("gcd" "Insert gcd" (insert "gcd"))
  ("hom" "Insert hom" (insert "hom"))
  ("inf" "Insert inf" (insert "inf"))
  ("ker" "Insert ker" (insert "ker"))
  ("lg" "Insert lg" (insert "lg"))
  ("lim" "Insert lim" (insert "lim"))
  ("liminf" "Insert liminf" (insert "liminf"))
  ("limsup" "Insert limsup" (insert "limsup"))
  ("ln" "Insert ln" (insert "ln"))
  ("log" "Insert log" (insert "log"))
  ("max" "Insert max" (insert "max"))
  ("min" "Insert min" (insert "min"))
  ("Pr" "Insert Pr" (insert "Pr"))
  ("sec" "Insert sec" (insert "sec"))
  ("sin" "Insert sin" (insert "sin"))
  ("sinh" "Insert sinh" (insert "sinh"))
  ("sup" "Insert sup" (insert "sup"))
  ("tan" "Insert tan" (insert "tan"))
  ("tanh" "Insert tanh" (insert "tanh"))

  ("abstract"  "Insert abstract" (make-abstract-data))
  ("maketitle" "Insert title"    (make-doc-data))
  ("tableofcontents" "Insert table of contents"
   (make-aux "table-of-contents" "toc-prefix" "toc"))
  ("appendix" "Insert appendix" (make-section 'appendix))
  ("chapter" "Insert chapter" (make-section 'chapter))
  ("section" "Insert section" (make-section 'section))
  ("subsection" "Insert subsection" (make-section 'subsection))
  ("subsubsection" "Insert subsubsection" (make-section 'subsubsection))
  ("paragraph" "Insert paragraph" (make-section 'paragraph))
  ("subparagraph" "Insert subparagraph" (make-section 'subparagraph))
  ("table" "Insert a big table" (make 'big-table))
  ("figure" "Insert a big figure" (make 'big-figure))
  ("graph-rev-hierarchy" "Insert reverse hierarchy graph"
   (insert-reverse-hierarchy-graph))

  ("def" "Insert definition" (make 'definition))
  ("rem" "Insert remark" (make 'remark))
  ("cau" "Insert caution" (make 'warning))
  ("cor" "Insert corollary" (make 'corollary))
  ("prop" "Insert proposition" (make 'proposition))
  ("thm" "Insert theorem" (make 'theorem))
  ("lem" "Insert lemma" (make 'lemma))
  ("eg" "Insert example" (make 'example))
  ("sln" "Insert unnumbered solution" (make 'solution*))
  ("pf" "Insert proof" (make 'proof))
  ("alt" "Insert alternative proof" (make 'proof-alternative))
  ("conj" "Insert conjecture" (make 'conjecture))
  ("qsn" "Insert question" (make 'question))
  ("ax" "Insert axiom" (make 'axiom))
  ("disam" "Insert disambiguation" (make 'disambiguation))

  ("frac" "Make fraction" (make-fraction))
  ("sqrt" "Make square root" (make-sqrt))
  ("not" "Make negation" (make-neg))
  ("acute" "Make acute" (make-wide "́"))
  ("bar" "Make bar" (make-wide "̅"))
  ("breve" "Make breve" (make-wide "̆"))
  ("invbreve" "Make inverted breve" (make-wide "̑"))
  ("check" "Make check" (make-wide "̌"))
  ("grave" "Make grave" (make-wide "̀"))
  ("hat" "Make hat" (make-wide "̂"))
  ("tilde" "Make tilde" (make-wide "̃"))
  ("vect" "Make vector" (make-wide "⃗"))
  ("dot" "Make dot" (make-wide "̇"))
  ("ddot" "Make double dot" (make-wide "̈"))
  ("dddot" "Make triple dot" (make-wide "⃛"))
  ("ddddot" "Make quadruple dot" (make-wide "⃜"))
  ("widecheck" "Make check" (make-wide "̌"))
  ("widehat" "Make hat" (make-wide "̂"))
  ("widetilde" "Make tilde" (make-wide-stretched "̃"))

  ("sum" "Insert big summation" (math-big-operator "sum"))
  ("prod" "Insert big product" (math-big-operator "prod"))
  ("coprod" "Insert big coproduct" (math-big-operator "amalg"))
  ("int" "Insert big integral" (math-big-operator "int"))
  ("fint" "Insert finite part integral" (math-big-operator "fint"))
  ("iint" "Insert big integrals" (math-big-operator "iint"))
  ("iiint" "Insert big integrals" (math-big-operator "iiint"))
  ("oint" "Insert big contour integral" (math-big-operator "oint"))
  ("oiint" "Insert big contour integrals" (math-big-operator "oiint"))
  ("oiiint" "Insert big contour integrals" (math-big-operator "oiiint"))
  ("bigcap" "Insert big intersection" (math-big-operator "cap"))
  ("bigcup" "Insert big union" (math-big-operator "cup"))
  ("bigsqcup" "Insert big square union" (math-big-operator "sqcup"))
  ("bigvee" "Insert big logical or" (math-big-operator "vee"))
  ("bigwedge" "Insert big logical and" (math-big-operator "wedge"))
  ("bigodot" "Insert big dotted point" (math-big-operator "odot"))
  ("bigotimes" "Insert big tensor product" (math-big-operator "otimes"))
  ("bigoplus" "Insert big direct sum" (math-big-operator "oplus"))
  ("biguplus" "Insert big union sum" (math-big-operator "uplus"))

  ("left(" "Insert large (" (math-bracket-open "(" ")" #t))
  ("left)" "Insert large left )" (math-bracket-open ")" "(" #t))
  ("left[" "Insert large [" (math-bracket-open "[" "]" #t))
  ("left]" "Insert large left ]" (math-bracket-open "]" "[" #t))
  ("left\\{" "Insert large {" (math-bracket-open "{" "}" #t))
  ("left\\}" "Insert large left }" (math-bracket-open "}" "{" #t))
  ("left\\lfloor" "Insert large <lfloor>"
   (math-bracket-open "⌊" "⌋" #t))
  ("left\\rfloor" "Insert large left <rfloor>"
   (math-bracket-open "⌋" "⌊" #t))
  ("left\\lceil" "Insert large <lceil>"
   (math-bracket-open "⌈" "⌉" #t))
  ("left\\rceil" "Insert large left <rceil>"
   (math-bracket-open "⌉" "⌈" #t))
  ("left\\langle" "Insert large <langle>"
   (math-bracket-open "⟨" "⟩" #t))
  ("left\\rangle" "Insert large left <rangle>"
   (math-bracket-open "⟩" "⟨" #t))
  ("left|" "Insert large left <mid>" (math-bracket-open "|" "|" #t))
  ("left||" "Insert large left <parallel>" (math-bracket-open "||" "||" #t))
  ("left/" "Insert large left /" (math-bracket-open "/" "\\" #t))
  ("left\\" "Insert large left \\" (math-bracket-open "\\" "/" #t))
  ("left." "Insert large left ." (math-bracket-open "." "." #t))

  ("right(" "Insert large right (" (math-bracket-close "(" ")" #t))
  ("right)" "Insert large )" (math-bracket-close ")" "(" #t))
  ("right[" "Insert large right [" (math-bracket-close "[" "]" #t))
  ("right]" "Insert large ]" (math-bracket-close "]" "[" #t))
  ("right\\{" "Insert large right {" (math-bracket-close "{" "}" #t))
  ("right\\}" "Insert large }" (math-bracket-close "}" "{" #t))
  ("right\\lfloor" "Insert large right <lfloor>"
   (math-bracket-close "⌊" "⌋" #t))
  ("right\\rfloor" "Insert large <rfloor>"
   (math-bracket-close "⌋" "⌊" #t))
  ("right\\lceil" "Insert large right <lceil>"
   (math-bracket-close "⌈" "⌉" #t))
  ("right\\rceil" "Insert large <rceil>"
   (math-bracket-close "⌉" "⌈" #t))
  ("right\\langle" "Insert large right <langle>"
   (math-bracket-close "⟨" "⟩" #t))
  ("right\\rangle" "Insert large <rangle>"
   (math-bracket-close "⟩" "⟨" #t))
  ("right|" "Insert large right <mid>" (math-bracket-close "|" "|" #t))
  ("right||" "Insert large right <parallel>" (math-bracket-close "||" "||" #t))
  ("right/" "Insert large right /" (math-bracket-close "/" "\\" #t))
  ("right\\" "Insert large right \\" (math-bracket-close "\\" "/" #t))
  ("right." "Insert large right ." (math-bracket-close "." "." #t))

  ("rmfamily" "Use roman font family" (make-with "font-family" "rm"))
  ("ttfamily" "Use typewriter font family" (make-with "font-family" "tt"))
  ("sffamily" "Use sans serif font family" (make-with "font-family" "ss"))
  ("mdseries" "Use medium font series" (make-with "font-series" "medium"))
  ("bfseries" "Use bold font series" (make-with "font-series" "bold"))
  ("upshape" "Use right font shape" (make-with "font-shape" "right"))
  ("itshape" "Use italic font shape" (make-with "font-shape" "italic"))
  ("slshape" "Use slanted font shape" (make-with "font-shape" "slanted"))
  ("scshape" "Use small-caps font shape"
   (make-with "font-shape" "small-caps"))
  ("rm" "Use roman font family" (make-with "font-family" "rm"))
  ("tt" "Use typewriter font family" (make 'tt))
  ("sf" "Use sans serif font family" (make-with "font-family" "ss"))
  ("md" "Use medium font series" (make-with "font-series" "medium"))
  ("bf" "Use bold font series" (make-with "font-series" "bold"))
  ("up" "Use right font shape" (make-with "font-shape" "right"))
  ("it" "Use italic font shape" (make-with "font-shape" "italic"))
  ("em" "Emphasize text" (make 'em))
  ("sl" "Use slanted font shape" (make-with "font-shape" "slanted"))
  ("sc" "Use small-caps font shape" (make-with "font-shape" "small-caps"))
  ("textrm" "Use roman font family" (make-with "font-family" "rm"))
  ("texttt" "Use typewriter font family" (make-with "font-family" "tt"))
  ("textsf" "Use sans serif font family" (make-with "font-family" "ss"))
  ("textmd" "Use medium font series" (make-with "font-series" "medium"))
  ("textbf" "Use bold font series" (make-with "font-series" "bold"))
  ("textup" "Use right font shape" (make-with "font-shape" "right"))
  ("textit" "Use italic font shape" (make-with "font-shape" "italic"))
  ("emph" "Use italic font shape" (make-with "font-shape" "italic"))
  ("textsl" "Use slanted font shape" (make-with "font-shape" "slanted"))
  ("textsc" "Use small-caps font shape" (make-with "font-shape" "small-caps"))
  ("cal" "Use calligraphic font" (make-with "math-font" "cal"))
  ("frak" "Use fraktur font" (make-with "font" "Euler"))
  ("Bbb" "Use blackboard bold font" (make-with "font" "Bbb*"))
  ("mathcal" "Use calligraphic font" (make-with "math-font" "cal"))
  ("mathscr" "Use script font" (make-with "font" "cal*"))
  ("mathfrak" "Use fraktur font" (make-with "font" "Euler"))
  ("mathbb" "Use blackboard math font" (make-with "font" "Bbb"))
  ("mathbbm" "Use blackboard math font" (make-with "font" "Bbb*"))
  ("mathrm" "Use upright roman math text" (make 'math-up))
  ("mathtt" "Use typewriter font family" (make-with "font-family" "tt"))
  ("mathsf" "Use sans serif font family" (make-with "font-family" "ss"))
  ("mathmd" "Use medium font series" (make-with "font-series" "medium"))
  ("mathbf" "Use bold font series" (make-with "font-series" "bold"))
  ("mathup" "Use right font shape" (make-with "font-shape" "right"))
  ("mathit" "Use italic font shape" (make-with "font-shape" "italic"))
  ("tiny" "Use tiny font font size" (make 'tiny))
  ("scriptsize" "Use script font size" (make 'very-small))
  ("footnotesize" "Use footnote font size" (make 'smaller))
  ("small" "Use small font size" (make 'small))
  ("normalsize" "Use normal font size" (make 'normal-size))
  ("large" "Use large font size" (make 'large))
  ("Large" "Use very large font size" (make 'larger))
  ("LARGE" "Use very large font size" (make 'very-large))
  ("huge" "Use huge font size" (make 'huge))
  ("Huge" "Use really huge font size" (make 'really-huge))
  ("displaystyle" "Switch to formula style"
   (make-with "math-display" "true"))

  ("black" "Use a black color" (make-with "color" "black"))
  ("white" "Use a white color" (make-with "color" "white"))
  ("grey" "Use a grey color" (make-with "color" "grey"))
  ("red" "Use a red color" (make-with "color" "red"))
  ("blue" "Use a blue color" (make-with "color" "blue"))
  ("yellow" "Use a yellow color" (make-with "color" "yellow"))
  ("green" "Use a green color" (make-with "color" "green"))
  ("orange" "Use a orange color" (make-with "color" "orange"))
  ("magenta" "Use a magenta color" (make-with "color" "magenta"))
  ("brown" "Use a brown color" (make-with "color" "brown"))
  ("pink" "Use a pink color" (make-with "color" "pink"))

  ("smallskip" "Insert small vertical space" (make-vspace-after "0.5fn"))
  ("medskip" "Insert medium vertical space" (make-vspace-after "1fn"))
  ("bigskip" "Insert big vertical space" (make-vspace-after "2fn"))
  ("item" "Insert new item or number" (make-item))
  ("label" "Make label" (make-label))
  ("ref" "Make reference" (make 'reference))
  ("pageref" "Make page reference" (make 'pageref))
  ("footnote" "Insert a footnote" (make 'footnote))
  ("input" "Include a document" (make 'include)))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Extensions to LaTeX
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(kbd-commands
  ("big." "Insert big ." (math-big-operator "."))
  ("underbrace" "Insert underbrace" (make-wide-under-stretched "⏟"))
  ("overbrace" "Insert overbrace" (make-wide-stretched "⏞")))

(kbd-commands
  ("ddots" "Insert ⋱" (kbd-insert "⋱"))
  ("mho" "Insert mho" (insert '(named-symbol "texmacs:mho")))
  ("Backepsilon" "Insert Backepsilon" (insert '(named-symbol "texmacs:Backepsilon")))
  ("Backsigma" "Insert Backsigma" (insert '(named-symbol "texmacs:Backsigma")))
  ("homsim" "Insert homsim" (insert '(named-symbol "texmacs:homsim")))
  ("mathcatalan" "Insert mathcatalan" (insert '(named-symbol "texmacs:mathcatalan")))
  ("mathD" "Insert mathD" (insert '(named-symbol "texmacs:mathD")))
  ("mathd" "Insert mathd" (insert '(named-symbol "texmacs:mathd")))
  ("mathe" "Insert mathe" (insert '(named-symbol "texmacs:mathe")))
  ("mathi" "Insert mathi" (insert '(named-symbol "texmacs:mathi")))
  ("mathGamma" "Insert mathGamma" (insert '(named-symbol "texmacs:mathGamma")))
  ("mathLaplace" "Insert mathLaplace" (insert '(named-symbol "texmacs:mathLaplace")))
  ("matheuler" "Insert matheuler" (insert '(named-symbol "texmacs:matheuler")))
  ("mathlambda" "Insert mathlambda" (insert '(named-symbol "texmacs:mathlambda")))
  ("mathpi" "Insert mathpi" (insert '(named-symbol "texmacs:mathpi"))))
