(texmacs-module (athena athena tm-vault-quick-switcher)
  (:use (kernel boot abbrevs)
        (kernel library list)
        (athena menus file-menu)))

(define (vault-quick-switcher-root-base)
  (url-append (vault-get-root) ""))

(define (vault-quick-switcher-url-in-current-vault? u)
  (and (url? u)
       (url-descends? u (vault-quick-switcher-root-base))))

(define (vault-quick-switcher-rel-path u)
  (url->unix (url-delta (vault-quick-switcher-root-base) u)))

(define (vault-recent-ath-files)
  (let ((res '())
        (cur (current-buffer)))
    (if (and (vault-quick-switcher-url-in-current-vault? cur)
             (url-exists? cur)
             (== (url-suffix cur) "ath"))
        (set! res (list (vault-quick-switcher-rel-path cur))))
    (for (u (recent-file-list 200))
      (if (and (vault-quick-switcher-url-in-current-vault? u)
               (url-exists? u)
               (== (url-suffix u) "ath")
               (not (in? (vault-quick-switcher-rel-path u) res)))
          (set! res (append res (list (vault-quick-switcher-rel-path u))))))
    res))

(define (vault-unsafe-path? path)
  (or (string-null? path)
      (string-starts? path "/")
      (string-starts? path "~")
      (in? ".." (string-tokenize-by-char path #\/))))

(define (vault-ensure-ath-suffix path)
  (if (string-ends? path ".ath") path (string-append path ".ath")))

(define (vault-current-file-directory)
  (let ((buf (current-buffer)))
    (if (and (vault-quick-switcher-url-in-current-vault? buf)
             (== (url-suffix buf) "ath"))
        (url-head buf)
        (vault-get-root))))

(define (vault-ensure-directory dir)
  (if (url-exists? dir)
      #t
      (let ((parent (url-head dir)))
        (if (and (url? parent) (!= parent dir) (not (url-exists? parent)))
            (vault-ensure-directory parent))
        (system-mkdir dir))))

(define (vault-empty-ath-document)
  (stree->tree
   `(document
      (TeXmacs ,(texmacs-compat-version))
      (style (tuple "generic"))
      (body (document "")))))

(define (vault-create-and-open-ath query)
  (let* ((path (vault-ensure-ath-suffix (tm-string-trim-both query))))
    (if (vault-unsafe-path? path)
        (show-message "Invalid file name for quick switcher creation." "Quick switcher")
        (let* ((target (url-append (vault-current-file-directory) (unix->url path)))
               (dir (url-head target)))
          (vault-ensure-directory dir)
          (if (and (not (url-exists? target))
                   (tree-export (vault-empty-ath-document) target "texmacs"))
              (show-message "Could not create ATHENA file." "Quick switcher")
              (load-buffer target))))))

(tm-define (open-quick-switcher)
  (:interactive #t)
  (if (not (vault-active?))
      (show-message "No active vault. Please load a vault first." "Quick switcher")
      (let ((res (vault-quick-switcher (vault-recent-ath-files))))
        (if (and (tree? res) (== (tree-label res) 'tuple) (>= (tree-arity res) 2))
            (let ((action (tree->string (tree-ref res 0)))
                  (payload (tree->string (tree-ref res 1))))
              (cond ((== action "open")
                     (load-buffer (url-append (vault-get-root) (unix->url payload))))
                    ((== action "create")
                     (vault-create-and-open-ath payload))))))))
