(texmacs-module (athena athena tm-vault-recents)
  (:use (kernel boot abbrevs)
        (kernel library list)))

(tm-define (recent-vaults-file)
  "$ATHENA_HOME_PATH/system/recent_vaults.scm")

(tm-define (get-recent-vaults)
  (let ((file (recent-vaults-file)))
    (if (url-exists? file)
        (let ((data (load-object file)))
          (if (list? data) data '()))
        '())))

(tm-define (add-recent-vault dir)
  (let* ((dir-s (url->string dir))
         (old (get-recent-vaults))
         (new (cons dir-s (list-difference old (list dir-s))))
         (final (sublist new 0 (min (length new) 20))))
    (save-object (recent-vaults-file) final)))

(tm-menu (recent-vault-menu)
  (for (dir-s (get-recent-vaults))
    (let* ((u (string->url dir-s))
           (name (url->system (url-tail u)))
           (v-name `(verbatim ,name))
           (v-dir `(verbatim ,dir-s)))
      ((balloon (eval v-name) (eval v-dir))
       (load-vault-dir u)))))
