(texmacs-module (athena athena tm-vault-quick-switcher)
  (:use (kernel boot abbrevs)
        (kernel library list)
        (kernel athena tm-file-system)
        (athena athena tm-vault-namespaces)
        (athena menus file-menu)))

(define (vault-recent-ath-files)
  (let ((res '()))
    (for (u (recent-file-list 200))
      (if (and (url? u) (== (url-suffix u) "ath"))
          (let ((path (url->unix u)))
            (if (not (in? path res))
                (set! res (append res (list path)))))))
    res))

(define (vault-unsafe-path? path)
  (or (string-null? path)
      (string-starts? path "/")
      (string-starts? path "~")
      (in? ".." (string-tokenize-by-char path #\/))))

(define (vault-ensure-ath-suffix path)
  (if (string-ends? path ".ath") path (string-append path ".ath")))

(define (vault-current-file-directory)
  (let ((buf (current-buffer)))
    (if (and (url-descends? buf (url-append (vault-get-root) ""))
             (== (url-suffix buf) "ath"))
        (url-head buf)
        (vault-get-root))))

(define (vault-ensure-directory dir)
  (if (url-exists? dir)
      #t
      (let ((parent (url-head dir)))
        (if (and (url? parent) (!= parent dir) (not (url-exists? parent)))
            (vault-ensure-directory parent))
        (system-mkdir dir))))

(define (vault-empty-ath-document)
  (stree->tree
   `(document
      (TeXmacs ,(texmacs-compat-version))
      (style (tuple "generic"))
      (body (document "")))))

(define (vault-create-and-open-ath query)
  (let* ((path (vault-ensure-ath-suffix (tm-string-trim-both query))))
    (if (vault-unsafe-path? path)
        (show-message "Invalid file name for quick switcher creation." "Quick switcher")
        (let* ((target (url-append (vault-current-file-directory) (unix->url path)))
               (dir (url-head target)))
          (vault-ensure-directory dir)
          (if (url-exists? target)
              (load-buffer target)
              (let ((err (namespace-create-file-with-optional-initializer
                          (url->system target))))
                (cond ((== err "")
                       (load-buffer target))
                      ((== err "cancelled")
                       (noop))
                      (else
                       (show-message err "Quick switcher")))))))))

(tm-define (quick-switcher-complete res)
  (if (and (tree? res) (== (tree-label res) 'tuple) (>= (tree-arity res) 2))
      (let ((action (tree->string (tree-ref res 0)))
            (payload (tree->string (tree-ref res 1))))
        (cond ((== action "open")
               (load-buffer (url-append (vault-get-root) (unix->url payload))))
              ((== action "open-url")
               (load-buffer (string->url payload)))
              ((== action "create")
               (vault-create-and-open-ath payload))))))

(tm-define (open-quick-switcher)
  (:interactive #t)
  (if (not (vault-active?))
      (show-message "No active vault. Please load a vault first." "Quick switcher")
      (vault-quick-switcher (vault-recent-ath-files))))
