#!/usr/bin/env bash
set -euo pipefail

KWIN_ATHENA_ROOT="${KWIN_ATHENA_ROOT:-$HOME/data/Software/KDE}"
KWIN_ATHENA_SRC="${KWIN_ATHENA_SRC:-$KWIN_ATHENA_ROOT/kwin-athena-src}"
KWIN_ATHENA_BUILD="${KWIN_ATHENA_BUILD:-$KWIN_ATHENA_ROOT/kwin-athena-build}"
KWIN_ATHENA_BUILD_TYPE="${KWIN_ATHENA_BUILD_TYPE:-RelWithDebInfo}"

cmake -S "$KWIN_ATHENA_SRC" -B "$KWIN_ATHENA_BUILD" -G Ninja \
  -DCMAKE_BUILD_TYPE="$KWIN_ATHENA_BUILD_TYPE" \
  -DBUILD_TESTING=OFF \
  -DKWIN_BUILD_KCMS=OFF \
  -DKWIN_BUILD_DECORATIONS=OFF \
  -DKWIN_BUILD_TABBOX=OFF \
  -DKWIN_BUILD_RUNNERS=OFF \
  -DKWIN_BUILD_NOTIFICATIONS=OFF \
  -DKWIN_BUILD_SCREENLOCKER=OFF

cmake --build "$KWIN_ATHENA_BUILD" -j"$(nproc)"

