#!/usr/bin/env bash
set -euo pipefail

KWIN_ATHENA_ROOT="${KWIN_ATHENA_ROOT:-$HOME/data/Software/KDE}"
KWIN_ATHENA_SRC="${KWIN_ATHENA_SRC:-$KWIN_ATHENA_ROOT/kwin-athena-src}"
KWIN_ATHENA_FULL_BUILD="${KWIN_ATHENA_FULL_BUILD:-$KWIN_ATHENA_ROOT/kwin-athena-full-build}"
KWIN_ATHENA_INSTALL="${KWIN_ATHENA_INSTALL:-$KWIN_ATHENA_ROOT/kwin-athena-install}"
KWIN_ATHENA_BUILD_TYPE="${KWIN_ATHENA_BUILD_TYPE:-RelWithDebInfo}"

cmake -S "$KWIN_ATHENA_SRC" -B "$KWIN_ATHENA_FULL_BUILD" -G Ninja \
  -DCMAKE_BUILD_TYPE="$KWIN_ATHENA_BUILD_TYPE" \
  -DCMAKE_INSTALL_PREFIX="$KWIN_ATHENA_INSTALL"

cmake --build "$KWIN_ATHENA_FULL_BUILD" -j"$(nproc)"
cmake --install "$KWIN_ATHENA_FULL_BUILD"
