#!/bin/sh
# Program to make Guile interface to TeXmacs

# update documentation of glue 
./build-auto-doc

GUILE=guile
if [ -f "$HOME/opt/guile18/bin/guile" ]; then
  GUILE="$HOME/opt/guile18/bin/guile"
fi

if test $# = 2; then
  $GUILE -l build-glue.scm -l $1 -c "(quit)" | cat > $2
else
  echo "Usage: build-glue <input.scm> <output.cpp>"
fi
