#!/bin/sh
# Program to make Guile interface to TeXmacs

GUILE=guile
if [ -f "$HOME/opt/guile18/bin/guile" ]; then
  GUILE="$HOME/opt/guile18/bin/guile"
fi

# update documentation of glue
$GUILE -l make-apidoc-module.scm -c "(quit)" | cat >../../../ATHENA/progs/prog/glue-symbols.scm

$GUILE -l make-apidoc-doc.scm -c "(quit)" | cat >../../../ATHENA/doc/devel/scheme/api/glue-auto-doc.en.tm
