("abscissa Create web site" "948")
("abscissa Document font selector" "674")
("abscissa Document metadata" "1279")
("abscissa Document page format" "1158")
("abscissa Equation editor plugin settings" "1131")
("abscissa Error messages" "186")
("abscissa Font selector" "608")
("abscissa Global search" "0")
("abscissa High resolution screen settings" "815")
("abscissa Insert LaTeX formula" "781")
("abscissa Macro editor" "990")
("abscissa Macros editor" "852")
("abscissa Notification" "1839")
("abscissa Page setup" "7")
("abscissa Preferences" "884")
("abscissa Quick switcher" "992")
("abscissa Search" "0")
("abscissa Search and replace" "990")
("abscissa Shortcuts editor" "1149")
("abscissa Statistics" "1837")
("abscissa TeXmacs" "0")
("abscissa TeXmacs:2" "0")
("abscissa TeXmacs:3" "0")
("abscissa TeXmacs:4" "0")
("abscissa TeXmacs:5" "0")
("abscissa TeXmacs:6" "0")
("abscissa User preferences" "1264")
("abscissa Vault Bugcheck" "355")
("advanced font customization" "on")
("buffer management" "ads")
("debugging tool" "off")
("developer tool" "off")
("enunciation color preset" "Nord Light")
("equation-editor" "on")
("gui cursor color" "#0000ff")
("gui selection color" "blue")
("gui:live-statistics" "on")
("height Create web site" "226")
("height Document font selector" "1515")
("height Document metadata" "254")
("height Document page format" "815")
("height Equation editor plugin settings" "676")
("height Error messages" "1143")
("height Font selector" "1515")
("height Global search" "487")
("height High resolution screen settings" "274")
("height Insert LaTeX formula" "166")
("height Macro editor" "624")
("height Macros editor" "989")
("height Notification" "140")
("height Page setup" "229")
("height Preferences" "932")
("height Quick switcher" "191")
("height Search" "319")
("height Search and replace" "440")
("height Shortcuts editor" "373")
("height Statistics" "191")
("height TeXmacs" "1514")
("height TeXmacs:2" "596")
("height TeXmacs:3" "897")
("height TeXmacs:4" "897")
("height TeXmacs:5" "998")
("height TeXmacs:6" "389")
("height User preferences" "932")
("height Vault Bugcheck" "473")
("inertial scrolling" "on")
("inertial scrolling friction" "0.90")
("inertial scrolling sensitivity" "8.0")
("interactive questions" "popup")
("look and feel" "kde")
("main icon bar" "on")
("mode dependent icons" "on")
("ordinate Create web site" "821")
("ordinate Document font selector" "336")
("ordinate Document metadata" "771")
("ordinate Document page format" "670")
("ordinate Equation editor plugin settings" "597")
("ordinate Error messages" "236")
("ordinate Font selector" "171")
("ordinate Global search" "0")
("ordinate High resolution screen settings" "902")
("ordinate Insert LaTeX formula" "847")
("ordinate Macro editor" "622")
("ordinate Macros editor" "440")
("ordinate Notification" "371")
("ordinate Page setup" "45")
("ordinate Preferences" "684")
("ordinate Quick switcher" "838")
("ordinate Search" "0")
("ordinate Search and replace" "714")
("ordinate Shortcuts editor" "336")
("ordinate Statistics" "1045")
("ordinate TeXmacs" "0")
("ordinate TeXmacs:2" "0")
("ordinate TeXmacs:3" "0")
("ordinate TeXmacs:4" "0")
("ordinate TeXmacs:5" "0")
("ordinate TeXmacs:6" "0")
("ordinate User preferences" "449")
("ordinate Vault Bugcheck" "1149")
("page medium" "papyrus")
("persistent fit width" "on")
("preferred fonts" "(\"B612\")")
("presentation tool" "off")
("remember ads panes layout" "off")
("render solution in smaller font" "off")
("retina-zoom" "off")
("search-and-replace" "off")
("shift-123" "{")
("shift-124" "|")
("shift-125" "}")
("shift-33" "!")
("shift-34" "\"")
("shift-35" "#")
("shift-36" "$")
("shift-37" "%")
("shift-38" "&")
("shift-40" "(")
("shift-41" ")")
("shift-42" "*")
("shift-43" "+")
("shift-58" ":")
("shift-60" "<")
("shift-62" ">")
("shift-63" "?")
("shift-65" "A")
("shift-66" "B")
("shift-67" "C")
("shift-68" "D")
("shift-69" "E")
("shift-70" "F")
("shift-71" "G")
("shift-72" "H")
("shift-73" "I")
("shift-74" "J")
("shift-75" "K")
("shift-76" "L")
("shift-77" "M")
("shift-78" "N")
("shift-79" "O")
("shift-80" "P")
("shift-81" "Q")
("shift-82" "R")
("shift-83" "S")
("shift-84" "T")
("shift-85" "U")
("shift-86" "V")
("shift-87" "W")
("shift-88" "X")
("shift-90" "Z")
("shift-94" "^")
("shift-95" "_")
("show font substitution warning" "off")
("side tools" "off")
("snap to pages" "on")
("source tool" "off")
("status bar" "on")
("texmacs->pdf:data-art cover" "on")
("toolbar search" "off")
("user provided icons" "off")
("vault acknowledgments color" "#ece0e9")
("vault auto anchor enunciations on save" "on")
("vault auto copy images to vault" "on")
("vault auto load last" "on")
("vault axiom color" "#ece3ed")
("vault conjecture color" "#e2e5f1")
("vault convention color" "#e3e8e2")
("vault corollary color" "#dcecf0")
("vault definition color" "#f0e4d8")
("vault disambiguation color" "#e0e4ec")
("vault example color" "#e2eddc")
("vault exercise color" "#dfece0")
("vault explorer track current file" "on")
("vault explorer use system trash" "on")
("vault labels mode" "hidden")
("vault law color" "#f1e0d5")
("vault lemma color" "#dfeaf2")
("vault normalize image filename when inserting" "on")
("vault notation color" "#e7ebdd")
("vault note color" "#dde8f1")
("vault preferred font" "pagella")
("vault problem color" "#dce9e7")
("vault proposition color" "#dceeea")
("vault question color" "#eee6da")
("vault remark color" "#e8eadc")
("vault report missing last" "on")
("vault take preferences with vault" "on")
("vault theorem color" "#e5e9f0")
("vault warning color" "#f1ded4")
("width Create web site" "1174")
("width Document font selector" "1658")
("width Document metadata" "778")
("width Document page format" "1261")
("width Equation editor plugin settings" "806")
("width Error messages" "2340")
("width Font selector" "1658")
("width Global search" "2022")
("width High resolution screen settings" "997")
("width Insert LaTeX formula" "922")
("width Macro editor" "1089")
("width Macros editor" "1364")
("width Notification" "546")
("width Page setup" "665")
("width Preferences" "1674")
("width Quick switcher" "1085")
("width Search" "2048")
("width Search and replace" "1089")
("width Shortcuts editor" "1026")
("width Statistics" "380")
("width TeXmacs" "2764")
("width TeXmacs:2" "2048")
("width TeXmacs:3" "1532")
("width TeXmacs:4" "1532")
("width TeXmacs:5" "1497")
("width TeXmacs:6" "2187")
("width User preferences" "1455")
("width Vault Bugcheck" "1775")
("zoom factor" "3.61939646533548")
