(define provider-load-count 0)

(define (assert-equal expected actual label)
  (unless (equal? expected actual)
    (error label expected actual)))

(define (assert-true actual label)
  (unless actual
    (error label actual)))

(let ((stats (gc-stats)))
  (assert-true (>= (assq-ref stats 'heap-size) (* 64 1024 1024))
               "ATHENA initial GC heap")
  (assert-true (> (assq-ref stats 'gc-parallel-markers) 1)
               "ATHENA parallel GC markers")
  (assert-equal #t (assq-ref stats 'gc-incremental)
                "ATHENA incremental GC")
  (assert-equal 1 (assq-ref stats 'gc-free-space-divisor)
                "ATHENA GC free-space divisor")
  (assert-equal 10 (assq-ref stats 'gc-time-limit-ms)
                "ATHENA incremental GC pause target"))

(define (native-inherited-forward-reference)
  native-inherited-forward-binding)

(lazy-define (test provider)
  (#:require (> (car args) 0))
  (#:synopsis "conditional lazy target")
  native-lazy-conditioned)
(native-lazy-conditioned -1)
(assert-equal 0 provider-load-count "condition avoids provider load")
(assert-equal '("conditional lazy target")
              (property 'native-lazy-conditioned #:synopsis)
              "lazy property")
(assert-equal 105 (native-lazy-conditioned 5) "conditioned lazy call")
(assert-equal 1 provider-load-count "conditioned provider exactly once")

(lazy-define (test provider) native-lazy-target native-dispatch)
(assert-equal 42 (native-lazy-target 5) "lazy call")
(assert-equal 39 (native-lazy-target 2) "second lazy call")
(assert-equal 1 provider-load-count "provider exactly once")
(assert-equal 'base (native-dispatch 0) "base dispatch")
(assert-equal 'positive (native-dispatch 1) "conditional dispatch")
(assert-equal '("native dispatch")
              (property 'native-dispatch #:synopsis)
              "native property")
(module-load '(test provider))
(assert-equal 1 provider-load-count "module-load exactly once")

(module-load '(test dispatch-base))
(assert-equal '(base 0) (call-cross-module-dispatch 0)
              "base module dispatch")
(module-load '(test dispatch-extension))
(assert-equal '(positive 1) (call-cross-module-dispatch 1)
              "later module updates compiled local dispatcher")
(assert-equal '(base 0) (call-cross-module-dispatch 0)
              "later module preserves former dispatch")

(module-load '(test cycle-a))
(assert-equal 'a (cycle-a-value) "cycle A")
(assert-equal 'b (cycle-b-value) "cycle B")

(%athena-root-binding-set! 'native-duplicate-binding 'root)
(module-load '(test legacy-compat))
(%athena-root-binding-set! 'native-forward-binding 73)
(assert-equal 73 (native-forward-reference) "late global binding")
(assert-equal 'module (native-duplicate-reference)
              "later module import wins without ambiguity")
(inherit-modules (test inherited-source))
(assert-equal 91 (native-inherited-forward-reference)
              "inherit satisfies compiled forward placeholder")
