("abstract" "povzetek")
("algorithm" "algoritem")
("and" "in")
("appendix" "dodatek")
("axiom" "aksiom")
("by" "avtor:")
("case" "case")
("cc" "kopija")
("chapter" "poglavje")
("convention" "konvencija")
("corollary" "korolar")
("date" "datum")
("definition" "definicija")
("email" "email")
("encl" "encl")
("epilogue" "epilog")
("example" "primer")
("exercise" "vaja")
("figure" "slika")
("file" "datoteka")
("footer" "noga")
("function" "funkcija")
("glossary" "besednjak")
("header" "glava")
("homepage" "doma£a stran")
("index" "stvarno kazalo")
("keywords" "klju£ne besede")
("lemma" "lema")
("list of figures" "seznam slik")
("list of tables" "seznam tabel")
("notation" "notacija")
("note" "notica")
("or" "ali")
("page" "stran")
("paragraph" "odstavek")
("part" "del")
("problem" "problem")
("prologue" "prolog")
("proof" "dokaz")
("proposition" "izjava")
("range" "obseg")
("references" "sklicevanja")
("remark" "opomba")
("search" "i²£i")
("section" "razdelek")
("see" "glej")
("subparagraph" "pododstavek")
("subsection" "podrazdelek")
("subsubsection" "podpodrazdelek")
("table of contents" "kazalo")
("tables" "tabele")
("table" "tabela")
("theorem" "izrek")
("warning" "opozorilo")
("web" "splet")
