("abstract" "streszczenie")
("algorithm" "algorytm")
("and" "i")
("appendix" "dodatek")
("axiom" "aksjomat")
("by" "autor")
("case" "wybór")
("cc" "cc")
("chapter" "rozdziaª")
("convention" "konwencja")
("corollary" "wniosek")
("date" "data")
("definition" "definicja")
("email" "email")
("encl" "encl")
("epilogue" "epilog")
("example" "przykªad")
("exercise" "¢wiczenie")
("figure" "rysunek")
("file" "plik")
("footer" "stopka")
("function" "funkcja")
("glossary" "sªownik")
("header" "nagªówek")
("index" "indeks")
("keywords" "sªowa kluczowe")
("lemma" "lemat")
("list of figures" "spis ryskunków")
("list of tables" "spis tablic")
("notation" "notacja")
("note" "notka")
("or" "lub")
("page" "strona")
("paragraph" "akapit")
("part" "cz¦±¢")
("problem" "problem")
("prologue" "kody jawne")
("proof" "dowód")
("proposition" "stwierdzenie")
("range" "zakres")
("references" "odsyªacze")
("remark" "uwaga")
("search" "szukaj")
("section" "akapit")
("see" "zobacz")
("subparagraph" "pod-paragraf")
("subsection" "punkt")
("subsubsection" "podpunkt")
("table" "tablica")
("table of contents" "spis tre±ci")
("tables" "tablice")
("theorem" "twierdzenie")
("warning" "ostrze»enie")
