("abstract" "abstract")
("appendix" "appendix")
("axiom" "axiom")
("by" "av")
("chapter" "kapitel")
("corollary" "corollar")
("definition" "definition")
("epilogue" "epilog")
("example" "exempel")
("exercise" "övningsuppgift")
("figure" "figur")
("file" "fil")
("function" "function")
("glossary" "glossar")
("index" "index")
("lemma" "lemma")
("list of figures" "figurlista")
("list of tables" "tabelllista")
("note" "notis")
("page" "sida")
("paragraph" "paragraf")
("part" "del")
("prologue" "prolog")
("proof" "bevis")
("proposition" "proposition")
("references" "referenser")
("remark" "kommentar")
("section" "avsnitt")
("subsection" "underavsnitt")
("subsubsection" "underunderavsnitt")
("table" "tabell")
("table of contents" "innehållsförteckning")
("theorem" "teorem")
("warning" "varning")
