("abstract" "saºetak")
("acknowledgments" "zahvale")
("algorithm" "algoritam")
("and" "i")
("answer" "odgovor")
("appendix" "dodatak")
("axiom" "aksiom")
("busy" "zauzeto")
("by" "sa")
("case" "case")
("cc" "kopija")
("chapter" "poglavlje")
("conjecture" "pretpostavka")
("convention" "konvencija")
("corollary" "korolar")
("date" "datum")
("dead" "mrtav")
("definition" "definicija")
("download" "preuzmi")
("email" "e-po²ta")
("encl" "prilozi")
("epilogue" "epilog")
("example" "primjer")
("exercise" "zadatak")
("figure" "slika")
("file" "datoteka")
("footer" "podnoºje")
("function" "funkcija")
("glossary" "pojmovnik")
("header" "zaglavlje")
("headers" "zaglavlja")
("homepage" "ku¢na stranica")
("index" "kazalo")
("interrupted" "prekinuto")
("keywords" "klju£ne rije£i")
("lemma" "lema")
("list of figures" "popis slika")
("list of tables" "popis tablica")
("notation" "notacija")
("note" "bilje²ka")
("or" "ili")
("page" "stranica")
("pages" "stranice")
("paragraph" "odlomak")
("paragraphs" "odlomci")
("part" "dio")
("plot" "graf")
("plot curve" "nacrtaj krivulju")
("problem" "problem")
("prologue" "prolog")
("proof" "dokaz")
("properties" "svojstva")
("proposition" "propozicija")
("question" "pitanje")
("range" "raspon")
("references" "reference")
("remark" "napomena")
("search" "pretraºivanje")
("section" "odjeljak")
("sections" "odjeljci")
("see" "vidi")
("solution" "rje²enje")
("subparagraph" "pododlomak")
("subsection" "pododjeljak")
("subsubsection" "podpododjeljak")
("table" "tablica")
("table of contents" "sadrºaj")
("tables" "tablice")
("theorem" "teorem")
("this" "ovo")
("this document has been written using" "ovaj je dokument napisan koriste¢i")
("warning" "upozorenje")
("web" "web")
