("abstract" "abstrakt")
("acknowledgments" "poďakovanie")
("algorithm" "algoritmus")
("algorithms" "algoritmy")
("and" "a")
("answer" "odpoveď")
("answers" "odpovede")
("appendix" "dodatok")
("axiom" "axióma")
("axioms" "axiómy")
("busy" "pracujem...")
("by" "vytvoril")
("case" "veľké/malé písmená")
("cc" "slepá kópia")
("chapter" "kapitola")
("conjecture" "domnienka")
("conjectures" "domnienky")
("convention" "konvencia")
("conventions" "konvencie")
("corollaries" "dôsledky")
("corollary" "dôsledok")
("date" "dátum")
("dead" "mŕtvy")
("definition" "definícia")
("definitions" "definície")
("download" "stiahnuť")
("email" "email")
("encl" "prílohy")
("epilogue" "epilóg")
("example" "príklad")
("examples" "príklady")
("exercise" "cvičenie")
("exercises" "cvičenia")
("figure" "obrázok")
("figures" "obrázky")
("file" "súbor")
("footer" "zápätie")
("for all" "pre  všetky")
("function" "funkcia")
("glossary" "glosár")
("header" "záhlavie (hlavička)")
("headers" "hlavičky")
("homepage" "domovská stránka")
("iff" "akk")
("index" "register")
("interrupted" "prerušené")
("keywords" "kľúčové slová")
("lemma" "lema")
("lemmas" "lemmy")
("list of figures" "zoznam obrázkov")
("list of tables" "zoznam tabuliek")
("notation" "notácia")
("notations" "notácie")
("note" "poznámka")
("notes" "poznámky")
("or" "alebo")
("page" "strana")
("pages" "strany")
("paragraph" "odstavec")
("paragraphs" "odstavce")
("part" "časť")
("plot" "graf")
("problem" "problém")
("problems" "problémy")
("prologue" "prológ")
("proof" "dôkaz")
("properties" "vlastnosti")
("proposition" "tvrdenie")
("propositions" "tvrdenia")
("question" "otázka")
("questions" "otázky")
("range" "rozsah")
("references" "odkazy")
("remark" "poznámka")
("remarks" "poznámky")
("search" "hľadať")
("section" "sekcia")
("sections" "sekcie")
("see" "viď")
("solution" "riešenie")
("solutions" "riešenia")
("subparagraph" "pododstavec")
("subparagraphs" "pododstavce")
("subsection" "podsekcia")
("subsections" "podsekcie")
("subsubsection" "podpodsekcia")
("subsubsections" "podpodsekcie")
("table" "tabuľka")
("table of contents" "obsah")
("tables" "tabuľky")
("theorem" "teoréma")
("theorems" "teorémy")
("this" "tento")
("this article has been written using" "tento článok bol napísaný použitím")
("this document has been written using" "tento tento dokument bol napísaný použitím")
("warning" "varovanie")
("warnings" "varovania")
("web" "web")
