("abstract" "abstrakt")
("algorithm" "algoritmus")
("and" "a")
("appendix" "dodatek")
("axiom" "axióm")
("by" "vytvo°il")
("case" "case")
("cc" "slepá kopie")
("chapter" "kapitola")
("convention" "konvence")
("corollary" "korolár")
("date" "datum")
("definition" "definice")
("email" "email")
("encl" "p°ílohy")
("epilogue" "epilog")
("example" "p°íklad")
("exercise" "cvi£ení")
("figure" "obrázek")
("file" "soubor")
("footer" "zápatí")
("function" "funkce")
("glossary" "glosá°")
("header" "hlavi£ka")
("index" "rejst°ík")
("keywords" "klí£ová slova")
("lemma" "lemma")
("list of figures" "seznam obrázk·")
("list of tables" "seznam tabulek")
("notation" "notace")
("note" "poznámka")
("or" "nebo")
("page" "strana")
("paragraph" "odstavec")
("part" "£ást")
("problem" "p°íklad")
("prologue" "prolog")
("proof" "d·kaz")
("proposition" "tvrzení")
("range" "rozsah")
("references" "odkazy")
("remark" "anotace")
("search" "hledat")
("section" "sekce")
("see" "viz")
("subparagraph" "pododstavec")
("subsection" "podsekce")
("subsubsection" "podposekce")
("table" "tabulka")
("table of contents" "obsah")
("tables" "tabulky")
("theorem" "teorém")
("warning" "varování")
