("abstract" "résumé")
("acknowledgments" "remerciements")
("algorithm" "algorithme")
("algorithms" "algorithmes")
("and" "et")
("answer" "réponse")
("answers" "réponses")
("appendix" "annexe")
("axiom" "axiome")
("axioms" "axiomes")
("busy" "en cours")
("by" "par")
("case" "choisir")
("cc" "copies à")
("chapter" "chapitre")
("conjecture" "conjecture")
("conjectures" "conjectures")
("convention" "convention")
("conventions" "conventions")
("corollaries" "corollaires")
("corollary" "corollaire")
("date" "date")
("dead" "mort")
("definition" "définition")
("definitions" "définitions")
("download" "télécharger")
("email" "email")
("encl" "inclus")
("epilogue" "épilogue")
("example" "exemple")
("examples" "exemples")
("exercise" "exercice")
("exercises" "exercices")
("figure" "figure")
("figures" "figures")
("file" "fichier")
("files" "fichiers")
("footer" "pied de page")
("for all" "pour tout")
("function" "fonction")
("glossary" "glossaire")
("header" "en-tête")
("headers" "en-têtes")
("homepage" "page d'acceuil")
("iff" "ssi")
("index" "index")
("interrupted" "interrompu")
("keywords" "mots-clefs")
("lemma" "lemme")
("lemmas" "lemmes")
("list of figures" "liste de figures")
("list of tables" "liste de tableaux")
("notation" "notation")
("notations" "notations")
("note" "note")
("notes" "notes")
("or" "ou")
("page" "page")
("pages" "pages")
("paragraph" "paragraphe")
("paragraphs" "paragraphes")
("part" "partie")
("plot" "graphique")
("problem" "problème")
("problems" "problèmes")
("prologue" "prologue")
("proof" "démonstration")
("proofs" "démonstrations")
("properties" "propriétés")
("property" "propriété")
("proposition" "proposition")
("propositions" "propositions")
("question" "question")
("questions" "questions")
("range" "partie")
("references" "références")
("remark" "remarque")
("remarks" "remarques")
("search" "chercher")
("section" "section")
("sections" "sections")
("see" "voir")
("solution" "solution")
("solutions" "solutions")
("subparagraph" "sous-paragraphe")
("subparagraphs" "sous-paragraphes")
("subsection" "sous-section")
("subsections" "sous-sections")
("subsubsection" "sous-sous-section")
("subsubsections" "sous-sous-sections")
("table" "tableau")
("table of contents" "table des matières")
("tables" "tableaux")
("theorem" "théorème")
("theorems" "théorèmes")
("this" "ceci")
("this article has been written using" "cet article a été rédigé avec")
("this document has been written using" "ce document a été rédigé avec")
("warning" "avertissement")
("warnings" "avertissements")
("web" "toile")
