("abstract" "rezumat")
("algorithm" "algoritm")
("and" "³i")
("appendix" "anexa")
("axiom" "axiom ")
("by" "prin")
("case" "caz")
("cc" "copie la")
("chapter" "capitol")
("convention" "convenµie")
("corollary" "corolar")
("date" "data")
("definition" "definiµie")
("email" "email")
("encl" "inclus")
("epilogue" "epilog")
("example" "exemplu")
("exercise" "exerciµiu")
("figure" "figur ")
("file" "fi³ier")
("footer" "footer")
("function" "funcµie")
("glossary" "glosar")
("header" "header")
("index" "index")
("keywords" "cuvinte cheie")
("lemma" "lem ")
("list of figures" "list  de figuri")
("list of tables" "list  de tabele")
("notation" "notaµie")
("note" "not ")
("or" "sau")
("page" "pagin ")
("paragraph" "paragraf")
("part" "parte")
("problem" "problem ")
("prologue" "prolog")
("proof" "demonstraµie")
("proposition" "propoziµie")
("range" "interval")
("references" "referinµe")
("remark" "observaµie")
("search" "c utare")
("section" "secµiune")
("see" "vezi")
("subparagraph" "sub-paragraf")
("subsection" "sub-secµiune")
("subsubsection" "sub-sub-secµiune")
("table" "tabel")
("table of contents" "cuprins")
("tables" "tabele")
("theorem" "teorem ")
("warning" "avertisment")
