("abstract" "resumen")
("algorithm" "algoritmo")
("and" "y")
("answer" "respuesta")
("appendix" "apéndice")
("axiom" "axioma")
("by" "por")
("case" "caso")
("cc" "cc")
("chapter" "capítulo")
("convention" "convenio")
("corollary" "corolario")
("date" "fecha")
("definition" "definición")
("email" "correo-e")
("encl" "adj.")
("epilogue" "epílogo")
("example" "ejemplo")
("exercise" "ejercicio")
("figure" "figura")
("file" "fichero")
("footer" "pie")
("function" "función")
("glossary" "glosario")
("header" "cabecera")
("index" "índice de materias")
("keywords" "palabras clave")
("lemma" "lema")
("list of figures" "lista de figuras")
("list of tables" "lista de tablas")
("notation" "notación")
("note" "nota")
("or" "o")
("page" "página")
("paragraph" "párrafo")
("part" "parte")
("problem" "problema")
("prologue" "prólogo")
("proof" "demostración")
("proposition" "proposición")
("question" "pregunta")
("range" "rango")
("references" "referencias")
("remark" "observación")
("search" "buscar")
("section" "sección")
("see" "ver")
("solution" "solución")
("subparagraph" "subpárrafo")
("subsection" "subsección")
("subsubsection" "subsubsección")
("table" "tabla")
("table of contents" "índice")
("tables" "tablas")
("theorem" "teorema")
("warning" "aviso")
("A.M.S. subject classification" "clasificación por temas de la AMS")
