;;; Compute dependency levels for ATHENA's Scheme bytecode build.

(use-modules (ice-9 rdelim) (srfi srfi-1))

(define (module-declaration path)
  (call-with-input-file path
    (lambda (port)
      (let loop ()
        (let ((form (read port)))
          (cond ((eof-object? form) #f)
                ((and (pair? form) (eq? (car form) 'texmacs-module)) form)
                (else (loop))))))))

(define (module-entry path)
  (let ((declaration (module-declaration path)))
    (if (not declaration)
        (list path #f '())
        (let ((name (cadr declaration))
              (options (cddr declaration)))
          (list path name
                (append-map
                  (lambda (option)
                    (if (and (pair? option)
                             (let* ((head (car option))
                                    (text (object->string head)))
                               (member text
                                       '("#:use" "#:inherit"
                                         ":use" ":inherit"))))
                        (cdr option)
                        '()))
                  options))))))

(define (read-source-list path)
  (call-with-input-file path
    (lambda (port)
      (let loop ((result '()))
        (let ((line (read-line port)))
          (if (eof-object? line)
              (reverse result)
              (loop (cons line result))))))))

(define (entry-path entry) (car entry))
(define (entry-name entry) (cadr entry))
(define (entry-dependencies entry) (caddr entry))

(define (module-key name)
  (and name (object->string name)))

(define (emit-entry level component dependencies entry)
  (display level)
  (display #\tab)
  (display component)
  (display #\tab)
  (display (entry-path entry))
  (display #\tab)
  (display (string-join (map number->string dependencies) ","))
  (newline))

(define (strongly-connected-components entries)
  (let ((by-key (make-hash-table))
        (indices (make-hash-table))
        (lowlinks (make-hash-table))
        (on-stack (make-hash-table))
        (stack '())
        (next-index 0)
        (components '()))
    (for-each (lambda (entry)
                (when (entry-name entry)
                  (hash-set! by-key (module-key (entry-name entry)) entry)))
              entries)
    (define (internal-dependencies entry)
      (filter-map (lambda (dependency)
                    (hash-ref by-key (module-key dependency)))
                  (entry-dependencies entry)))
    (define (strong-connect entry)
      (let ((key (module-key (entry-name entry))))
        (hash-set! indices key next-index)
        (hash-set! lowlinks key next-index)
        (set! next-index (+ next-index 1))
        (set! stack (cons entry stack))
        (hash-set! on-stack key #t)
        (for-each
          (lambda (dependency)
            (let ((dependency-key (module-key (entry-name dependency))))
              (cond
                ((not (hash-ref indices dependency-key))
                 (strong-connect dependency)
                 (hash-set! lowlinks key
                            (min (hash-ref lowlinks key)
                                 (hash-ref lowlinks dependency-key))))
                ((hash-ref on-stack dependency-key)
                 (hash-set! lowlinks key
                            (min (hash-ref lowlinks key)
                                 (hash-ref indices dependency-key)))))))
          (internal-dependencies entry))
        (when (= (hash-ref lowlinks key) (hash-ref indices key))
          (let pop ((component '()))
            (let* ((member (car stack))
                   (member-key (module-key (entry-name member))))
              (set! stack (cdr stack))
              (hash-set! on-stack member-key #f)
              (let ((component (cons member component)))
                (if (eq? member entry)
                    (set! components (cons component components))
                    (pop component))))))))
    (for-each (lambda (entry)
                (when (and (entry-name entry)
                           (not (hash-ref indices
                                          (module-key (entry-name entry)))))
                  (strong-connect entry)))
              entries)
    (append (reverse components)
            (map list (filter (lambda (entry) (not (entry-name entry)))
                              entries)))))

(define (plan entries)
  (let* ((components (strongly-connected-components entries))
         (component-of (make-hash-table))
         (component-ids (iota (length components))))
    (for-each
      (lambda (component id)
        (for-each (lambda (entry)
                    (when (entry-name entry)
                      (hash-set! component-of
                                 (module-key (entry-name entry)) id)))
                  component))
      components component-ids)
    (define (component-dependencies id)
      (sort
        (delete-duplicates
          (append-map
            (lambda (entry)
              (filter-map
                (lambda (dependency)
                  (let ((dependency-id
                         (hash-ref component-of (module-key dependency))))
                    (and dependency-id
                         (not (= dependency-id id))
                         dependency-id)))
                (entry-dependencies entry)))
            (list-ref components id)))
        <))
    (let loop ((remaining component-ids) (completed '()) (level 0))
      (unless (null? remaining)
        (let ((ready
               (filter (lambda (id)
                         (every (lambda (dependency)
                                  (member dependency completed))
                                (component-dependencies id)))
                       remaining)))
          (when (null? ready)
            (error "internal error: condensation graph contains a cycle"))
          (for-each
            (lambda (id)
              (let ((dependencies (component-dependencies id)))
                (for-each (lambda (entry)
                            (emit-entry level id dependencies entry))
                          (list-ref components id))))
            ready)
          (loop (lset-difference = remaining ready)
                (append ready completed)
                (+ level 1)))))))

(let ((arguments (cdr (command-line))))
  (unless (= (length arguments) 1)
    (error "usage: plan-athena-scheme-bytecode.scm SOURCE-LIST"))
  (plan (map module-entry (read-source-list (car arguments)))))
