# Consume target-compatible bytecode; never execute the target to generate it.
function (athena_package_scheme_bytecode target)
  set (ATHENA_PACKAGED_SCHEME_DIR "" CACHE PATH
    "Precompiled ATHENA .go tree for the target Guile runtime")
  if (NOT EXISTS "${ATHENA_PACKAGED_SCHEME_DIR}/.complete")
    message (FATAL_ERROR "iPadOS requires ATHENA_PACKAGED_SCHEME_DIR with a .complete stamp")
  endif ()
  file (STRINGS "${ATHENA_PACKAGED_SCHEME_DIR}/.complete" runtime_id LIMIT_COUNT 1)
  if (NOT runtime_id STREQUAL ATHENA_GUILE_RUNTIME_ID)
    message (FATAL_ERROR "Packaged Scheme bytecode runtime identity does not match the target")
  endif ()
  file (GLOB_RECURSE sources RELATIVE "${ATHENA_SOURCE_DIR}/ATHENA/progs"
    "${ATHENA_SOURCE_DIR}/ATHENA/progs/*.scm")
  set (bytecode "${ATHENA_PACKAGED_SCHEME_DIR}/.complete")
  foreach (source IN LISTS sources)
    string (REGEX REPLACE "\\.scm$" ".go" compiled "${source}")
    if (NOT EXISTS "${ATHENA_PACKAGED_SCHEME_DIR}/${compiled}")
      message (FATAL_ERROR "Missing packaged Scheme module: ${compiled}")
    endif ()
    list (APPEND bytecode "${ATHENA_PACKAGED_SCHEME_DIR}/${compiled}")
  endforeach ()
  foreach (file IN LISTS bytecode)
    file (RELATIVE_PATH relative "${ATHENA_PACKAGED_SCHEME_DIR}" "${file}")
    get_filename_component (directory "${relative}" DIRECTORY)
    set_source_files_properties ("${file}" PROPERTIES
      MACOSX_PACKAGE_LOCATION "Resources/ATHENA/lib/athena-scheme/${ATHENA_GUILE_RUNTIME_ID}/${directory}")
  endforeach ()
  target_sources (${target} PRIVATE ${bytecode})
endfunction ()
